import { MAPS, PET_SKILL_BALANCE, PET_VISUALS, QUALITY, SKILLS, SLOTS } from './data.js?v=27';
import { compareEquipment, dailyQuests, enhanceChance, enhanceCost, equipmentPower, format, recompute } from './core.js?v=27';
import { claimOffline, exportSave, importSave, resetSave, saveState } from './save.js?v=27';
import { currentObjective, progress } from './objective-system.js';
import { TUTORIAL_STEPS, restartTutorial, skipTutorial, syncTutorialStep } from './tutorial-system.js';
import { canEvolvePet, canStarPet, getPetDisplayName, getPetEffectiveAttack, getPetEffectiveHpBonus, getPetEvolutionAbilities, getPetEvolutionStage, getPetFragments, getPetSkillDefinition, getPetSkillPower, getPetSkillProfile, getPetSkillRank, getPetStarCost, previewPetStar } from './pet-system.js';
import { PET_CODEX_DATA, PET_CODEX_REWARDS, canClaimPetCodexReward, claimPetCodexReward, getCodexRewardProgress, getPetCodexBonuses, getPetCodexDisplay, getPetCodexSummary } from './pet-codex-system.js';
import { drawPet } from './pet-renderer.js';
import { getPetSupportBonuses, getPetTeamMembers } from './pet-team-system.js';
import { EQUIPMENT_AFFIX_DATA, formatEquipmentAffix } from './equipment-affix-system.js';
import { PET_TEAM_SYNERGIES, describePetTeamSynergy, getPetTeamSynergyBonuses } from './pet-synergy-system.js';
import { preloadArtAssets } from './art-asset-manager.js';
import { getSkillPhase, skillUnavailableReason } from './battle-skill-system.js?v=27';

const iconFor = slot => ({ weapon: '⚔', helmet: '◉', armor: '✦', gloves: '✧', boots: '⌁', necklace: '◈', ring: '◌', wings: '❈' }[slot] || '◇');
const qualityRank = { common: 1, uncommon: 2, rare: 3, epic: 4, legendary: 5, mythic: 6, astral: 7 };

export class AstralUI {
  constructor(state, game, renderer, makeItem) {
    this.state = state; this.game = game; this.renderer = renderer; this.makeItem = makeItem;
    this.active = 'battle'; this.logs = []; this.nextBattlePaint = 0; this.skillSignature = ''; this.petCodexFilter = 'all'; this.petCodexSort = 'region';
    this.$ = id => document.getElementById(id);
    document.addEventListener('click', event => this.handle(event));
    this.renderAll();
  }

  setState(state) { this.state = state; this.game.state = state; this.renderAll(); }
  update(state, battle) {
    this.state = state; this.battle = battle;
    const now = performance.now();
    if (now >= this.nextBattlePaint) {
      this.renderTop(); this.renderHud(); this.renderSkills(); this.renderTutorial();
      this.nextBattlePaint = now + 110;
    }
  }
  event({ title, message }) { this.logs.unshift({ title, message }); this.logs = this.logs.slice(0, 5); this.renderLog(); this.toast(`${title}：${message}`); }

  handle(event) {
    const button = event.target.closest('[data-action]'); if (!button) return;
    const action = button.dataset.action;
    if (action === 'page') this.show(button.dataset.page);
    else if (action === 'boss') { if (!this.game.challengeBoss()) this.toast('擊殺 10 隻普通怪物後才能挑戰 Boss。'); }
    else if (action === 'skill') { const index=Number(button.dataset.index); if(this.game.castSkill(index)){this.state.tutorial.manualSkills=(this.state.tutorial.manualSkills||0)+1;this.toast(`${SKILLS[index].name} 已排入施放。`);} this.renderSkills(); }
    else if (action === 'skillAuto') { const index=Number(button.dataset.index); const enabled=this.game.toggleSkill(index); this.toast(`${SKILLS[index].name} AUTO ${enabled?'開啟':'關閉'}`); this.renderSkills(); }
    else if (action === 'skillUp') { if(this.state.player.level<15)this.toast('技能升級將在 Lv.15 解鎖。'); else if (!this.game.upgradeSkill(Number(button.dataset.index))) this.toast('金幣不足。'); this.renderAll(); }
    else if (action === 'equip') { this.game.equip(button.dataset.id); this.renderAll(); }
    else if (action === 'inspect') { this.state.tutorial.inspected=(this.state.tutorial.inspected||0)+1; this.inspect(button.dataset.id); }
    else if (action === 'enhance') { const result=this.game.enhance(button.dataset.id); this.toast(result.ok?`強化成功：+${result.item.enhance}`:result.reason==='gold'?'金幣不足。':'強化失敗，裝備仍保留。'); this.renderAll(); }
    else if (action === 'bestEquip') { const count=this.game.equipBest(); this.toast(count?`已穿戴 ${count} 件最佳裝備。`:'目前已是最佳配置。'); this.renderAll(); }
    else if (action === 'sell') { this.game.sell(button.dataset.id) ? this.renderAll() : this.toast('已裝備或鎖定的裝備不能出售。'); }
    else if (action === 'lock') { this.game.toggleLock(button.dataset.id); this.renderAll(); }
    else if (action === 'pet') { this.game.setActivePet(button.dataset.id); this.renderAll(); }
    else if (action === 'petTeam') { this.game.setPetTeamSlot(button.dataset.id, button.dataset.slot); this.renderAll(); }
    else if (action === 'synergyInfo') this.openSynergyInfo();
    else if (action === 'petStar') { const result=this.game.starPet(button.dataset.id); if(result.ok){this.toast(`${getPetDisplayName(result.pet)} 升至 ${result.after.stars}★　攻擊 ${result.before.attack} → ${result.after.attack}　生命 +${result.before.hpBonus} → +${result.after.hpBonus}`);this.renderAll();}else if(result.reason==='fragments')this.toast('碎片不足，持續收服同種類寵物可取得碎片。');else if(result.reason==='max')this.toast('此寵物已達 6★ 滿星。');else if(result.reason!=='busy')this.toast('無法升星。'); }
    else if (action === 'petEvolve') { const result=this.game.evolvePet(button.dataset.id); if(result.ok){this.toast(`${result.before.stage.name} 進化為 ${result.after.stage.name}！E${result.after.rank} ★1`);this.renderAll();}else if(result.reason==='stars')this.toast('突破需要寵物達到 6★。');else if(result.reason==='level')this.toast(`突破需要 Lv.${result.cost.level}。`);else if(result.reason==='fragments')this.toast('物種碎片不足。');else if(result.reason==='gold')this.toast('金幣不足。');else if(result.reason==='core')this.toast('進化核心不足，擊敗 Boss 可獲得。');else if(result.reason==='max')this.toast('此寵物已達 E4。');else if(result.reason!=='busy')this.toast('無法突破。'); }
    else if (action === 'petCodexFilter') { this.petCodexFilter = button.dataset.filter; this.renderPetCodex(); }
    else if (action === 'petCodexSort') { this.petCodexSort = button.dataset.sort; this.renderPetCodex(); }
    else if (action === 'claimPetCodex') { const reward=claimPetCodexReward(this.state, button.dataset.id); if(reward){recompute(this.state);saveState(this.state);this.toast(`圖鑑獎勵：${reward.label}`);this.renderAll();} }
    else if (action === 'map') { this.game.setMap(Number(button.dataset.id)); this.show('battle'); }
    else if (action === 'claimQuest') this.claimQuest(button.dataset.id);
    else if (action === 'offline') this.openOffline();
    else if (action === 'modalClose') this.closeModal();
    else if (action === 'save') { saveState(this.state); this.toast('已儲存到本機瀏覽器。'); }
    else if (action === 'export') this.export();
    else if (action === 'import') this.import();
    else if (action === 'sellSetting') { const order=['none','common','uncommon','rare']; const index=order.indexOf(this.state.settings.autoSell); this.state.settings.autoSell=order[(index+1)%order.length]; this.renderSettings(); saveState(this.state); }
    else if (action === 'artTheme') { const next=this.state.settings.artTheme==='cc0-pixel'?'current':'cc0-pixel';this.state.settings.artTheme=next;saveState(this.state);this.renderSettings();if(next==='cc0-pixel'){this.toast('正在載入 CC0 像素主題…');preloadArtAssets({bundle:'cc0-region01'}).then(status=>this.toast(status.failed?'部分像素素材載入失敗，已安全保留目前美術。':'CC0 像素主題已啟用。'));}else this.toast('已切換為目前美術。'); }
    else if (action === 'reset') this.reset();
    else if (action === 'objective') { const objective=currentObjective(this.state); this.show(objective.page||'battle'); }
    else if (action === 'tutorialSkip') { skipTutorial(this.state); saveState(this.state); this.renderAll(); }
    else if (action === 'tutorialRestart') { restartTutorial(this.state); saveState(this.state); this.show('battle'); this.renderAll(); }
    else if (action === 'help') this.openHelp();
    else if (action === 'toggle') { if(button.dataset.key==='autoBoss'&&this.state.player.level<10){this.toast('自動挑戰 Boss 將在 Lv.10 解鎖。');return;} this.state.settings[button.dataset.key] = !this.state.settings[button.dataset.key]; this.renderSettings(); this.appendSettingsTools(); saveState(this.state); }
  }

  show(page) {
    this.active = page;
    document.querySelectorAll('.screen').forEach(section => section.classList.toggle('active', section.dataset.screen === page));
    document.querySelectorAll('.bottom-nav button').forEach(button => button.classList.toggle('active', button.dataset.page === page));
    if (page === 'character') this.renderCharacter(); if (page === 'equipment') this.renderEquipment(); if (page === 'pets') this.renderPets(); if (page === 'petCodex') this.renderPetCodex(); if (page === 'maps') this.renderMaps(); if (page === 'inventory') this.renderInventory(); if (page === 'quests') this.renderQuests(); if (page === 'settings') { this.renderSettings(); this.appendSettingsTools(); } this.applyLockStates(); this.renderTutorial();
  }

  renderAll() { this.skillSignature = ''; this.renderTop(); this.renderHud(); this.renderSkills(); this.renderLog(); this.renderTutorial(); ['character','equipment','pets','petCodex','maps','inventory','quests','settings'].forEach(name => { if (this.active === name) this.show(name); }); }
  appendSettingsTools() { const page=this.$('settingsPage'); if(!page||page.querySelector('.onboarding-tools'))return; const tools=document.createElement('section'); tools.className='panel onboarding-tools'; tools.innerHTML='<h3>新手與說明</h3><p>隨時可重新查看引導；已領取的新手獎勵不會重複發放。</p><button class="action" data-action="help">遊戲說明</button> <button class="action" data-action="tutorialRestart">重新開始新手教學</button>'; page.append(tools); }
  applyLockStates() { const autoBoss=document.querySelector('[data-action="toggle"][data-key="autoBoss"]'); if(autoBoss&&this.state.player.level<10){autoBoss.disabled=true;autoBoss.textContent='Lv.10 解鎖';} document.querySelectorAll('[data-action="skillUp"]').forEach(button=>{if(this.state.player.level<15){button.disabled=true;button.title='Lv.15 解鎖技能升級';}}); }
  renderTop() { const p = this.state.player; this.$('level').textContent = p.level; this.$('power').textContent = format(p.power); this.$('gold').textContent = format(p.gold); this.$('xpFill').style.width = `${Math.min(100, p.exp / p.nextExp * 100)}%`; }
  renderHud() { const p = this.state.player; const b = this.battle; this.$('mapName').textContent = MAPS[this.state.mapId - 1].name; this.$('stageLabel').textContent = `${this.state.mapId}-${this.state.stage}`; this.$('playerHp').style.width = `${p.hp / p.maxHp * 100}%`; this.$('playerHpText').textContent = `${Math.floor(p.hp)} / ${Math.floor(p.maxHp)}`; this.$('playerShield').style.width = `${Math.min(100, p.shield / (p.maxHp * .65) * 100)}%`; this.$('playerShieldText').textContent = Math.floor(p.shield); this.$('playerMp').style.width = `${p.mp / p.maxMp * 100}%`; this.$('playerMpText').textContent = `${Math.floor(p.mp)} / ${p.maxMp}`; this.$('playerRage').style.width = `${p.rage / p.maxRage * 100}%`; this.$('playerRageText').textContent = `${Math.floor(p.rage)} / ${p.maxRage}`; this.$('killProgress').textContent = `${this.state.killsInStage} / 10`; const runtime=this.state.skillRuntimeState; const casting=['queued','casting','resolving'].includes(runtime?.phase)?SKILLS.find(skill=>skill.id===runtime.skillId):null; this.$('battleState').textContent = casting ? `${casting.name}・${runtime.phase}` : b?.enemy?.boss ? `Boss：${b.enemy.name}` : b?.reviveIn > 0 ? `復甦 ${Math.ceil(b.reviveIn)} 秒` : '自動探索'; const boss = this.$('bossButton'); boss.disabled = Boolean(b?.enemy) || this.state.killsInStage < 10; boss.textContent = b?.enemy?.boss ? b.enemy.name : '挑戰 Boss'; const pet=this.state.pets.find(item=>item.id===this.state.activePetId); const readout=this.$('petSkillReadout'); if(pet){const skill=getPetSkillDefinition(pet),rank=getPetSkillRank(pet),energy=Math.floor(pet.skillEnergy||0);readout.innerHTML=rank<skill.unlockRank?`<small>${getPetDisplayName(pet)}：E1 解鎖主動技能</small>`:`<b>${skill.name}</b><span>能量 ${energy} / ${PET_SKILL_BALANCE.maxEnergy}</span><i style="width:${energy/PET_SKILL_BALANCE.maxEnergy*100}%"></i>`;}else readout.textContent='尚未派出寵物'; this.renderObjective(); }
  renderObjective() { const objective=currentObjective(this.state), value=Math.min(objective.target,progress(this.state,objective)); this.$('objectiveText').textContent=`${objective.title}（${value} / ${objective.target}）`; this.$('unlockHint').textContent=`${objective.description}　獎勵：${objective.reward.gold} 金幣`; const card=this.$('objectiveCard'); card.dataset.action='objective'; card.setAttribute('role','button'); card.setAttribute('tabindex','0'); }
  objectiveComplete(objective) { this.toast(`目標完成：${objective.title}　+${objective.reward.gold} 金幣`); syncTutorialStep(this.state); saveState(this.state); this.renderAll(); }
  unlockNotice(unlock) { this.toast(`功能解鎖：${unlock.name}　${unlock.description}`); saveState(this.state); }
  renderTutorial() { const overlay=this.$('tutorialOverlay'); if(!overlay)return; const tutorial=this.state.tutorial||{}; document.querySelectorAll('.tutorial-target').forEach(node=>node.classList.remove('tutorial-target')); if(!tutorial.active||tutorial.completed||this.active!=='battle'){overlay.hidden=true;return;} const objective=currentObjective(this.state); syncTutorialStep(this.state); const step=TUTORIAL_STEPS[tutorial.step]||TUTORIAL_STEPS[0]; const selector={battle:'#battleCanvas',inventory:'.bottom-nav [data-page="inventory"]',pets:'.bottom-nav [data-page="pets"]',maps:'.bottom-nav [data-page="maps"]'}[objective.page]||'#battleCanvas'; const target=document.querySelector(objective.id==='manual_skill'?'#skills .skill-card:first-child':objective.id==='first_boss'?'#bossButton':selector); target?.classList.add('tutorial-target'); overlay.hidden=false; overlay.innerHTML=`<section class="tutorial-popover"><small>新手引導 ${tutorial.step+1} / ${TUTORIAL_STEPS.length}</small><h2>${step.title}</h2><p>${step.text}</p><p class="tutorial-goal">目標：${objective.title}</p><div><button class="action ghost" data-action="tutorialSkip">跳過</button><button class="action" data-action="objective">前往目標</button></div><small>跳過後仍可從「設定 → 新手教學」重新查看。</small></section>`; }
  renderSkills() { const wrap=this.$('skills'); const targetValid=Boolean(this.battle?.enemy?.alive); const status=SKILLS.map(skill=>`${getSkillPhase(this.state,skill.id)}:${Math.ceil(this.state.skillCooldowns[skill.id]||0)}:${skillUnavailableReason(this.state,skill,targetValid)||'ok'}`).join('|'); const signature=`${this.state.skills.join(',')}|${JSON.stringify(this.state.skillAutoSettings)}|${status}|${this.state.skillRuntimeState?.skillId}`; if(signature===this.skillSignature)return; this.skillSignature=signature; wrap.innerHTML=SKILLS.map((skill,index)=>{const phase=getSkillPhase(this.state,skill.id),cooldown=this.state.skillCooldowns[skill.id]||0,reason=skillUnavailableReason(this.state,skill,targetValid),auto=this.state.skillAutoSettings[skill.id],cost=skill.rageCost?`${skill.rageCost} 怒`:`${skill.mpCost} MP`,active=['queued','casting','resolving'].includes(phase);return `<article class="skill-card ${auto?'':'off'} ${reason?'unavailable':''} ${active?'active-cast':''}"><button class="skill-cast" data-action="skill" data-index="${index}" ${reason?'disabled':''}><i>${['⌁','✦','◌','✹'][index]}</i><b>${skill.shortName}</b><small>Lv.${this.state.skills[index]}・${cost}</small>${cooldown>0?`<span class="cool">${Math.ceil(cooldown)}</span>`:''}${active?`<span class="cast-state">${phase}</span>`:''}</button><button class="skill-auto ${auto?'on':''}" data-action="skillAuto" data-index="${index}" aria-pressed="${auto}">AUTO ${auto?'ON':'OFF'}</button></article>`;}).join(''); }
  renderLog() { this.$('eventLog').innerHTML = this.logs.map(item => `<p><b>${item.title}</b>　${item.message}</p>`).join(''); }

  page(title, subtitle, content) { return `<section class="page"><header class="page-head"><div><h1>${title}</h1><p>${subtitle}</p></div><button class="action" data-action="page" data-page="battle">返回戰鬥</button></header>${content}</section>`; }
  renderCharacter() { const p=this.state.player,{main,support}=getPetTeamMembers(this.state),team=getPetSupportBonuses(this.state),synergy=getPetTeamSynergyBonuses(this.state);const petName=pet=>pet?getPetDisplayName(pet):'空位';const summary=[['攻擊',synergy.attack],['生命',synergy.hp],['暴擊',synergy.crit],['寵物傷害',synergy.petDamage],['Boss 傷害',synergy.bossDamage],['普通怪傷害',synergy.normalDamage],['金幣',synergy.goldBonus],['經驗',synergy.expBonus]].filter(([,value])=>value).map(([label,value])=>`${label} +${Math.round(value*100)}%`).join('・')||'尚未啟動';this.$('characterPage').innerHTML=this.page('星界冒險者','星刃使 · 持續探索星界',`<div class="panel hero-card"><div class="hero-art"></div><div><b>戰力 ${format(p.power)}</b><p>等級 ${p.level}　暴擊 ${(p.crit*100).toFixed(0)}%</p><p class="player-title">稱號：${this.state.playerTitle||'尚未取得'}</p><div class="stat-grid"><div><span>攻擊</span><b>${Math.floor(p.attack)}</b></div><div><span>生命</span><b>${Math.floor(p.maxHp)}</b></div><div><span>防禦</span><b>${Math.floor(p.defense)}</b></div><div><span>攻速</span><b>${p.attackSpeed.toFixed(2)}s</b></div></div></div></div><div class="panel team-bonus"><b>隊伍加成</b><p>主戰：${petName(main)}</p><p>支援：${support.map(petName).join('、')}</p><p>主戰攻擊 +${team.mainAttack}／生命 +${team.mainHp}<br>支援攻擊 +${team.attack}／生命 +${team.hp}<br><strong>總加成：攻擊 +${team.mainAttack+team.attack}／生命 +${team.mainHp+team.hp}</strong></p><p>啟動羈絆：${synergy.active.length}<br>${summary}</p></div><div class="panel"><b>技能成長</b>${SKILLS.map((s,i)=>`<div class="quest"><div><h3>${s.name}　Lv.${this.state.skills[i]}</h3><p>${s.description} · 冷卻 ${s.cooldown} 秒</p></div><button class="action" data-action="skillUp" data-index="${i}">升級 ${100*this.state.skills[i]}G</button></div>`).join('')}</div>`); }
  renderEquipment() { const equipped=Object.values(this.state.equipped); this.$('equipmentPage').innerHTML=this.page('星界裝備','八個部位會直接影響攻擊、生存與戰力',`<div class="panel slot-grid">${Object.entries(SLOTS).map(([id,slot])=>{const item=this.state.equipped[id];return `<div class="slot ${item?`quality-${item.quality}`:''}"><i>${iconFor(id)}</i><span>${slot.label}</span><b>${item?.name||'未裝備'}</b></div>`}).join('')}</div><div class="panel"><b>目前加成</b><p>已裝備 ${equipped.length}/8 件 · 攻擊 ${Math.floor(this.state.player.attack)} · 生命 ${Math.floor(this.state.player.maxHp)}</p><button class="action" data-action="page" data-page="inventory">前往背包更換</button></div>`); }
  renderInventory() { const items=[...this.state.inventory].sort((a,b)=>qualityRank[b.quality]-qualityRank[a.quality]||equipmentPower(b)-equipmentPower(a)); this.$('inventoryPage').innerHTML=this.page('星界背包',`${items.length} / 100 格 · 已按品質與戰力排列`, `<div class="panel"><b>自動裝備與最佳配置</b><p>${this.state.settings.autoEquip?'已開啟：較強裝備會自動穿戴。':'已關閉：掉落裝備將保留在背包。'}</p><button class="action" data-action="toggle" data-key="autoEquip">切換自動裝備</button> <button class="action" data-action="bestEquip">一鍵穿戴最佳</button></div><div class="item-list">${items.length?items.map(item=>this.item(item)).join(''):'<div class="panel">尚未取得裝備，持續擊敗怪物與 Boss 吧。</div>'}</div>`); }
  item(item) { const equipped=this.state.equipped[item.slot]?.id===item.id; const names=(item.affixes||[]).map(a=>EQUIPMENT_AFFIX_DATA[a.id]?.label).filter(Boolean); return `<article class="item-card quality-${item.quality}"><button class="icon" data-action="inspect" data-id="${item.id}">${iconFor(item.slot)}</button><div><h3>${item.name} +${item.enhance||0}</h3><p>${item.label} · Lv.${item.level} · 戰力 ${equipmentPower(item)}</p><p>詞綴 ${names.length}：${names.join('・')||'無'}</p></div><div class="tiny-actions"><button data-action="equip" data-id="${item.id}">${equipped?'已穿戴':'裝備'}</button><button data-action="enhance" data-id="${item.id}">強化</button><button data-action="inspect" data-id="${item.id}">詳情</button><button data-action="lock" data-id="${item.id}">${item.locked?'解鎖':'鎖定'}</button><button data-action="sell" data-id="${item.id}">出售</button></div></article>`; }
  inspect(id) { const item=this.state.inventory.find(entry=>entry.id===id); if(!item)return; const current=this.state.equipped[item.slot]; const comparison=compareEquipment(item,current?.id===item.id?null:current); const sign=(value,rate=false,invert=false)=>{const adjusted=invert?-value:value,shown=rate?`${Math.abs(value*100).toFixed(1)}%`:Math.round(Math.abs(value)*100)/100;return adjusted>0?`<em class="up">▲ +${shown}</em>`:adjusted<0?`<em class="down">▼ -${shown}</em>`:'<em>— 不變</em>';}; const statNames={attack:'攻擊',maxHp:'生命',defense:'防禦',crit:'暴擊率',critDamage:'暴擊傷害',attackSpeed:'攻擊間隔'}; const base=Object.entries(item.stats||{}).map(([key,value])=>{const shown=key==='attackSpeed'?`${value<0?'縮短 ':'增加 '}${Math.abs(value).toFixed(2)} 秒`:Math.abs(value)<1?`${value>=0?'+':''}${(value*100).toFixed(1)}%`:`${value>=0?'+':''}${Math.round(value)}`;return `<li>${statNames[key]||key} ${shown}</li>`;}).join('')||'<li>無基礎屬性</li>'; const affixes=(item.affixes||[]).map(formatEquipmentAffix).filter(Boolean).map(a=>`<li><b>${a.label}</b>　${a.text}</li>`).join('')||'<li>此裝備沒有隨機詞綴</li>'; const cost=enhanceCost(item),chance=Math.round(enhanceChance(item)*100); this.openModal(`${item.name} +${item.enhance||0}`,`<b>${item.label} · ${SLOTS[item.slot].label} · Lv.${item.level}</b><br>戰力 ${equipmentPower(item)} ${comparison.power>0?'· 推薦裝備':''}<br><br><b>基礎屬性</b><ul>${base}</ul><b>隨機詞綴（${item.affixes?.length||0}）</b><ul>${affixes}</ul><b>與目前裝備比較</b><br>戰力 ${sign(comparison.power)}<br>攻擊 ${sign(comparison.stats.attack)}　防禦 ${sign(comparison.stats.defense)}<br>生命 ${sign(comparison.stats.maxHp)}　暴擊 ${sign(comparison.stats.crit,true)}<br>攻擊間隔 ${sign(comparison.stats.attackSpeed,false,true)}　Boss 傷害 ${sign(comparison.stats.bossDamage,true)}<br>普通怪傷害 ${sign(comparison.stats.normalDamage,true)}　金幣 ${sign(comparison.stats.goldBonus,true)}　經驗 ${sign(comparison.stats.expBonus,true)}<br><br>下次強化：${cost} 金幣 · 成功率 ${chance}%`, `<button data-action="enhance" data-id="${item.id}">強化</button><button data-action="modalClose">關閉</button>`); }
  renderPets() {
    const pets=this.state.pets;
    const {main,support}=getPetTeamMembers(this.state),team=getPetSupportBonuses(this.state),petName=pet=>pet?getPetDisplayName(pet):'空位';
    const cards=pets.map(p=>{const check=canStarPet(this.state,p),preview=previewPetStar(p),evolution=canEvolvePet(this.state,p),stage=getPetEvolutionStage(p),abilities=getPetEvolutionAbilities(p),attack=getPetEffectiveAttack(p),hp=getPetEffectiveHpBonus(p),fragments=getPetFragments(this.state,p),cost=getPetStarCost(p.stars),skill=getPetSkillDefinition(p),skillRank=getPetSkillRank(p),profile=getPetSkillProfile(p);const teamSlot=p.id===main?.id?'main':p.id===support[0]?.id?'support1':p.id===support[1]?.id?'support2':null;const starLabel=preview.max?'已滿星':check.ok?'升星':'碎片不足';const need=evolution.cost;const evolveText=need?`下一階 E${p.evolutionRank+1}：Lv.${need.level} · 碎片 ${fragments}/${need.fragments} · 金幣 ${need.gold.toLocaleString()} · 核心 ${this.state.evolutionCores||0}/${need.core}`:'已達 E4 最終進化';const facts=[`傷害 ${Math.round(profile.power*100)}%`,profile.hits&&`段數 ${profile.hits}`,profile.critBonus&&`暴擊 +${Math.round(profile.critBonus*100)}%`,profile.critMultiplier&&`暴傷 ${Math.round(profile.critMultiplier*100)}%`,profile.heal&&`治療 ${Math.round(profile.heal*100)}%`,profile.shield&&`護盾 ${Math.round(profile.shield*100)}%`,profile.duration&&`持續 ${profile.duration}s`,profile.ticks&&`燃燒 ${profile.ticks} 次`,profile.bossBonus&&`Boss +${Math.round(profile.bossBonus*100)}%`].filter(Boolean).join(' · ');const skillText=skillRank<skill.unlockRank?`主動技能：E1 解鎖「${skill.name}」`:`技能：${skill.name}（E${skillRank}）<br><small>${facts} · 能量 ${Math.floor(p.skillEnergy||0)}/${skill.energy}</small>`;return `<article class="item-card pet-team-card quality-${p.quality}"><div class="icon">✧</div><div><h3>${getPetDisplayName(p)}　Evolution E${p.evolutionRank}　${p.stars}★ ${teamSlot?`· ${teamSlot==='main'?'主戰':teamSlot==='support1'?'支援1':'支援2'}`:''}</h3><p>定位：${stage.role || ''}　Lv.${p.level} · 攻擊 ${attack} · 生命加成 ${hp}</p><p>${skillText}</p><p>碎片 ${fragments}${preview.max?' · 已滿星':` / ${cost}`}</p>${preview.max?`<p>${evolveText}</p>`:`<p>下一星：${preview.stars}★ · 攻擊 ${attack} → ${preview.attack} · 生命 ${hp} → ${preview.hpBonus}</p>`}${abilities.length?`<p>進化能力：${abilities.map(a=>a.label).join('、')}</p>`:'<p>突破至 E1 後解鎖第一項進化能力。</p>'}</div><div class="tiny-actions team-actions"><button data-action="petTeam" data-slot="main" data-id="${p.id}">${teamSlot==='main'?'解除主戰':'設為主戰'}</button><button data-action="petTeam" data-slot="support1" data-id="${p.id}">${teamSlot==='support1'?'解除支援1':'設為支援1'}</button><button data-action="petTeam" data-slot="support2" data-id="${p.id}">${teamSlot==='support2'?'解除支援2':'設為支援2'}</button><button data-action="petStar" data-id="${p.id}" ${!check.ok?'disabled':''}>${starLabel}</button><button data-action="petEvolve" data-id="${p.id}" ${!evolution.ok?'disabled':''}>${need?'突破':'已進化'}</button></div></article>`;}).join('');
    const supportAbilities=support.filter(Boolean).flatMap(pet=>getPetEvolutionAbilities(pet).map(ability=>ability.label));
    const synergy=getPetTeamSynergyBonuses(this.state);const activeSynergies=synergy.active.length?synergy.active.map(item=>`<div class="synergy-active"><strong>${item.name}</strong><small>${describePetTeamSynergy(item)}</small></div>`).join(''):'<p>隊伍滿三隻後，可依地區、類型與進化程度啟動羈絆。</p>';
    const teamPanel=`<div class="panel pet-team"><b>寵物隊伍</b><div class="pet-team-slots"><div><small>主戰</small><strong>${petName(main)}</strong></div><div><small>支援 1</small><strong>${petName(support[0])}</strong></div><div><small>支援 2</small><strong>${petName(support[1])}</strong></div></div><p>支援提供 20% 基礎能力與完整進化被動，不會出現在戰場或施放主動技能。</p><p>目前支援：攻擊 +${team.attack} · 生命 +${team.hp}<br>被動：${supportAbilities.join('、')||'尚無'}</p><div class="synergy-list"><b>目前羈絆</b>${activeSynergies}</div><button class="action" data-action="synergyInfo">羈絆說明</button></div>`;
    this.$('petsPage').innerHTML=this.page('星靈寵物',`配置 1 隻主戰與 2 隻支援；持有進化核心：${this.state.evolutionCores||0}`, `${teamPanel}<div class="item-list">${cards||'<div class="panel">擊敗可收服怪物時，有機會出現收服光效。</div>'}</div>`);
  }
  openSynergyInfo() { const active=new Set(getPetTeamSynergyBonuses(this.state).active.map(item=>item.id));const rows=PET_TEAM_SYNERGIES.map(item=>`<div class="synergy-rule ${active.has(item.id)?'active':''}"><strong>${item.name}${active.has(item.id)?' · 已啟動':''}</strong><small>${item.description}<br>${describePetTeamSynergy(item)}</small></div>`).join('');this.openModal('寵物隊伍羈絆',rows,'<button data-action="modalClose">關閉</button>'); }
  renderPetCodex() {
    const summary=getPetCodexSummary(this.state), bonuses=getPetCodexBonuses(this.state), records=this.state.petCodex?.species||{};
    let rows=Object.keys(PET_CODEX_DATA).map(kind=>({kind,record:records[kind],display:getPetCodexDisplay(kind,records[kind]) }));
    if(this.petCodexFilter==='discovered')rows=rows.filter(row=>row.display.discovered);
    if(this.petCodexFilter==='undiscovered')rows=rows.filter(row=>!row.display.discovered);
    if(this.petCodexFilter==='regular')rows=rows.filter(row=>row.display.rarity!=='boss');
    if(this.petCodexFilter==='boss')rows=rows.filter(row=>row.display.rarity==='boss');
    rows.sort((a,b)=>this.petCodexSort==='discovered'?(Number(b.display.discovered)-Number(a.display.discovered))||a.display.region-b.display.region||a.display.baseName.localeCompare(b.display.baseName):this.petCodexSort==='stars'?(b.record?.highestStars||0)-(a.record?.highestStars||0)||a.display.region-b.display.region:this.petCodexSort==='evolution'?(b.record?.highestEvolutionRank||0)-(a.record?.highestEvolutionRank||0)||a.display.region-b.display.region:a.display.region-b.display.region||a.display.baseName.localeCompare(b.display.baseName));
    const controls=`<div class="codex-controls"><div>${[['all','全部'],['discovered','已收錄'],['undiscovered','未收錄'],['regular','普通'],['boss','Boss']].map(([id,label])=>`<button class="action ${this.petCodexFilter===id?'selected':''}" data-action="petCodexFilter" data-filter="${id}">${label}</button>`).join('')}</div><div>${[['region','區域'],['discovered','已收服優先'],['stars','星級'],['evolution','進化']].map(([id,label])=>`<button class="action ${this.petCodexSort===id?'selected':''}" data-action="petCodexSort" data-sort="${id}">${label}</button>`).join('')}</div></div>`;
    const cards=rows.map(({kind,record,display})=>{const discovered=display.discovered;const profile=discovered?getPetSkillProfile({sourceKind:kind,evolutionRank:record.highestEvolutionRank}):null;const facts=profile?[`傷害 ${Math.round(profile.power*100)}%`,profile.hits&&`${profile.hits} 段`,profile.critBonus&&`暴擊 +${Math.round(profile.critBonus*100)}%`,profile.heal&&`治療 ${Math.round(profile.heal*100)}%`,profile.shield&&`護盾 ${Math.round(profile.shield*100)}%`,profile.slow&&`減速 ${Math.round(profile.slow*100)}%`,profile.bossBonus&&`Boss +${Math.round(profile.bossBonus*100)}%`].filter(Boolean).join(' · '):'';return `<article class="codex-card ${discovered?'':'locked'}"><canvas class="codex-preview" width="116" height="106" data-codex-kind="${kind}" data-silhouette="${discovered?'0':'1'}"></canvas><div><small>${display.category} · 區域 ${display.region}</small><h3>${discovered?display.highestName:'???'}</h3><p>${discovered?`${display.baseName} · E${display.evolutionRank} · 最高 ★${record.highestStars} · Lv.${record.highestLevel}`:display.sourceHint}</p>${discovered?`<p>主動技能：${profile.rank<1?'E1 解鎖':`${profile.name} · E${profile.rank}`}<br><small>${profile.rank<1?'E1 解鎖後可查看效果。':facts}</small></p><p>定位：${display.role}</p>`:''}</div></article>`;}).join('');
    const rewards=PET_CODEX_REWARDS.map(reward=>{const value=getCodexRewardProgress(this.state,reward),claimed=this.state.petCodex?.claimedRewards?.includes(reward.id),ready=canClaimPetCodexReward(this.state,reward.id);return `<div class="codex-reward"><span>${reward.label}<small>${Math.min(value,reward.target)} / ${reward.target}</small></span><button class="action" data-action="claimPetCodex" data-id="${reward.id}" ${!ready?'disabled':''}>${claimed?'已領取':'領取'}</button></div>`;}).join('');
    this.$('petCodexPage').innerHTML=this.page('寵物圖鑑',`已收服 ${summary.captures} / 20 · 完成度 ${summary.completion}%`, `<div class="panel codex-summary"><b>總星級 ${summary.totalStars}</b><b>總進化階級 ${summary.totalEvolutionRank}</b><p>收藏加成：攻擊 +${(bonuses.attack*100).toFixed(1)}% · 生命 +${(bonuses.hp*100).toFixed(1)}% · 寵物傷害 +${(bonuses.petDamage*100).toFixed(1)}% · Boss 傷害 +${(bonuses.bossDamage*100).toFixed(1)}%</p></div>${controls}<div class="codex-grid">${cards}</div><section class="panel codex-rewards"><h2>收藏獎勵</h2>${rewards}</section>`);
    this.drawCodexPreviews(rows);
  }
  drawCodexPreviews(rows) { document.querySelectorAll('.codex-preview').forEach(canvas=>{const kind=canvas.dataset.codexKind;const entry=rows.find(row=>row.kind===kind);if(!entry)return;const pet=this.state.pets.find(item=>item.sourceKind===kind)||{sourceKind:kind,evolutionRank:entry.record?.highestEvolutionRank||0,quality:entry.display.rarity==='boss'?'epic':'rare',...(PET_VISUALS[kind]||{})};const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);drawPet(ctx,pet,{time:0,powerSave:true,silhouette:canvas.dataset.silhouette==='1'},58,59);}); }
  renderMaps() { this.$('mapsPage').innerHTML=this.page('星界地圖',`已推進至 ${MAPS[this.state.highestMap-1].name}`, MAPS.map(map=>`<article class="map-card ${map.id>this.state.highestMap?'locked':''}"><h2>${map.id}. ${map.name}</h2><p>${map.description} · Boss：${map.boss[0]}</p><button class="action" data-action="map" data-id="${map.id}" ${map.id>this.state.highestMap?'disabled':''}>${map.id===this.state.mapId?'探索中':'前往'}</button><small>普通怪：${map.mobs.map(m=>m[0]).join('、')}</small></article>`).join('')); }
  renderQuests() { const quests=dailyQuests(); this.$('questsPage').innerHTML=this.page('每日任務','依本機日期更新；獎勵只能領取一次。', `<div class="panel">今日：${this.state.quests.date}</div>${quests.map(q=>{const value=this.state.quests.progress[q.id]||0, done=value>=q.target, claimed=this.state.quests.claimed[q.id];return `<div class="panel quest"><div><h3>${q.name}</h3><p>${Math.min(value,q.target)} / ${q.target}　獎勵：${q.reward.gold} 金幣</p><div class="xp-bar"><i style="width:${Math.min(100,value/q.target*100)}%"></i></div></div><button class="action" data-action="claimQuest" data-id="${q.id}" ${!done||claimed?'disabled':''}>${claimed?'已領取':'領取'}</button></div>`}).join('')}`); }
  claimQuest(id) { const q=dailyQuests().find(item=>item.id===id); if(!q||this.state.quests.claimed[id]||(this.state.quests.progress[id]||0)<q.target)return; this.state.quests.claimed[id]=true;this.state.player.gold+=q.reward.gold;this.toast(`已領取 ${q.reward.gold} 金幣`);this.renderQuests();saveState(this.state); }
  renderSettings() { const s=this.state.settings; const sellName={none:'不自動出售',common:'普通以下',uncommon:'優良以下',rare:'稀有以下'}[s.autoSell]||'不自動出售'; const themeName=s.artTheme==='cc0-pixel'?'CC0 像素':'目前美術'; this.$('settingsPage').innerHTML=this.page('設定與存檔','所有資料僅儲存在目前瀏覽器。',`<div class="panel"><div class="setting"><span>戰鬥美術主題<small>CC0 像素目前支援第一區</small></span><button class="action" data-action="artTheme">${themeName}</button></div>${[['autoBoss','自動挑戰 Boss'],['autoAdvance','自動推進關卡'],['autoEquip','自動裝備'],['vibration','畫面震動'],['damageNumbers','傷害數字'],['powerSave','省電模式']].map(([k,n])=>`<div class="setting"><span>${n}</span><button class="action" data-action="toggle" data-key="${k}">${s[k]?'開啟':'關閉'}</button></div>`).join('')}<div class="setting"><span>自動出售</span><button class="action" data-action="sellSetting">${sellName}</button></div></div><div class="panel"><button class="action" data-action="offline">離線收益</button> <button class="action" data-action="save">手動儲存</button><br><br><button class="action" data-action="export">匯出存檔</button> <button class="action" data-action="import">匯入存檔</button><br><br><button class="action" data-action="reset">重置遊戲</button></div>`); }
  openOffline() { const pending=this.state.offlinePending; const description=pending?`離線 ${Math.floor(pending.seconds/3600)} 小時 ${Math.floor(pending.seconds%3600/60)} 分鐘<br>經驗 ${format(pending.exp)}、金幣 ${format(pending.gold)}、裝備 ${pending.equipment} 件、碎片 ${pending.fragments} 個。`:'目前沒有可領取的離線收益。'; this.openModal('離線星界收益',description,pending?`<button data-action="modalClose" data-claim="1">領取收益</button>`:'<button data-action="modalClose">確定</button>'); }
  openModal(title, text, actionHtml) { this.$('modalCard').innerHTML=`<h2>${title}</h2><p>${text}</p>${actionHtml}`; const modal=this.$('modal'); modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); const close=this.$('modalCard').querySelector('[data-action="modalClose"]'); close?.addEventListener('click',()=>{if(close.dataset.claim==='1'){const reward=claimOffline(this.state,this.makeItem);if(reward)this.toast('離線收益已加入帳戶與背包。');}this.closeModal();this.renderAll();}); }
  closeModal(){const modal=this.$('modal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true');}
  openHelp(){this.openModal('遊戲說明','<b>自動戰鬥</b><br>角色會持續攻擊怪物；點技能卡可手動施放或切換自動。<br><br><b>Boss 與地圖</b><br>每關擊敗 10 隻怪物即可挑戰 Boss；勝利會解鎖後續關卡與地圖。<br><br><b>裝備</b><br>品質越高詞綴越多；詳情中的綠色數字代表提升。可強化、穿戴或出售未鎖定裝備。<br><br><b>寵物與任務</b><br>收服怪物後可派出協同攻擊；每日任務依本機日期重置。<br><br><b>離線與存檔</b><br>離線最長累積 8 小時收益；設定頁可匯出、匯入與手動儲存。','<button data-action="modalClose">知道了</button>');}
  export(){const blob=new Blob([exportSave(this.state)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='astral-world-save.json';a.click();URL.revokeObjectURL(a.href);}
  import(){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=async()=>{try{this.setState(importSave(await input.files[0].text()));this.toast('存檔已匯入。');}catch{this.toast('匯入失敗：檔案格式不正確。');}};input.click();}
  reset(){if(!confirm('確定要重置《Astral World》存檔嗎？此動作無法復原。'))return;if(!confirm('再次確認：所有本遊戲進度都會清除。'))return;this.setState(resetSave());this.game.battle=this.game.newBattle();this.toast('已重置 Astral World 存檔。');}
  toast(message){const toast=this.$('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>toast.classList.remove('show'),2600);}
}
