import { stat, useHerb, gainExp, addItem, activeGenerals, addToFormation } from './player.js';
import { resolveDrops } from './enemy.js';
import { randomInt } from './utils.js';

export const SKILLS={powerStrike:{id:'powerStrike',name:'破陣擊',mp:6,multiplier:1.8},swiftRaid:{id:'swiftRaid',name:'疾風突',mp:10,multiplier:2.35}};
const damage=(attack,defense)=>Math.max(1,attack-defense+randomInt(-2,3));
const stop=state=>{if(state.battle)state.battle.auto=false;};
function finishWin(state){const {player,battle}=state,enemy=battle.enemy;const levels=gainExp(player,enemy.exp);player.gold+=enemy.gold;const drops=resolveDrops(enemy);drops.forEach(id=>addItem(player,id));battle.ended=true;stop(state);battle.result={win:true,exp:enemy.exp,gold:enemy.gold,drops,levels,recruited:false};battle.log.push(`擊敗 ${enemy.name}，獲得 ${enemy.exp} 經驗與 ${enemy.gold} 金。`);if(levels.length)battle.log.push(`升至 ${player.level} 級，體力與氣力完全恢復。`);}
function companionTurn(state){const {player,battle}=state;for(const general of activeGenerals(player)){const dealt=damage(general.attack,battle.enemy.defense);battle.enemy.hp=Math.max(0,battle.enemy.hp-dealt);battle.log.push(`${general.name} 協擊，造成 ${dealt} 傷害。`);if(!battle.enemy.hp){finishWin(state);return true;}}return false;}
function enemyTurn(state){const {player,battle}=state;if(battle.ended)return;const incoming=damage(battle.enemy.attack,stat(player,'defense'));const dealt=battle.defending?Math.max(1,Math.floor(incoming/2)):incoming;player.hp=Math.max(0,player.hp-dealt);battle.log.push(`${battle.enemy.name}${battle.defending?'攻向守勢中的你':'發動攻擊'}，造成 ${dealt} 傷害。`);battle.defending=false;if(!player.hp){battle.ended=true;stop(state);battle.result={win:false};battle.log.push('你力竭倒下，戰鬥結束。');}}
function attack(state,multiplier=1,label='普通攻擊'){const {player,battle}=state;const dealt=damage(Math.round(stat(player,'attack')*multiplier),battle.enemy.defense);battle.enemy.hp=Math.max(0,battle.enemy.hp-dealt);battle.log.push(`你使用${label}，對 ${battle.enemy.name} 造成 ${dealt} 傷害。`);if(!battle.enemy.hp)return finishWin(state);if(!companionTurn(state))enemyTurn(state);}
export function battleAction(state,action){const {player,battle}=state;if(!battle||battle.ended||!player.hp)return;if(action==='attack')attack(state);if(action.startsWith('skill:')){const skill=SKILLS[action.slice(6)];if(!skill)return;if(player.mp<skill.mp){battle.log.push('氣力不足，改用普通攻擊。');attack(state);}else{player.mp-=skill.mp;attack(state,skill.multiplier,skill.name);}}if(action==='defend'){battle.defending=true;battle.log.push('你擺出守勢。');if(!companionTurn(state))enemyTurn(state);}if(action==='item'){const result=useHerb(player);battle.log.push(result.message);if(result.ok&&!companionTurn(state))enemyTurn(state);}if(action==='flee'){if(Math.random()<.6){battle.ended=true;stop(state);battle.result={fled:true};battle.log.push('你成功脫離戰場。');}else{battle.log.push('撤退失敗。');enemyTurn(state);}}}
export function autoBattleAction(state){const battle=state.battle;if(!battle||battle.ended||!battle.auto||state.screen!=='battle')return;const selected=battle.autoSkill;battleAction(state,selected&&SKILLS[selected]?`skill:${selected}`:'attack');}
export function recruitDefeatedEnemy(state){const battle=state.battle;if(!battle?.result?.win||battle.result.recruited)return{ok:false,message:'目前沒有可招募的對手。'};const enemy=battle.enemy,id=`captured-${enemy.id}`;if(state.player.generals.some(g=>g.id===id))return{ok:false,message:`${enemy.name} 已在隊伍中。`};const loyalty=randomInt(48,68);state.player.generals.push({id,name:enemy.name,title:`${enemy.tier}豪傑`,attack:enemy.attack,defense:enemy.defense,loyalty,price:0,source:'戰後招募'});addToFormation(state.player,id);battle.result.recruited=true;return{ok:true,message:`${enemy.name} 加入隊伍，忠誠度 ${loyalty}。`};}
export function leaveBattle(state){const result=state.battle?.result;if(result&&!result.win)state.player.hp=Math.max(1,Math.ceil(state.player.maxHp*.35));stop(state);state.battle=null;state.screen='village';state.notice=result?.fled?'已安全返回村莊。':result?.win?'凱旋而歸。':'你被村民救回並恢復少量體力。';state.noticeType=result?.win?'good':result?.fled?'':'bad';}
