import { MAPS,BOSSES,CAPTURE_ITEMS,EQUIPMENT_TEMPLATES,QUALITY,AFFIXES } from '../data/huntingData.js';
import { randomInt,clamp,pick } from './utils.js';
const stars=[2,5,10,20];
export function migrateCore(p){p.saveVersion=3;p.hunting=p.hunting||{};p.hunting.maps=p.hunting.maps||{};MAPS.forEach(m=>p.hunting.maps[m.id]=p.hunting.maps[m.id]||{kills:0,bossDefeated:false,hiddenDefeated:false});p.hunting.mapId=MAPS.some(m=>m.id===p.hunting.mapId)?p.hunting.mapId:'plains';p.hunting.totalKills=p.hunting.totalKills||0;p.hunting.bossKills=p.hunting.bossKills||0;p.hunting.captureCount=p.hunting.captureCount||0;p.hunting.hunterRank=p.hunting.hunterRank||1;p.hunting.auto={heal:true,retreat:25,stopOnBoss:true,autoBoss:false,autoCapture:false,captureItem:'captureNormal',speed:850,logMode:'brief',...(p.hunting.auto||{})};p.bossPartners=p.bossPartners||p.bossSouls||[];p.equipmentInstances=p.equipmentInstances||Object.entries(p.inventory||{}).filter(([id,count])=>count>0&&id!=='herb').flatMap(([templateId,count])=>Array.from({length:count},()=>gear(templateId)));p.equipmentInstances=p.equipmentInstances.map(x=>x.instanceId?x:gear(x.templateId||x.id));p.captureItems={captureNormal:3,captureAdvanced:1,captureLegend:0,...(p.captureItems||{})};return p;}
export function currentMap(p){return MAPS.find(m=>m.id===p.hunting.mapId)||MAPS[0];} export function mapState(p){return p.hunting.maps[currentMap(p).id];}
export function unlocked(p,m){const idx=MAPS.indexOf(m);if(idx===0)return true;const prev=MAPS[idx-1];return p.level>=m.need*5&&p.hunting.maps[prev.id]?.bossDefeated;}
function gear(templateId){const t=EQUIPMENT_TEMPLATES.find(x=>x.id===templateId)||EQUIPMENT_TEMPLATES[0],r=Math.random(),q=QUALITY.find(x=>r<=x[2])||QUALITY[0],aff=Array.from({length:q[1]},()=>`${pick(AFFIXES)}${randomInt(2,8)}%`);return {instanceId:`g-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,templateId:t.id,name:t.name,slot:t.slot,quality:q[0],level:t.level,baseStats:{attack:t.attack,defense:t.defense},affixes:aff,locked:false,obtainedAt:Date.now()};}
export function rollGear(p){const t=pick(EQUIPMENT_TEMPLATES.filter(x=>x.level<=p.level+5));const g=gear(t.id);p.equipmentInstances.push(g);return g;}
export function spawn(p){const m=currentMap(p),s=mapState(p);if(s.kills>=m.threshold)return bossFight(m.boss,m);if(s.kills>=50&&Math.random()<.06)return bossFight(m.hidden,m,true);if(Math.random()<.1)return {kind:'elite',name:m.elite,hp:75+p.level*12,attack:10+p.level*3,defense:4+p.level,exp:30+p.level*8,gold:24+p.level*6};return {kind:'normal',name:pick(m.normal),hp:38+p.level*9,attack:7+p.level*2,defense:2+Math.floor(p.level/2),exp:15+p.level*5,gold:10+p.level*3};}
function bossFight(id,m,hidden=false){const b=BOSSES[id];return {kind:'boss',bossId:id,hidden,name:b.name,hp:b.hp,maxHp:b.hp,attack:b.attack,defense:b.defense,exp:120,gold:100,catchable:false,enraged:false};}
export function win(p,e){p.gold+=e.gold;p.exp+=e.exp;p.hunting.totalKills++;let boss=false;if(e.kind==='normal'||e.kind==='elite'){mapState(p).kills++;if(e.kind==='elite'&&Math.random()<.35)p.captureItems.captureNormal++;}else{boss=true;const s=mapState(p);s.kills=0;s.bossDefeated=true;if(e.hidden)s.hiddenDefeated=true;p.hunting.bossKills++;}const g=Math.random()<.65?rollGear(p):null;while(p.exp>=50+(p.level-1)*35){p.exp-=50+(p.level-1)*35;p.level++;p.maxHp+=20;p.hp=p.maxHp;p.baseAttack+=2;p.baseDefense++;}return {boss,g};}
export function capture(p,e,item){const b=BOSSES[e.bossId],pct=e.hp/e.maxHp;if(!b||pct>.2)return {ok:false,text:'Boss 生命尚未低於 20%。'};if(!p.captureItems[item])return {ok:false,text:'收服符不足。'};p.captureItems[item]--;const base={普通:35,精英:20,稀有:10,傳說:3}[b.rarity]||3;const low=pct<=.05?25:pct<=.1?15:5;const chance=clamp(base+low+CAPTURE_ITEMS[item].bonus+(p.hunting.hunterRank-1)*2,1,90);if(Math.random()*100<chance){const own=p.bossPartners.find(x=>x.id===b.id);if(own){own.souls=(own.souls||0)+b.soul;return {ok:true,text:`重複收服，轉為 ${b.soul} 枚魂印。`,chance,repeat:true};}p.bossPartners.push({id:b.id,name:b.name,rarity:b.rarity,level:1,exp:0,stars:1,hp:b.hp,attack:b.attack,defense:b.defense,speed:10,activeSkill:b.skills[0],passive:b.passive,souls:0,captures:1,deployed:p.bossPartners.every(x=>!x.deployed)});p.hunting.captureCount++;return {ok:true,text:`成功收服【${b.name}】！`,chance};}const fail=pick(['反擊','回復','狂暴','逃走','無事']);if(fail==='回復')e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.1);if(fail==='狂暴'){e.attack=Math.floor(e.attack*1.3);e.enraged=true;}if(fail==='逃走')e.escaped=true;return {ok:false,text:`收服失敗！Boss ${fail}。`,chance};}
export function deploy(p,id){p.bossPartners.forEach(b=>b.deployed=b.id===id);return {ok:true,text:'Boss 已上陣。'};}export function star(p,id){const b=p.bossPartners.find(x=>x.id===id),need=stars[(b?.stars||1)-1];if(!b||!need||b.souls<need)return {ok:false,text:'魂印不足或已滿星。'};b.souls-=need;b.stars++;b.attack+=Math.ceil(b.attack*.12);b.defense+=Math.ceil(b.defense*.1);return {ok:true,text:`${b.name}升至 ${b.stars} 星！`};}
