import {createGameState,startNewGame,explore,restAtVillage,advanceMonth} from './game.js';
import {render} from './ui.js';import {saveGame,loadGame} from './save.js';import {buyItem} from './shop.js';
import {useHerb,equipItem,normalizePlayer,switchFormation} from './player.js';
import {battleAction,autoBattleAction,leaveBattle,recruitDefeatedEnemy,SKILLS} from './battle.js';
import {createTavernRoster,hireGeneral} from './tavern.js';import {LOCATIONS} from '../data/mapData.js';
const state=createGameState(),app=document.querySelector('#app');let autoBattleTimer=null;
export function stopAutoBattle(){if(state.battle)state.battle.auto=false;if(autoBattleTimer!==null){clearTimeout(autoBattleTimer);autoBattleTimer=null;}}
function scheduleAutoBattle(){if(autoBattleTimer!==null)return;if(state.screen!=='battle'||!state.battle?.auto||state.battle.ended||!state.player?.hp)return;autoBattleTimer=setTimeout(()=>{autoBattleTimer=null;if(state.screen==='battle'&&state.battle?.auto&&!state.battle.ended&&state.player.hp){autoBattleAction(state);draw();}},800);}
function draw(){app.innerHTML=render(state);requestAnimationFrame(()=>{const log=app.querySelector('.battle-log');if(log)log.scrollTop=log.scrollHeight;});scheduleAutoBattle();}
function setNotice(result){state.notice=result.message;state.noticeType=result.ok?'good':'bad';}function changeScreen(screen){stopAutoBattle();state.screen=screen;}
app.addEventListener('click',event=>{const target=event.target.closest('button[data-action]');if(!target||target.disabled)return;const action=target.dataset.action;
if(action==='new'){changeScreen('create');state.notice='';}else if(action==='load'){const saved=loadGame();if(saved){state.player=normalizePlayer(saved);state.selectedMap=LOCATIONS[state.player.location]?.enemyTier?state.player.location:'forest';state.tavernRoster=createTavernRoster();changeScreen('village');state.notice=`歡迎回來，${state.player.name}。`;state.noticeType='good';}}else if(action==='help')changeScreen('help');else if(action==='menu'){changeScreen('menu');state.notice='';}else if(action==='create'){const input=document.querySelector('#name-input'),name=input?.value.trim();if(!name){input?.focus();return;}startNewGame(state,name);}else if(action==='village')changeScreen('village');else if(action==='explore')explore(state);else if(action==='rest')restAtVillage(state);else if(action==='month')advanceMonth(state);else if(['shop','inventory','character','maps','tavern'].includes(action))changeScreen(action);else if(action==='save')setNotice(saveGame(state));else if(action==='leave-battle'){stopAutoBattle();leaveBattle(state);}else if(action==='recruit-enemy')setNotice(recruitDefeatedEnemy(state));else if(action.startsWith('explore-map:'))explore(state,action.slice(12));else if(action.startsWith('buy:'))setNotice(buyItem(state.player,action.slice(4)));else if(action.startsWith('hire:'))setNotice(hireGeneral(state.player,state.tavernRoster,action.slice(5)));else if(action.startsWith('formation:'))setNotice(switchFormation(state.player,action.slice(10)));else if(action.startsWith('use:'))setNotice(useHerb(state.player));else if(action.startsWith('equip:'))setNotice(equipItem(state.player,action.slice(6)));else if(action==='auto:start'){state.battle.auto=true;state.battle.log.push('自動戰鬥開始。');}else if(action==='auto:stop'){stopAutoBattle();state.battle.log.push('自動戰鬥已停止。');}else if(action.startsWith('battle:')){stopAutoBattle();battleAction(state,action.slice(7));}draw();});
app.addEventListener('change',event=>{if(event.target.matches('#auto-skill')&&state.battle){state.battle.autoSkill=SKILLS[event.target.value]?event.target.value:'';state.battle.log.push(state.battle.autoSkill?`自動戰鬥將優先使用${SKILLS[state.battle.autoSkill].name}。`:'自動戰鬥將使用普通攻擊。');draw();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAutoBattle();});window.addEventListener('pagehide',stopAutoBattle);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));draw();
