import { ITEMS, SHOP_ITEMS } from '../data/itemData.js';
import { LOCATIONS, ADVENTURE_MAPS } from '../data/mapData.js';
import { stat, expNeeded, activeGenerals } from './player.js';
import { escapeHtml } from './utils.js';
import { hasSave } from './save.js';

// 所有 HTML 畫面集中渲染，事件委派由 main.js 處理。
const button=(action,text,extra='')=>`<button data-action="${action}" ${extra}>${text}</button>`;
const nameOf=id=>ITEMS[id]?.name||'無';
function header(){return `<header class="masthead"><h1 class="title">群雄天下</h1><div class="subtitle">Demo v0.0.1 · 亂世之中，從一座小村開始</div></header>`;}
function notice(state){return state.notice?`<div class="notice ${state.noticeType}">${escapeHtml(state.notice)}</div>`:'';}
function playerBar(p){return `<div class="topbar"><span><strong>${escapeHtml(p.name)}</strong> Lv.${p.level} · 第 ${p.month} 月</span><span>HP <strong>${p.hp}/${p.maxHp}</strong></span><span>金錢 <strong>${p.gold}</strong></span></div>`;}
function stats(p){return `<div class="stat-grid"><div class="stat">等級<b>${p.level}</b></div><div class="stat">HP<b>${p.hp}/${p.maxHp}</b></div><div class="stat">攻擊<b>${stat(p,'attack')}</b></div><div class="stat">防禦<b>${stat(p,'defense')}</b></div><div class="stat">EXP<b>${p.exp}/${expNeeded(p)}</b></div><div class="stat">武將<b>${p.generals?.length||0}</b></div></div>`;}
function menu(){return `<section class="screen card"><p class="lead">烽火連天，英雄不問出處。你的傳奇，即將在這裡揭幕。</p><div class="menu">${button('new','開始遊戲','class="btn-main"')}${button('load','讀取存檔',hasSave()?'':'disabled title="尚無存檔"')}${button('help','遊戲說明')}</div><p class="hint">本遊戲使用瀏覽器 LocalStorage 保存進度。</p></section>`;}
function create(){const p={level:1,hp:100,maxHp:100,baseAttack:10,baseDefense:5,equipment:{weapon:null,armor:null},exp:0,generals:[]};return `<section class="screen card"><h2 class="section-title">建立角色</h2><p class="lead">為即將踏上亂世的旅人命名。</p><label class="field">角色姓名<input id="name-input" maxlength="12" aria-label="角色姓名" autocomplete="off"></label>${stats(p)}<div class="menu">${button('create','建立角色','class="btn-main"')}${button('menu','返回主選單')}</div></section>`;}
function village(state){const p=state.player;return `<section class="screen card">${playerBar(p)}<h2 class="section-title">${LOCATIONS.village.name}</h2><p class="lead">${escapeHtml(LOCATIONS.village.description)}</p>${notice(state)}<div class="village-actions">${button('maps','世界地圖','class="btn-main"')}${button('tavern','酒館招募')}${button('shop','商店')}${button('inventory','背包')}${button('character','角色與武將')}${button('month','度過本月','class="btn-good"')}${button('save','存檔','class="btn-good"')}${button('rest','村中休息')}${button('menu','返回主選單','class="btn-danger"')}</div></section>`;}
function maps(state){const p=state.player;return `<section class="screen card">${playerBar(p)}<h2 class="section-title">世界地圖</h2><p class="lead">選擇目的地。不同地圖會遭遇固定位階的敵人。</p><div class="item-list">${ADVENTURE_MAPS.map(map=>`<article class="item"><div><h3>${map.name} <span class="equip">${map.label}</span></h3><p>${map.description}<br>敵人位階：${map.enemyTier}</p></div><div class="item-actions">${button(`explore-map:${map.id}`,'前往探索','class="btn-main"')}</div></article>`).join('')}</div><div class="back">${button('village','返回村莊')}</div></section>`;}
function items(p){const ids=Object.keys(p.inventory).filter(id=>p.inventory[id]>0);if(!ids.length)return '<p class="empty">背包目前是空的。</p>';return `<div class="item-list">${ids.map(id=>{const it=ITEMS[id];const equipped=p.equipment.weapon===id||p.equipment.armor===id;return `<article class="item"><div><h3>${it.name} × ${p.inventory[id]} ${equipped?'<span class="equip">（已裝備）</span>':''}</h3><p>${it.description}</p></div><div class="item-actions">${it.type==='consumable'?button(`use:${id}`,'使用'):''}${(it.type==='weapon'||it.type==='armor')?button(`equip:${id}`,equipped?'重新裝備':'裝備'):''}</div></article>`;}).join('')}</div>`;}
function inventory(state){return `<section class="screen card">${playerBar(state.player)}<h2 class="section-title">背包與裝備</h2>${notice(state)}<div class="notice">目前武器：${nameOf(state.player.equipment.weapon)}<br>目前護甲：${nameOf(state.player.equipment.armor)}</div>${items(state.player)}<div class="back">${button('village','返回村莊')}</div></section>`;}
function generalList(p){if(!p.generals.length)return '<p class="empty">尚無武將。可在酒館招募，或在戰勝敵人後選擇降服。</p>';return `<div class="item-list">${p.generals.map(g=>{const following=p.formation.includes(g.id);return `<article class="item"><div><h3>${escapeHtml(g.name)} <span class="equip">${escapeHtml(g.title)}${following?'・隨行中':''}</span></h3><p>來源：${escapeHtml(g.source)}　攻擊 ${g.attack}／防禦 ${g.defense}<br>忠誠：<strong>${g.loyalty}/100</strong></p></div><div class="item-actions">${button(`formation:${g.id}`,following?'撤下':'加入隨行',g.loyalty<=0?'disabled':'')}</div></article>`;}).join('')}</div>`;}
function character(state){const p=state.player;return `<section class="screen card">${playerBar(p)}<h2 class="section-title">角色與武將</h2>${stats(p)}<div class="notice">武器：${nameOf(p.equipment.weapon)}　護甲：${nameOf(p.equipment.armor)}<br>隨行隊伍：${activeGenerals(p).map(g=>g.name).join('、')||'尚未編組'}（最多 3 位）<br>距離下一級還需 ${expNeeded(p)-p.exp} EXP。</div>${notice(state)}<h3 class="section-title">麾下武將</h3>${generalList(p)}<div class="back">${button('village','返回村莊')}</div></section>`;}
function shop(state){const p=state.player;return `<section class="screen card">${playerBar(p)}<h2 class="section-title">村莊商店</h2><p class="lead">裝備購入後可在背包隨時裝備，舊裝備會自動放回背包。</p>${notice(state)}<div class="item-list">${SHOP_ITEMS.map(id=>{const it=ITEMS[id];return `<article class="item"><div><h3>${it.name}</h3><p>${it.description}　售價：${it.price} 金錢</p></div><div class="item-actions">${button(`buy:${id}`,'購買')}</div></article>`;}).join('')}</div><div class="back">${button('village','返回村莊')}</div></section>`;}
function tavern(state){const p=state.player;const roster=state.tavernRoster||[];return `<section class="screen card">${playerBar(p)}<h2 class="section-title">酒館</h2><p class="lead">第 ${p.month} 月的來客正在等候明主。每月會有新的人選到訪。</p>${notice(state)}${roster.length?`<div class="item-list">${roster.map(g=>`<article class="item"><div><h3>${g.name} <span class="equip">${g.title}</span></h3><p>攻擊 ${g.attack}／防禦 ${g.defense}／忠誠 ${g.loyalty}<br>招募費：${g.price} 金錢</p></div><div class="item-actions">${button(`hire:${g.id}`,'招募')}</div></article>`).join('')}</div>`:'<p class="empty">本月酒館已無可招募武將，請度過本月再來。</p>'}<div class="back">${button('village','返回村莊')}</div></section>`;}
function battle(state){const {player:p,battle:b}=state;const e=b.enemy;const r=b.result;const companions=activeGenerals(p);let result='';if(r){if(r.win){const recruit=r.recruited?'<br><span class="equip">已成功降服此敵人。</span>':`<br>${button('recruit-enemy',`降服${e.name}`,'class="btn-good"')}`;result=`<div class="result"><h3>戰鬥勝利</h3>獲得 ${r.exp} EXP、${r.gold} 金錢。${r.drops.length?`<br>掉落物品：${r.drops.map(id=>ITEMS[id].name).join('、')}。`:'<br>沒有物品掉落。'}${r.levels.length?`<br>等級提升至 ${p.level}！`:''}${recruit}<br>${button('leave-battle','返回村莊','class="btn-main"')}</div>`;}else result=`<div class="result"><h3>${r.fled?'成功逃跑':'戰鬥失敗'}</h3>${r.fled?'你避開了這場危機。':'你帶著傷勢被送回村莊。'}<br>${button('leave-battle','返回村莊')}</div>`;}const companionStatus=companions.length?`<div class="notice good">隨行武將：${companions.map(g=>`${escapeHtml(g.name)}（攻 ${g.attack}／防 ${g.defense}）`).join('、')}。他們會在每回合協同攻擊。</div>`:'<div class="notice">目前沒有隨行武將；在角色與武將頁編組後，最多三位武將可協同作戰。</div>';const autoStatus=b.auto&&!r?'<div class="notice good">自動攻擊中：下一回合即將進行。點選下方任一指令可切換為手動戰鬥。</div>':'';return `<section class="screen card battle-stage">${playerBar(p)}<h2 class="section-title">${e.tier} · ${b.mapName||'蒼林'}戰鬥</h2><div class="combatants"><div class="fighter"><h3>${escapeHtml(p.name)}</h3><div class="hp">HP ${p.hp}/${p.maxHp}</div><small>攻 ${stat(p,'attack')}／防 ${stat(p,'defense')}</small></div><div class="vs">VS</div><div class="fighter"><h3>${e.name}</h3><div class="hp">HP ${e.hp}/${e.maxHp}</div><small>${e.tier}　攻 ${e.attack}／防 ${e.defense}</small></div></div>${companionStatus}${autoStatus}<div class="battle-log">${b.log.map(escapeHtml).join('<br>')}</div>${r?result:`<div class="battle-actions">${button('battle:attack','攻擊')}${button('battle:defend','防禦')}${button('battle:item','使用藥草')}${button('battle:flee','逃跑','class="btn-danger"')}</div>`}</section>`;}
function help(){return `<section class="screen card"><h2 class="section-title">遊戲說明</h2><p class="lead">世界地圖分為蒼林（小怪）、斷崖嶺（菁英）與黑風寨（BOSS），每次探索皆有 70% 機率遇怪、20% 機率取得藥草、10% 無事件。戰鬥可自動進行，也可點選指令切換手動控制。</p><p class="lead">戰勝敵人可獲得 EXP、金錢與掉落物，並能選擇降服敵人為武將。在角色與武將頁可自由編組或撤下隨行武將，最多三位會協同作戰。酒館每月提供三位可招募武將；忠誠會隨每月事件浮動，降至 0 的武將將離去。</p><p class="lead">商店販售武器、護甲與藥草。購買後可在背包使用或裝備。度過本月會發生隨機事件並更新酒館來客。</p><div class="back">${button('menu','返回主選單')}</div></section>`;}
export function render(state){let content=state.screen==='menu'?menu():state.screen==='create'?create():state.screen==='village'?village(state):state.screen==='maps'?maps(state):state.screen==='shop'?shop(state):state.screen==='tavern'?tavern(state):state.screen==='inventory'?inventory(state):state.screen==='character'?character(state):state.screen==='battle'?battle(state):help();return `<div class="app-wrap">${header()}${content}</div>`;}
