import {ITEMS,SHOP_ITEMS} from '../data/itemData.js';import {LOCATIONS,ADVENTURE_MAPS} from '../data/mapData.js';import {stat,expNeeded,activeGenerals} from './player.js';import {escapeHtml} from './utils.js';import {hasSave} from './save.js';import {SKILLS} from './battle.js';
const button=(action,text,extra='')=>`<button type="button" data-action="${action}" ${extra}>${text}</button>`,nameOf=id=>ITEMS[id]?.name||'無';
const header=()=>`<header class="masthead"><h1 class="title">群雄天下</h1><div class="subtitle">原創三國文字冒險</div></header>`;
const notice=s=>s.notice?`<div class="notice ${s.noticeType}">${escapeHtml(s.notice)}</div>`:'';
const playerBar=p=>`<div class="topbar"><span><strong>${escapeHtml(p.name)}</strong> Lv.${p.level} · 第 ${p.month} 月</span><span>HP <strong>${p.hp}/${p.maxHp}</strong> · MP <strong>${p.mp}/${p.maxMp}</strong></span><span>金 <strong>${p.gold}</strong></span></div>`;
const stats=p=>`<div class="stat-grid"><div class="stat">等級<b>${p.level}</b></div><div class="stat">HP<b>${p.hp}/${p.maxHp}</b></div><div class="stat">MP<b>${p.mp}/${p.maxMp}</b></div><div class="stat">攻擊<b>${stat(p,'attack')}</b></div><div class="stat">防禦<b>${stat(p,'defense')}</b></div><div class="stat">EXP<b>${p.exp}/${expNeeded(p)}</b></div></div>`;
function menu(){return `<section class="screen card"><p class="lead">亂世初起，你將從邊境村落出發，招攬豪傑、整備隊伍，走出自己的天下之路。</p><div class="menu">${button('new','開始新旅程','class="btn-main"')}${button('load','讀取存檔',hasSave()?'':'disabled')}${button('help','遊戲說明')}</div></section>`;}
function create(){return `<section class="screen card"><h2 class="section-title">建立角色</h2><label class="field">角色姓名<input id="name-input" maxlength="12" autocomplete="off"></label>${stats({level:1,hp:100,maxHp:100,mp:24,maxMp:24,baseAttack:10,baseDefense:5,equipment:{},exp:0})}<div class="menu">${button('create','踏上旅程','class="btn-main"')}${button('menu','返回')}</div></section>`;}
function village(s){const p=s.player;return `<section class="screen card">${playerBar(p)}<h2 class="section-title">${LOCATIONS.village.name}</h2><p class="lead">${LOCATIONS.village.description}</p>${notice(s)}<div class="village-actions">${button('maps','冒險地圖','class="btn-main"')}${button('tavern','武將酒館')}${button('shop','商店')}${button('inventory','背包與裝備')}${button('character','角色與編組')}${button('month','推進一月','class="btn-good"')}${button('save','儲存進度','class="btn-good"')}${button('rest','村中休息')}${button('menu','主選單','class="btn-danger"')}</div></section>`;}
function maps(s){return `<section class="screen card">${playerBar(s.player)}<h2 class="section-title">冒險地圖</h2><div class="item-list">${ADVENTURE_MAPS.map(m=>`<article class="item"><div><h3>${m.name} <span class="equip">${m.label}</span></h3><p>${m.description}<br>威脅：${m.enemyTier}</p></div>${button(`explore-map:${m.id}`,'前往探索','class="btn-main"')}</article>`).join('')}</div><div class="back">${button('village','返回村莊')}</div></section>`;}
function itemList(p){const ids=Object.keys(p.inventory).filter(id=>p.inventory[id]>0);return ids.length?`<div class="item-list">${ids.map(id=>{const it=ITEMS[id],eq=p.equipment.weapon===id||p.equipment.armor===id;return `<article class="item"><div><h3>${it.name} × ${p.inventory[id]} ${eq?'<span class="equip">已裝備</span>':''}</h3><p>${it.description}</p></div><div class="item-actions">${it.type==='consumable'?button(`use:${id}`,'使用'):''}${['weapon','armor'].includes(it.type)?button(`equip:${id}`,eq?'替換':'裝備'):''}</div></article>`;}).join('')}</div>`:'<p class="empty">背包目前是空的。</p>';}
function inventory(s){const p=s.player;return `<section class="screen card">${playerBar(p)}<h2 class="section-title">背包與裝備</h2>${notice(s)}<div class="notice">武器：${nameOf(p.equipment.weapon)}<br>護甲：${nameOf(p.equipment.armor)}</div>${itemList(p)}<div class="back">${button('village','返回村莊')}</div></section>`;}
function generals(p){return p.generals.length?`<div class="item-list">${p.generals.map(g=>{const on=p.formation.includes(g.id);return `<article class="item"><div><h3>${escapeHtml(g.name)} <span class="equip">${on?'隨行中':escapeHtml(g.title)}</span></h3><p>攻擊 ${g.attack} · 防禦 ${g.defense} · 忠誠 ${g.loyalty}/100</p></div>${button(`formation:${g.id}`,on?'撤下':'編入')}</article>`;}).join('')}</div>`:'<p class="empty">尚未招募武將。</p>';}
function character(s){const p=s.player;return `<section class="screen card">${playerBar(p)}<h2 class="section-title">角色與編組</h2>${stats(p)}<div class="notice">隨行武將：${activeGenerals(p).map(g=>g.name).join('、')||'無'}（最多 3 位）</div>${notice(s)}${generals(p)}<div class="back">${button('village','返回村莊')}</div></section>`;}
function shop(s){return `<section class="screen card">${playerBar(s.player)}<h2 class="section-title">村莊商店</h2>${notice(s)}<div class="item-list">${SHOP_ITEMS.map(id=>{const it=ITEMS[id];return `<article class="item"><div><h3>${it.name}</h3><p>${it.description} · ${it.price} 金</p></div>${button(`buy:${id}`,'購買')}</article>`;}).join('')}</div><div class="back">${button('village','返回村莊')}</div></section>`;}
function tavern(s){return `<section class="screen card">${playerBar(s.player)}<h2 class="section-title">武將酒館</h2>${notice(s)}<div class="item-list">${s.tavernRoster.map(g=>`<article class="item"><div><h3>${g.name} <span class="equip">${g.title}</span></h3><p>攻擊 ${g.attack} · 防禦 ${g.defense} · 忠誠 ${g.loyalty} · ${g.price} 金</p></div>${button(`hire:${g.id}`,'招募')}</article>`).join('')||'<p class="empty">本月無人投宿。</p>'}</div><div class="back">${button('village','返回村莊')}</div></section>`;}
function battle(s){const p=s.player,b=s.battle,e=b.enemy,r=b.result;const skills=Object.values(SKILLS).map(sk=>`<option value="${sk.id}" ${b.autoSkill===sk.id?'selected':''}>${sk.name}（${sk.mp} MP）</option>`).join('');let result='';if(r?.win)result=`<div class="result"><h3>戰鬥勝利</h3>經驗 ${r.exp} · 金 ${r.gold}<br>${r.recruited?'已招募對手':button('recruit-enemy',`招募 ${e.name}`,'class="btn-good"')}<br>${button('leave-battle','返回村莊','class="btn-main"')}</div>`;else if(r)result=`<div class="result"><h3>${r.fled?'成功撤退':'戰鬥失敗'}</h3>${button('leave-battle','返回村莊')}</div>`;return `<section class="screen card battle-stage">${playerBar(p)}<h2 class="section-title">${e.tier} · ${b.mapName}</h2><div class="combatants"><div class="fighter"><h3>${escapeHtml(p.name)}</h3><div class="hp">HP ${p.hp}/${p.maxHp}</div><small>MP ${p.mp}/${p.maxMp}</small></div><div class="vs">VS</div><div class="fighter"><h3>${e.name}</h3><div class="hp">HP ${e.hp}/${e.maxHp}</div></div></div><div class="auto-panel"><label for="auto-skill">自動策略</label><select id="auto-skill" ${r?'disabled':''}><option value="">普通攻擊</option>${skills}</select>${!r?(b.auto?button('auto:stop','停止自動','class="btn-danger"'):button('auto:start','開始自動','class="btn-good"')):''}<small>技能 MP 不足時會自動改用普通攻擊</small></div><div class="battle-log" role="log" aria-live="polite">${b.log.map(escapeHtml).join('<br>')}</div>${r?result:`<div class="battle-actions">${button('battle:attack','普通攻擊')}${button('battle:skill:powerStrike','破陣擊')}${button('battle:defend','防禦')}${button('battle:item','使用藥草')}${button('battle:flee','撤退','class="btn-danger"')}</div>`}</section>`;}
function help(){return `<section class="screen card"><h2 class="section-title">遊戲說明</h2><p class="lead">從冒險地圖探索並進入回合制戰鬥。你可以手動攻擊、防禦、使用道具或撤退，也能設定技能後啟動自動戰鬥。自動戰鬥會在勝負、停止、離開頁面或切換畫面時終止。</p><p class="lead">勝利可獲得經驗、金錢、物品，並可能招募對手。酒館武將可編入三人隨行隊伍。所有進度保存在目前瀏覽器。</p>${button('menu','返回主選單')}</section>`;}
export function render(s){const views={menu,create,village,maps,inventory,character,shop,tavern,battle,help};const view=views[s.screen]||help;return `<div class="app-wrap">${header()}${view(s)}</div>`;}
