import { esc, dialogueComposer } from './ui.js';
export function modeBar(state,error='') {
  return `<section class="panel ai-mode"><div><span class="tag">${state.ai.mode==='ai'?'✦ AI 動態劇情':'◇ 離線／模板劇情'}</span><button class="text-button" data-action="ai-settings">設定 AI</button></div>${state.ai.mode==='ai'?`<p class="muted fine">即時生成 · 驗證成功才保存${state.ai.checkpoint?' · 可重寫本幕':''}</p>${state.ai.checkpoint?'<button class="secondary" data-action="ai-rewrite">↻ 重寫這一幕</button>':''}`:'<button class="secondary" data-action="ai-mode" data-id="ai">切換 AI 動態劇情（推薦）</button>'}${error?`<div class="ai-error" role="alert"><p>${esc(error)}</p><p>本次生成未提交，原旅程保留。</p><button class="secondary" data-action="ai-retry">重新生成</button><button class="secondary" data-action="ai-mode" data-id="offline">切換離線模式</button></div>`:''}</section>`;
}
export function aiWelcome(state) {
  return `<section class="panel"><span class="eyebrow">AI GAME MASTER</span><h1>下一幕，還沒有人寫過。</h1><p>AI 帶你進入正在發生的事件。閱讀劇情，點選 ①②③；角色會記得你的決定。</p><p class="muted">先到 AI 設定填入本次使用的金鑰，或使用自己的 Proxy。每幕會將相關遊戲資料傳給你選擇的 Provider，並可能產生 API 費用。</p><div class="button-grid"><button class="primary" data-action="ai-generate">生成${state.turn?'下一幕':'開場'} →</button><button class="secondary" data-action="ai-settings">設定 AI 連線</button><button class="secondary" data-action="ai-mode" data-id="offline">先玩離線劇情</button></div><details class="custom-action"><summary>✎ 自訂行動</summary>${dialogueComposer()}</details></section>`;
}
export function aiSettings(state,credentials) {
  const c=credentials.config;
  return `<section class="panel"><span class="eyebrow">STORY / AI 劇情</span><h2>讓故事即時生長</h2><p>推薦 AI 動態劇情；離線模式仍可隨時遊玩。</p><div class="button-grid"><button class="${state.ai.mode==='ai'?'primary':'secondary'}" data-action="ai-mode" data-id="ai">AI 動態劇情</button><button class="${state.ai.mode==='offline'?'primary':'secondary'}" data-action="ai-mode" data-id="offline">離線／模板劇情</button></div><form id="ai-form" autocomplete="off"><label>Provider<select name="provider" id="ai-provider">${[['openai','OpenAI'],['openrouter','OpenRouter'],['compatible','OpenAI 相容 API'],['proxy','自己的 Backend / Proxy']].map(([v,label])=>`<option value="${v}" ${v===c.provider?'selected':''}>${label}</option>`).join('')}</select></label><label>Model<input name="model" value="${esc(c.model)}" maxlength="100" required></label><label>Base URL<input name="baseURL" id="ai-base-url" type="url" value="${esc(c.baseURL)}" required ${['openai','openrouter'].includes(c.provider)?'readonly':''}></label><small>填到 /v1 等 API 根路徑；程式會接上 /chat/completions。Proxy 須相容此格式。</small><label>API Key／Proxy Token<input type="password" name="apiKey" autocomplete="new-password" maxlength="500" placeholder="${credentials.hasKey?credentials.maskedKey:'只在本次分頁使用'}"></label><label><input id="ai-remember" type="checkbox" name="rememberKey" ${credentials.remembered?'checked':''}>記住 API Key（僅儲存在這台裝置）</label><p class="muted fine">${credentials.remembered?'API Key 已儲存在此裝置':credentials.hasKey?'API Key 僅在本次分頁使用':'尚未設定 API Key'}</p><label>Temperature / Creativity<input name="temperature" type="number" min="0" max="2" step="0.1" value="${c.temperature}" required></label><div class="button-grid"><button class="primary" type="submit">套用本次設定</button><button class="secondary" type="submit" name="operation" value="test">測試連線</button></div></form><button class="text-button" data-action="ai-clear-key">清除已儲存 Key</button><p id="ai-connection-result" role="status" class="muted fine">${esc(credentials.storageError||'')}</p><p class="muted fine">預設只在本次分頁使用。勾選記住後，金鑰與連線設定儲存在這台裝置的瀏覽器，與遊戲存檔分開；不加入匯出或 GitHub。共用裝置請勿勾選。清除網站資料、私密瀏覽結束或瀏覽器清理資料可能移除金鑰。只輸入你信任的端點，API Key 會傳給該端點。適合私人單人使用；多人服務請使用自己管理並有驗證的 Proxy，勿分享金鑰。</p><p class="muted fine">純 GitHub Pages 不提供 AI 額度。OpenAI 預設模型為 gpt-4.1-mini；需你的 API 帳戶權限。OpenRouter 預設 cognitivecomputations/dolphin-mistral-24b-venice-edition；尚未進行真實模型推論或成人對話品質測試。相容 API 必須支援 JSON mode、temperature 及 CORS。未部署具登入、限額與伺服器金鑰的後端，並非免設定 AI。</p></section>`;
}
export function aiJournal(state) {
  const a=state.ai;
  if(!a.recent.length&&!Object.keys(a.entities).length)return '';
  const cards=Object.values(a.quests).concat(Object.values(a.threads));
  return `<details class="panel"><summary>世界記憶 · ${Object.keys(a.facts).length} 個重要事實</summary><p class="muted">最近 ${a.recent.length} 幕 · 已摘要 ${a.compactedScenes} 幕 · 世界時間 ${a.minutes} 分鐘</p><h3>任務與伏筆</h3>${cards.map(q=>`<p><b>${esc(q.title)}</b> · ${esc({active:'進行中',resolved:'已完成',failed:'已失敗'}[q.status])}<br>${esc(q.description)}</p>`).join('')||'<p>尚無未完成委託。</p>'}<h3>世界新事物</h3>${Object.values(a.entities).slice(-20).map(e=>`<p><b>${esc(e.name)}</b>${e.kind==='item'?` × ${state.inventory[e.id]||0}`:''}<br>${esc(e.description)}</p>`).join('')}<h3>重要記憶</h3>${Object.values(a.facts).slice(-20).map(f=>`<p>${esc(f.text)}</p>`).join('')}<h3>舊幕摘要</h3>${a.summaries.map(s=>`<p class="muted">${esc(s)}</p>`).join('')}</details>`;
}
