import { inspectTarget } from './gimmick-engine.js';
import { intimacyDialogue } from '../data/intimacy/dialogue.js';
import { getCharacter } from './character-engine.js';
import { statLabel, worlds } from './world-engine.js';
export const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paragraphs = text => String(text).split('\n\n').map(p=>`<p>${esc(p)}</p>`).join('');
const button = (action,label,cls='secondary',extra='') => `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const heading = (kicker,title,description='') => `<div class="page-heading"><span class="eyebrow">${kicker}</span><h1>${title}</h1>${description ? `<p>${description}</p>` : ''}</div>`;
const metric = (label,value,kind) => `<div class="metric ${kind}"><div><span>${label}</span><strong>${value}<small> / 100</small></strong></div><progress max="100" value="${value}" aria-label="${label}"></progress></div>`;
function baseStatusBar(state,world) { return `<section class="world-bar"><div><span class="live-dot"></span>${esc(world.name)}<small>${esc(world.locations.find(l=>l.id===state.location)?.name || state.ai?.locations[state.location]?.name)}</small></div><span class="turn">第 ${String(state.turn+1).padStart(2,'0')} 幕</span></section><section class="player-bar"><span class="player-name">${esc(state.player.name)} <small>${state.player.age} 歲</small></span><div>${Object.entries(world.stats).map(([k,d])=>`<span><small>${esc(d.name)}</small>${esc(statLabel(d,state.stats[k]))}</span>`).join('')}</div></section>`; }
export function landing(state,world) {
  return `<section class="landing"><div class="orbit" aria-hidden="true"><span>夢</span></div><span class="eyebrow">每一個選擇，都有人記得</span><h1>入夢，<br>遇見另一種人生。</h1><p>世界不止一個。<br>你的旅程，從這一步開始。</p><article class="world-cover"><span class="tag">${esc(world.theme)} · 獨立旅程</span><h2>${esc(world.name)}</h2><p>${esc(world.description)}</p><div class="cover-foot"><span>${esc(state.player.name)} · ${state.player.age} 歲<br><small>${esc(state.player.identity)} / ${esc(state.gimmick.name)}</small></span><span class="seal" aria-hidden="true">入<br>夢</span></div></article>${button('start','踏入'+esc(world.name)+' <span>→</span>','primary enter')}<div class="landing-note">三個選項，一步一步走進故事。<br>成年角色 · 自願互動 · 自動保存於此裝置</div></section>`;
}
export function story(state,world,scene) {
  const deltas=[];
  for(const [id,changes] of Object.entries(state.lastOutcome?.changes?.characters || {})) for(const [key,label] of [['affection','好感'],['trust','信任'],['intimacy','親密']]) if(changes[key]) deltas.push(`${getCharacter(state,id)?.name} ${label} ${changes[key]>0?'+':''}${changes[key]}`);
  for(const [key,n] of Object.entries(state.lastOutcome?.changes?.stats || {})) deltas.push(`${world.stats[key].name} ${n>0?'+':''}${n}`);
  return `${state.ai?.mode==='ai'?`<details class="panel conversation-status"><summary>${esc(world.name)} · 第 ${state.turn+1} 幕 · 查看狀態</summary>${statusBar(state,world)}</details>`:statusBar(state,world)}<section class="story-panel"><div class="scene-meta"><span class="eyebrow">${esc(scene.eyebrow)}</span><span class="chapter-mark">✧</span></div>${state.lastOutcome ? `<details class="outcome" open><summary>你的選擇，留下了回聲</summary><p>${esc(state.lastOutcome.text)}</p>${deltas.length?`<div class="deltas">${deltas.map(s=>`<span>${esc(s)}</span>`).join('')}</div>`:''}</details>`:''}<h1>${esc(scene.title)}</h1>${scene.speaker?`<div class="speaker"><span>${esc(scene.speaker.slice(0,1))}</span>${esc(scene.speaker)}</div>`:''}<div class="prose">${paragraphs(scene.sceneText)}</div>${scene.aside?`<aside class="system-note"><span>◇ 系統低語</span><p>${esc(scene.aside)}</p></aside>`:''}</section><section class="choice-area" aria-label="劇情選項">${state.ai?.mode==='ai'&&scene.choices.length!==3?'<p>這是舊版對話存檔，進度已保留。</p><button class="primary" data-action="ai-generate">接續劇情並生成三選項 →</button>':''}<div class="choice-heading"><span>${'此刻，你決定——'}</span><small>${state.ai?.mode==='ai'?'點選 ①②③ 繼續故事':'選擇會留下記憶'}</small></div>${scene.choices.map((c,i)=>`<button class="choice" data-action="choose" data-id="${esc(c.id)}"><span class="choice-number">${['①','②','③'][i]}</span><span><strong>${esc(c.label)}</strong><small>${esc(c.hint || '繼續故事')}</small></span><span class="choice-arrow">↗</span></button>`).join('')}${state.ai?.mode==='ai'?`<details class="custom-action"><summary>✎ 自訂行動</summary>${dialogueComposer()}</details>`:`<details class="custom-action"><summary>✏️ 自訂行動 <small>想試試另一種可能？</small></summary><form id="custom-form"><label for="custom-input">你打算怎麼做？</label><textarea id="custom-input" name="action" maxlength="160" required placeholder="例如：先問她喜歡什麼，再準備禮物"></textarea><small>本地規則會提供三種回應。</small><button class="secondary" type="submit">提出行動 →</button></form></details>`}<p class="save-hint">◇ 成功回應後自動保存 · ${state.memory.long.length} 段重要記憶</p></section>`;
}
export function castPage(state,world) {
  return heading('CHARACTERS / 旅途中的人','相遇，都有回音。','有些人還在遠方，有些人已把你放進記憶。')+`<div class="cast-list">${Object.keys(state.characters).map((id,i)=>{const c=getCharacter(state,id),s=state.characters[id],met=state.flags[`met:${id}`],persona=c.personas.find(p=>p.worldId===world.id);return `<button class="cast-card ${met?'':'unmet'}" data-action="character" data-id="${id}"><div class="portrait portrait-${i%3}"><span>${esc(c.name.slice(-2))}</span><small>${met?'已相遇':'未相遇'}</small></div><div class="cast-info"><div class="cast-title"><h2>${esc(c.name)}</h2><span>${esc(s.relationship)}</span></div><p>${c.age} 歲 · ${esc(persona?.identity)}</p><small>${esc(c.corePersonality)}</small><div class="mini-metrics"><span>好感 <b>${s.affection}</b></span><span>信任 <b>${s.trust}</b></span><span>親密 <b>${s.intimacy}</b></span></div></div><span class="card-arrow">↗</span></button>`;}).join('')}</div>`;
}
export function characterPage(state,world,id) {
  const c=getCharacter(state,id),s=state.characters[id],p=c.personas.find(p=>p.worldId===world.id),met=state.flags[`met:${id}`];
  const row=(label,value)=>`<div class="profile-row"><dt>${label}</dt><dd>${esc(value)}</dd></div>`;
  return `${button('cast','← 所有角色','text-button')}<div class="character-heading"><div class="portrait large"><span>${esc(c.name.slice(-2))}</span></div><div><span class="eyebrow">CHARACTER / 成年角色</span><h1>${esc(c.name)}</h1><p>${c.age} 歲 · ${esc(p?.identity)}</p><span class="tag">${esc(s.relationship)} · ${esc(s.mood)}</span></div></div><section class="panel metrics">${metric('好感',s.affection,'affection')}${metric('信任',s.trust,'trust')}${metric('親密',s.intimacy,'intimacy')}</section><section class="panel"><h2>此刻的模樣 / 角色狀態</h2><dl>${row('外貌',c.appearance)}${row('服裝',p?.clothing)}${row('狀態',s.status)}${row('身份背景',p?.background)}${row('能力',p?.abilities)}</dl></section><section class="panel"><h2>不只是姓名</h2><dl>${row('核心性格',c.corePersonality)}${row('說話方式',c.speechStyle)}${row('行為模式',c.behavior || '等待更多相處來了解。')}${row('關係風格',c.relationshipStyle)}${row('親密風格',c.intimacyStyle)}${row('喜歡',s.trust>=15?c.likes:'尚未了解 · 信任 15 後解鎖')}${row('不喜歡',c.dislikes)}${row('界線',c.boundaries)}${row('弱點',s.trust>=25 || s.unlocked.includes('weakness') ? c.weakness : '尚未解鎖 · 信任達到 25 後揭露')}${row('秘密',s.trust>=50 || s.unlocked.includes('secret') ? c.secret : '尚未解鎖 · 信任達到 50 後揭露')}</dl></section><section class="panel"><h2>共同記憶 <small>${s.memories.length} 段</small></h2>${s.memories.length?`<ol class="timeline">${s.memories.slice().reverse().map(m=>`<li><small>第 ${m.turn} 次選擇</small><p>${esc(m.text)}</p></li>`).join('')}</ol>`:`<p class="muted">${met?'故事才剛開始。':'你們還未相遇。公開資料以外的故事，留待日後發現。'}</p>`}</section><details class="panel"><summary>親密事件紀錄 · ${s.intimacyHistory.length}</summary>${s.intimacyHistory.map(m=>`<p>${esc(m.text)}</p>`).join('') || '<p class="muted">尚無紀錄。每一次靠近都需要自願。</p>'}</details><section class="panel"><h2>相處的溫度 <span class="tag">對話 Lv.${s.intimacyDialogueLevel || 0}</span></h2><p>${esc((intimacyDialogue[id]||intimacyDialogue.default)[s.intimacyDialogueLevel||0])}</p><p class="muted fine">共同成長：${s.progress || 0} 點</p><div class="button-grid"><button class="secondary" data-action="social" data-id="${id}" ${met?'':'disabled'}>與對方相處</button><button class="secondary" data-action="private" data-id="${id}" ${met?'':'disabled'}>私人邀約</button></div></section>${state.flags['eye:'+id]?`<section class="panel"><h2>仙緣之眼 · 已解鎖資訊</h2><p class="scan-result">${esc(inspectTarget(state,world,id))}</p></section>`:''}${id.startsWith('custom-')?'<p class="muted">自創角色已加入世界，可以相處或發出邀約，也可加入其他新世界。</p>':''}`;
}
export function worldPage(state,world) { return heading('WORLDS / 無數人生，一座入口','你的下一個世界。')+`<section class="world-cover active-world"><span class="tag">目前世界 · ${world.theme}</span><h2>${world.name}</h2><p>${world.description}</p><div class="world-stats">${Object.entries(world.stats).map(([key,d])=>`<div><small>${d.name}</small><strong>${esc(statLabel(d,state.stats[key]))}</strong></div>`).join('')}</div></section><section class="panel"><h2>世界法則</h2><ul class="rules">${world.rules.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><p class="muted">特殊能力：${esc(world.playerRole.abilities.join('、'))}</p></section><section class="panel"><h2>旅途摘要</h2><p>${esc(state.memory.worldSummary)}</p><span class="tag">${state.flags.chapterComplete?'卷一完成 · 宗主召見待續':'卷一進行中'}</span></section>${button('new-world','＋ 建立新世界','new-world')}<p class="save-hint">${worlds.size} 個可玩世界 · 更多人生，留給下一場夢</p>`; }
export function forgePage(state) { const fields=[['name','姓名','text',true],['age','成年年齡','number',true],['appearance','外貌','text'],['identity','目前身份','text'],['corePersonality','性格','text'],['speechStyle','說話方式','text'],['background','世界背景','text'],['abilities','能力','text'],['likes','喜好','text'],['relationshipStyle','關係風格','text'],['intimacyStyle','親密風格','text']];return heading('CREATION / 造物臺','讓想像，有個名字。','建立自己的成年角色，讓他們在這個世界留下位置。')+`<section class="panel"><span class="tag">V0.2.2 · 成年角色建立</span><p class="muted">新角色會加入目前世界的角色名冊並隨存檔保存。AI 模式會依新角色的性格與身份續寫；離線模式提供相處與邀約事件。</p><form id="forge-form" class="forge-form">${fields.map(([key,label,type,required])=>`<label>${label}<input name="${key}" type="${type}" ${required?'required':''} ${type==='number'?'min="18" max="9999" step="1" value="24"':`maxlength="${key==='name'?30:400}"`} placeholder="${key==='name'?'例如：江聽雨':'由你定義'}"></label>`).join('')}<label class="check"><input type="checkbox" name="adult" required> 我確認角色已成年，互動尊重雙方意願與界線。</label><button class="primary" type="submit">創造角色，加入世界 →</button><p class="save-hint">${state.customCharacters.length} / 20 位自創角色</p></form></section>`; }
export function settingsPage(state,storageError,worldCount=1) { return heading('ARCHIVE / 夢境存檔','把故事，好好留下。')+`<section class="panel"><h2>全部旅程 <span class="tag">${worldCount} 個世界</span></h2><p>${esc(state.player.name)} · 已做出 ${state.turn} 次選擇</p><p class="muted">${storageError?'儲存暫不可用，請匯出備份。':state.savedAt?`上次保存：${esc(new Date(state.savedAt).toLocaleString('zh-TW'))}`:'尚未保存'}</p><div class="button-grid">${button('save','手動存檔')}${button('export','匯出 JSON')}<label class="secondary file-button">匯入 JSON<input type="file" id="import-file" accept="application/json,.json"></label>${button('reset','重置目前世界','danger')}</div><p class="muted fine">進度只存在這個瀏覽器。清除網站資料會失去存檔，建議定期匯出。</p></section><section class="panel"><h2>閱讀設定</h2><label class="check"><input type="checkbox" id="large-text"> 加大劇情字體</label></section><section class="panel"><h2>關於這場夢</h2><p class="muted">夢境世界 V0.2.2<br>支援 AI 即時劇情與離線模式。AI 需自行設定 Provider；圖片與影片事件保留既有 Media Engine。</p><p class="muted fine">獨立世界、角色核心、身份模組與記憶系統。每一段故事，都可以是下一個世界的起點。</p></section>`; }
export function navigation(active) { const items=[['story','◈','劇情'],['cast','♧','角色'],['world','◎','世界'],['forge','✧','造物臺'],['settings','▤','設定']];return items.map(([id,icon,label])=>`<button data-action="tab" data-id="${id}" ${active===id?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${label}</button>`).join(''); }

export function statusBar(state,world) { const g=state.gimmick; return baseStatusBar(state,world)+`<div class="gimmick-strip"><button class="secondary" data-action="gimmick">✨ 外掛</button><span>${esc(g.name)} <b>Lv.${g.level}</b><small>EXP ${g.exp} · ${esc(g.resourceName)} ${g.specialResources.energy}</small></span></div>`; }

export function dialogueComposer() {
  return `<form id="custom-form" class="dialogue-composer"><label for="custom-input">你想說什麼，或做什麼？</label><textarea id="custom-input" name="action" maxlength="300" rows="3" required placeholder="例如：清霜，剛才那件事讓你不開心嗎？"></textarea><small>想試另一種可能時，描述行動或對話；最多 300 字。</small><button class="primary" type="submit">送出對話／行動 →</button></form>`;
}
