import { esc } from './ui.js';
import { worldPresets } from '../data/worlds/presets.js';
import { gimmickTemplates } from '../data/gimmicks/templates.js';
import { characters } from '../data/characters/cast.js';
import { worldFor, characterLibrary } from './archive-engine.js';
import { getCharacter } from './character-engine.js';
import { abilityStatus, nextLevelExp } from './gimmick-engine.js';
export function worldsPage(archive) {
  return `<div class="page-heading"><span class="eyebrow">WORLDS / 彼此獨立的旅程</span><h1>這一場夢，由你定義。</h1><p>切換世界會保存原本的旅程。每個世界都有自己的關係、記憶與外掛。</p></div><button class="primary enter" data-action="new-world">＋ 建立新世界 <span>${archive.worlds.length} / 12</span></button>${archive.worlds.map(s=>{const w=worldFor(s);return `<section class="world-cover managed-world"><span class="tag">${esc(w.theme)} · ${s.worldId===archive.activeWorldId?'目前世界':'已保存'}</span><h2>${esc(w.name)}</h2><p>${esc(w.description)}</p><p>第 ${s.turn+1} 幕 · ${esc(s.player.name)} · ${esc(s.player.identity)}</p><p class="gimmick-name">✨ ${esc(s.gimmick.name)} Lv.${s.gimmick.level}</p><div class="button-grid"><button class="secondary" data-action="switch-world" data-id="${s.worldId}">${s.worldId===archive.activeWorldId?'繼續世界':'切換世界'}</button><button class="danger" data-action="delete-world" data-id="${s.worldId}" ${archive.worlds.length===1?'disabled':''}>刪除世界</button></div></section>`;}).join('')}<p class="save-hint">世界進度分開保存 · 匯出時包含全部世界</p>`;
}
const field=(name,label,value,area=false,required=true)=>`<label>${label}${area?`<textarea name="${name}" maxlength="1500" ${required?'required':''}>${esc(value)}</textarea>`:`<input name="${name}" maxlength="100" value="${esc(value)}" ${required?'required':''}>`}</label>`;
export function wizardPage(d,step,archive) {
  const titles=['選擇世界類型','寫下世界的規則','✨ 主角特殊外掛','誰會與你同行？','準備好，踏入新世界'];
  let content='';
  if(step===1)content=`<div class="type-grid">${Object.entries(worldPresets).map(([id,p])=>`<label class="type-option"><input type="radio" name="worldType" value="${id}" ${d.worldType===id?'checked':''} required><strong>${p.name}</strong><small>${p.title}</small></label>`).join('')}</div>`;
  if(step===2)content=field('name','世界名稱',d.name)+field('description','世界簡介',d.description,true)+field('playerIdentity','玩家身份',d.playerIdentity)+field('rules','世界規則',d.rules,true)+field('statsText','世界專屬數值',d.statsText,true)+`<p class="muted fine">每行「名稱|初始值」，2–8 項。第一項代表成長，第二項代表可投入與返還的資源。例：血脈|0、資源|10（分行填寫）。</p>`+field('background','世界特殊背景',d.background,true);
  if(step===3)content=`<label>設定方式<select name="gimmickMode" id="gimmick-mode">${[['recommended','使用世界推薦外掛'],['template','從已有模板選擇'],['custom','自訂外掛']].map(([v,l])=>`<option value="${v}" ${d.gimmickMode===v?'selected':''}>${l}</option>`).join('')}</select></label><p class="muted">這個世界推薦：${gimmickTemplates[worldPresets[d.worldType].gimmick].name}</p><label>模板／自訂外掛的可執行機制<select name="template">${Object.entries(gimmickTemplates).map(([id,g])=>`<option value="${id}" ${d.template===id?'selected':''}>${g.name}</option>`).join('')}</select></label><p class="muted fine">模板可跨世界搭配。自訂名稱與設定會保存；本版以選定機制執行能力，不會把自由描述直接當成程式。</p><fieldset id="custom-gimmick-fields" ${d.gimmickMode==='custom'?'':'hidden'}><legend>自訂外掛設定</legend>${[['name','外掛名稱'],['description','外掛描述'],['coreAbility','核心能力'],['growth','成長方式'],['resourceName','特殊資源'],['trigger','觸發條件']].map(([key,label])=>field(`gimmick_${key}`,label,d[`gimmick_${key}`]||'',key==='description',false)).join('')}</fieldset>`;
  if(step===4)content=`<p class="muted">可加入既有成年角色，或完全不勾選。不同世界的人格一致，但身份與關係重新開始。</p><div class="character-options">${[...Object.values(characters),...characterLibrary(archive)].map(c=>`<label class="check character-option"><input type="checkbox" name="characters" value="${c.id}" ${(d.characters||[]).includes(c.id)?'checked':''}><span><strong>${esc(c.name)}</strong> · ${c.age} 歲<br><small>${esc(c.corePersonality)}</small></span></label>`).join('')}</div>`;
  if(step===5){const template=d.gimmickMode==='recommended'?worldPresets[d.worldType].gimmick:d.template;content=`<section class="world-cover"><span class="tag">${worldPresets[d.worldType].name}</span><h2>${esc(d.name)}</h2><p>${esc(d.description)}</p><p>身份：${esc(d.playerIdentity)}</p><p>✨ ${esc(d.gimmickMode==='custom'?d.gimmick_name:gimmickTemplates[template].name)}</p><p>${d.characters.length} 位成年同行者 · 全新獨立進度</p></section><p class="muted">建立後會直接進入第一幕，並提供三個可玩的選項。現有世界保留。</p>`;}
  return `<div class="page-heading"><span class="eyebrow">CREATE WORLD / ${step} OF 5</span><h1>${titles[step-1]}</h1><div class="step-track" aria-label="第 ${step} 步，共 5 步">${titles.map((_,i)=>`<span class="${i<step?'done':''}"></span>`).join('')}</div></div><form id="world-form" class="world-form">${content}<div class="button-grid">${step>1?'<button type="button" class="secondary" data-action="wizard-back">上一步</button>':'<button type="button" class="secondary" data-action="wizard-cancel">取消</button>'}<button class="primary" type="submit">${step===5?'建立並進入世界 →':'下一步 →'}</button></div></form>`;
}
export function gimmickPanel(state,world) {
  const g=state.gimmick,next=nextLevelExp(g),targets=Object.keys(state.characters).filter(id=>state.flags[`met:${id}`]);
  return `<span class="eyebrow">PLAYER GIMMICK / 不同的可能</span><h2>✨ ${esc(g.name)}</h2><p class="tag">Lv.${g.level} · EXP ${g.exp}${next?` / ${next}`:' · 已達最高等級'}</p><p>${esc(g.description)}</p><p class="muted fine">核心能力：${esc(g.coreAbility)}<br>觸發條件：${esc(g.trigger)}</p><div class="resource-grid"><span>${esc(g.resourceName)}<strong>${g.specialResources.energy}/100</strong></span><span>體力<strong>${g.specialResources.stamina}/100</strong></span>${g.templateId==='taixu'?`<span>仙元儲存<strong>${g.specialResources.yuan}</strong></span>`:''}</div><p class="muted fine">${esc(g.growth)} 日常行動恢復能量與體力；能力消耗與冷卻以卡片為準。</p><label>能力目標<select id="gimmick-target"><option value="">觀察世界／尚未指定</option>${targets.map(id=>`<option value="${id}">${esc(getCharacter(state,id).name)}</option>`).join('')}</select></label><div class="ability-list">${g.abilities.map(a=>{const reason=abilityStatus(state,a);return `<article class="ability-card"><strong>${esc(a.name)}</strong><small>Lv.${a.level} · 消耗 ${a.cost} · 冷卻 ${a.cooldown} 回合</small><button class="secondary" data-action="prepare-ability" data-id="${a.id}" ${reason?'disabled':''}>${esc(reason || '準備使用 →')}</button></article>`;}).join('')}</div><section class="system-note"><span>特殊任務 · ${g.quest.completed?'已完成':'進行中'}</span><p>${esc(g.quest.description)}</p><p>${esc(g.quest.reward)}</p></section><p class="muted fine">世界成果：據點 ${state.worldState.shelter||0} · 人口 ${state.worldState.population||0} · 領地 ${state.worldState.territory||0} · 情報 ${state.worldState.intelligence||0}</p>`;
}
