import{PET_CLASS_LIMIT,petExpNeed,totalControlUsed,remainingControl}from'./balance.js?v=27';import{PET_TYPES,SUMMON_TYPES,PET_EVOLUTIONS,controlCapacity}from'./systems.js?v=27';import{derived}from'./player.js?v=27';import{PET_STONES,BOSS_PET_FORMS}from'./content-v13.js?v=27';
export function companionHits(p){let hits=p.pets.filter(x=>p.activePets.includes(x.uid)&&x.alive).map(pet=>{let pd=PET_TYPES.find(x=>x.id===pet.type),boss=BOSS_PET_FORMS.find(x=>x.id===pet.bossForm),mult=(pet.evolutionMultiplier||1)*(boss?.attack||1)*(boss?.speed||1);return{name:pet.name,damage:Math.floor((pd?.atk||0)*mult*(1+pet.level/20))}}),sum=p.summons[0],sd=sum?SUMMON_TYPES.find(x=>x.id===sum.type):null;if(sd)hits.push({name:sd.name,damage:sd.atk});return hits}export function companionAttack(p){return companionHits(p).reduce((n,x)=>n+x.damage,0)}
export const petControl=pet=>((pet.evolution||0)>0?PET_EVOLUTIONS[pet.type]?.[(pet.evolution||0)-1]?.control:0)||PET_TYPES.find(t=>t.id===pet.type)?.control||0;
export function togglePet(p,uid){let pet=p.pets.find(x=>x.uid===uid);if(!pet||!pet.alive)return false;let i=p.activePets.indexOf(uid);if(i>=0){p.activePets.splice(i,1);return true}if(p.activePets.length>=PET_CLASS_LIMIT[p.cls])return false;p.activePets.push(uid);return true}
export function evolvePet(p,uid){let pet=p.pets.find(x=>x.uid===uid),stage=pet?.evolution||0,old=PET_EVOLUTIONS[pet?.type]?.[stage],material=stage===0?PET_STONES.normal:stage===1?PET_STONES.advanced:null,count=stage===0?5:stage===1?3:0,level=old?.level||(stage===0?15:35);if(!pet||stage>1||pet.level<level||(p.petMaterials?.[material]||0)<count)return false;p.petMaterials[material]-=count;pet.evolution=stage+1;pet.name=stage===0?`進化${PET_TYPES.find(x=>x.id===pet.type)?.name||'寵物'}`:`高階${PET_TYPES.find(x=>x.id===pet.type)?.name||'寵物'}`;pet.evolutionMultiplier=stage===0?1.28:1.6;pet.hp=Math.floor(pet.hp*(stage===0?1.2:1.25));return true}
export function evolvePetBoss(p,uid,formId){let pet=p.pets.find(x=>x.uid===uid),form=BOSS_PET_FORMS.find(x=>x.id===formId);if(!pet||pet.evolution<2||pet.bossForm||!form||(p.bossMaterials[form.material]||0)<1)return false;p.bossMaterials[form.material]--;pet.bossForm=form.id;pet.evolution=3;pet.name=form.name;pet.evolutionMultiplier=form.mult;return true}
export function summonStatus(p,id){let t=SUMMON_TYPES.find(x=>x.id===id),cha=derived(p).stats.cha,ring=Object.values(p.equipment).some(x=>x?.id==='summon-ring'||x?.summonControl),reasons=[];if(!t)return null;if(p.level<t.level)reasons.push(`等級不足 ${p.level}/${t.level}`);if(cha<t.requiredCha)reasons.push(`魅力不足 ${cha}/${t.requiredCha}`);if(!p.learnedSkills.includes(t.skill))reasons.push(`需要技能：${t.skill}`);if(t.ring&&!ring)reasons.push('需要召喚控制戒指');if(remainingControl({...p,stats:{...p.stats,cha}})<t.control)reasons.push('召喚控制力不足');return{summon:t,currentCha:cha,hasRing:ring,ok:reasons.length===0,reasons}}
export function summon(p,id){let status=summonStatus(p,id),t=status?.summon;if(!status?.ok||p.cls!=='法師')return false;p.summons=[{type:id,hp:t.hp}];return true}
export function petWin(p,battleExp=10){let pets=p.pets.filter(x=>p.activePets.includes(x.uid)&&x.alive),share=pets.length?Math.max(1,Math.floor(battleExp/pets.length)):0;for(let pet of pets){pet.exp+=share;while(pet.exp>=petExpNeed(pet.level)){pet.exp-=petExpNeed(pet.level);pet.level++;pet.hp+=8}}}
export function companionDeath(p){for(let pet of p.pets||[])if((p.activePets||[]).includes(pet.uid)){pet.alive=false;pet.hp=0}p.activePets=[];p.summons=[]}





