import{PET_CLASS_LIMIT,petExpNeed}from'./balance.js?v=57';import{PET_TYPES,SUMMON_TYPES,PET_EVOLUTIONS,controlCapacity}from'./systems.js?v=60';import{derived}from'./player.js?v=38';import{BOSS_PET_FORMS,CHARM_SET}from'./content-v13.js?v=60';import{BALANCE_CONFIG,petExpReward}from'./balance-config.js?v=54';import{combatAdvancement}from'./rebirth.js?v=54';
export function companionHits(p){let hits=p.pets.filter(x=>p.activePets.includes(x.uid)&&x.alive).map(pet=>{let pd=PET_TYPES.find(x=>x.id===pet.type),boss=BOSS_PET_FORMS.find(x=>x.id===pet.bossForm),mult=(pet.evolutionMultiplier||1)*(boss?.attack||1)*(boss?.speed||1);return{name:pet.name,damage:Math.max(1,Math.floor((pd?.atk||0)*mult*(1+pet.level/20)*BALANCE_CONFIG.petDamageRate))}}),sum=p.summons[0],sd=sum?SUMMON_TYPES.find(x=>x.id===sum.type):null;if(sd){let pieces=Object.values(p.equipment).filter(i=>i&&CHARM_SET.pieceIds.includes(i.id)).length,mult=(pieces>=4?1+(CHARM_SET.effects[4].summonDamage||0):1)*combatAdvancement(p).summon;hits.push({name:sd.name,damage:Math.floor(sd.atk*mult)})}return hits}export function companionAttack(p){return companionHits(p).reduce((n,x)=>n+x.damage,0)}
export const petControl=pet=>((pet.evolution||0)>0?PET_EVOLUTIONS[pet.type]?.[(pet.evolution||0)-1]?.control:0)||PET_TYPES.find(t=>t.id===pet.type)?.control||0;
export function petMaxHp(pet){let base=PET_TYPES.find(x=>x.id===pet.type),stage=Math.min(2,pet.evolution||0),stageHp=(stage>=1?1.2:1)*(stage>=2?1.25:1),boss=BOSS_PET_FORMS.find(x=>x.id===pet.bossForm);return Math.max(1,Math.floor(((base?.hp||pet.hp||1)+Math.max(0,(pet.level||1)-1)*8)*stageHp*(boss?.hp||1)))}
export function recoverPet(pet){if(!pet)return false;pet.alive=true;pet.hp=petMaxHp(pet);return true}
export function togglePet(p,uid){let pet=p.pets.find(x=>x.uid===uid);if(!pet)return false;let i=p.activePets.indexOf(uid);if(i>=0){p.activePets.splice(i,1);return true}if(!pet.alive)recoverPet(pet);if(p.activePets.length>=PET_CLASS_LIMIT[p.cls])return false;p.activePets.push(uid);return true}
export function petEvolutionStatus(p,uid){let pet=p.pets.find(x=>x.uid===uid),stage=pet?.evolution||0,rule=PET_EVOLUTIONS[pet?.type]?.[stage];if(!pet)return{ok:false,reason:'找不到寵物。'};if(stage>1||!rule)return{ok:false,reason:'一般進化階段已完成。'};if(pet.level<rule.level)return{ok:false,reason:`寵物等級不足，需要 Lv.${rule.level}。`};if((p.petMaterials?.[rule.material]||0)<rule.count)return{ok:false,reason:`${rule.material}不足，需要 ×${rule.count}。`};return{ok:true,pet,stage,rule}}
export function evolvePet(p,uid){let status=petEvolutionStatus(p,uid);if(!status.ok)return false;let{pet,stage,rule}=status,level=pet.level,exp=pet.exp;p.petMaterials[rule.material]-=rule.count;pet.evolution=stage+1;pet.name=rule.name;pet.evolutionMultiplier=rule.mult;pet.hp=petMaxHp(pet);pet.level=level;pet.exp=exp;return true}
export function evolvePetBoss(p,uid,formId){let pet=p.pets.find(x=>x.uid===uid),form=BOSS_PET_FORMS.find(x=>x.id===formId);if(!pet||pet.evolution<2||pet.bossForm||!form||(p.bossMaterials[form.material]||0)<1)return false;p.bossMaterials[form.material]--;pet.bossForm=form.id;pet.evolution=3;pet.name=form.name;pet.evolutionMultiplier=form.mult;pet.hp=petMaxHp(pet);return true}
export function summonStatus(p,id){let t=SUMMON_TYPES.find(x=>x.id===id),cha=derived(p).stats.cha,ring=Object.values(p.equipment).some(x=>x?.id==='summon-ring'||x?.summonControl),reasons=[];if(!t)return null;if(p.level<t.level)reasons.push(`等級不足 ${p.level}/${t.level}`);if(cha<t.requiredCha)reasons.push(`魅力不足 ${cha}/${t.requiredCha}`);if(!p.learnedSkills.includes(t.skill))reasons.push(`需要技能：${t.skill}`);if(controlCapacity(cha)<t.control)reasons.push('召喚控制力不足');let eligible=SUMMON_TYPES.filter(x=>x.skill===t.skill&&p.level>=x.level&&cha>=x.requiredCha&&controlCapacity(cha)>=x.control),defaultSummon=eligible.at(-1);if(!ring&&defaultSummon&&t.id!==defaultSummon.id)reasons.push(`未裝備召喚控制戒指時自動召喚：${defaultSummon.name}`);return{summon:t,currentCha:cha,hasRing:ring,ringEffect:'可從符合條件的召喚獸中指定種類',ok:reasons.length===0,reasons}}
export function summon(p,id){let status=summonStatus(p,id),t=status?.summon;if(!status?.ok||p.cls!=='法師')return false;p.summons=[{type:id,hp:Math.floor(t.hp*combatAdvancement(p).summon)}];return true}
export function petWin(p,battleExp=10){let pets=p.pets.filter(x=>p.activePets.includes(x.uid)&&x.alive),share=pets.length?Math.max(1,Math.floor(petExpReward(battleExp)/pets.length)):0;for(let pet of pets){pet.exp+=share;while(pet.exp>=petExpNeed(pet.level)){pet.exp-=petExpNeed(pet.level);pet.level++;pet.hp+=8}}}
export function companionDeath(p){p.activePets=[];for(let pet of p.pets||[])recoverPet(pet);p.summons=[]}
