import{BOSS_CATALOG,BOSS_SETS}from'./systems.js?v=60';
const ALL_CLASSES=['王族','騎士','妖精','法師','黑暗妖精','龍騎士','幻術士'];
const armor=(id,name,slot,ac,tier,extra={})=>({id,name,slot,ac,safe:4,weight:8,price:25000*tier,rarity:tier>=5?'稀有':tier>=3?'進階':'普通',tier,classes:ALL_CLASSES,officialConfirmed:true,...extra});
export const OFFICIAL_PROGRESSION_GEAR=[armor('official-bracer','腕甲','手套',-1,1),armor('official-iron-gloves','鋼鐵手套','手套',-2,2),armor('official-power-gloves','力量手套','手套',-2,3,{statBonuses:{str:1}}),armor('official-taras-gloves','塔拉斯手套','手套',-3,5,{statBonuses:{str:2},mpRegen:1}),armor('official-shirt','T恤','內衣',-1,1),armor('official-elf-shirt','精靈T恤','內衣',-1,2,{classes:['妖精']}),armor('official-power-shirt','力量T恤','內衣',-1,3,{statBonuses:{str:1},hit:1}),armor('official-dex-shirt','敏捷T恤','內衣',-1,4,{statBonuses:{dex:1},hit:1}),armor('official-int-shirt','智力T恤','內衣',-1,5,{statBonuses:{int:1},magic:1})];
export const VERIFIED_BOSS_SET_IDS=new Set(['set0']);
const HIGH_MAP_BOSS_POOLS={8:[0,1],9:[0,1,6],10:[0,1,6,7],11:[0,1,6,7,10],12:[0,1,6,7,10,14],13:[0,1,6,7,10,14,15],14:[0,1,6,7,10,14,15],15:[0,1,6,7,10,14,15]};
export function highMapBossLoot(player,map,rng=Math.random){if(map.dragon||map.tier<8)return null;let indexes=HIGH_MAP_BOSS_POOLS[Math.min(15,map.tier)]||HIGH_MAP_BOSS_POOLS[15],bosses=indexes.map(i=>BOSS_CATALOG[i]).filter(Boolean),roll=rng();if(roll<.0012){let usable=bosses.map(x=>x.item).filter(x=>!x.classes||x.classes.includes(player.cls));return usable.length?usable[Math.floor(rng()*usable.length)]:null}if(roll<.002){let pieces=BOSS_SETS.filter(x=>VERIFIED_BOSS_SET_IDS.has(x.id)&&bosses.some(b=>b.name===x.boss)).flatMap(x=>x.pieces);return pieces.length?pieces[Math.floor(rng()*pieces.length)]:null}if(roll<.003){let materials=bosses.map(x=>x.material);return{kind:'boss-material',name:materials[Math.floor(rng()*materials.length)]}}return null}
export const WEAPON_MAGIC={'boss-item-1':{name:'地裂術',proc:.06,power:1.15},'boss-item-6':{name:'魔力奪取',proc:.05,power:.8},'boss-item-7':{name:'冰錐',proc:.06,power:1.1},'boss-item-10':{name:'烈炎術',proc:.05,power:1.3}};
export function weaponMagicProc(player,enemy,rng=Math.random){let weapon=player.equipment?.武器,magic=WEAPON_MAGIC[weapon?.id];if(!magic||rng()>=magic.proc)return null;let damage=Math.max(1,Math.floor(((weapon.small+weapon.large)/2+(player.stats?.int||0))*magic.power));return{...magic,damage}}
export const EQUIPMENT_AUDIT={OFFICIAL_CONFIRMED:[...OFFICIAL_PROGRESSION_GEAR.map(x=>x.name),'死亡騎士頭盔','死亡騎士盔甲','死亡騎士手套','死亡騎士鞋子','巴風特魔杖','冰之女王魔杖','死亡騎士烈炎劍','古代之劍','古代巨劍','巨蟻女皇的銀翅膀'],CUSTOM_CONFIRMED:BOSS_SETS.filter(x=>!VERIFIED_BOSS_SET_IDS.has(x.id)).flatMap(x=>x.pieces.map(p=>p.name)),NEEDS_VERIFICATION:['身體腰帶','賢者戒指']};
