import{CLASSES}from'./data.js?v=27';
let instanceSequence=0;export const itemInstanceId=()=>`item-${Date.now().toString(36)}-${(++instanceSequence).toString(36)}-${Math.random().toString(36).slice(2,9)}`;
export function ensureItemInstances(p){let used=new Set;for(let item of[...(p.bag||[]),...Object.values(p.equipment||{}).filter(Boolean)]){let id=item.instanceId||item.uid;if(!id||used.has(id))id=itemInstanceId();item.instanceId=item.uid=id;used.add(id)}return used.size}
export function canEquip(p,item){if(item.slot==='武器'&&item.classes&&!item.classes.includes(p.cls))return false;if(item.slot==='武器'&&!CLASSES[p.cls].weapon.includes(item.type))return false;if(item.slot==='盾牌'){let w=p.equipment.武器;if(w&&(w.two||w.type==='弓'||['雙刀','鋼爪'].includes(w.type)))return false}return true}
export function equip(p,id){let i=p.bag.find(x=>x.uid===id);if(!i||!canEquip(p,i))return false;if(i.slot==='武器'&&(i.two||i.type==='弓'||['雙刀','鋼爪'].includes(i.type))&&p.equipment.盾牌)p.bag.push(p.equipment.盾牌),delete p.equipment.盾牌;let old=p.equipment[i.slot];p.bag=p.bag.filter(x=>x.uid!==id);if(old)p.bag.push(old);p.equipment[i.slot]=i;return true}
export function addItem(p,item){let instanceId=itemInstanceId();p.bag.push({...item,uid:instanceId,instanceId,enhance:item.enhance||0,protected:!!item.protected||!!item.boss||!!item.world||!!item.special});return instanceId}
export function unequip(p,slot){let item=p.equipment[slot];if(!item)return false;delete p.equipment[slot];p.bag.push(item);return true}
export function sell(p,id){let i=p.bag.find(x=>x.uid===id);if(!i||i.protected||i.enhance>0)return false;p.gold+=Math.floor((i.price||100)/3);p.bag=p.bag.filter(x=>x.uid!==id);return true}
export function autoSell(p){let list=p.bag.filter(i=>i.kind!=='book'&&!i.protected&&!i.enhance),gold=list.reduce((n,i)=>n+Math.floor((i.price||100)/3),0);p.gold+=gold;p.bag=p.bag.filter(i=>i.kind==='book'||i.protected||i.enhance);return gold}
