import{CLASSES}from'./data.js?v=38';
let instanceSequence=0;export const itemInstanceId=()=>`item-${Date.now().toString(36)}-${(++instanceSequence).toString(36)}-${Math.random().toString(36).slice(2,9)}`;
export function ensureItemInstances(p){let used=new Set;for(let item of[...(p.bag||[]),...Object.values(p.equipment||{}).filter(Boolean)]){let id=item.instanceId||item.uid;if(!id||used.has(id))id=itemInstanceId();item.instanceId=item.uid=id;used.add(id)}return used.size}
export function canEquip(p,item){if(item.slot==='武器'&&item.classes&&!item.classes.includes(p.cls))return false;if(item.slot==='武器'&&!CLASSES[p.cls].weapon.includes(item.type))return false;if(item.slot==='盾牌'){let w=p.equipment.武器;if(w&&(w.two||w.type==='弓'||['雙刀','鋼爪'].includes(w.type)))return false}return true}
export const EQUIPMENT_SLOTS=new Set(['武器','頭盔','盔甲','內衣','斗篷','手套','盾牌','鞋子','項鍊','戒指1','戒指2']);
export function countInstanceId(p,id){return(p.bag||[]).filter(x=>(x.instanceId||x.uid)===id).length+Object.values(p.equipment||{}).filter(x=>(x?.instanceId||x?.uid)===id).length}
const transactionState=(p,item)=>({item:item?{name:item.name,instanceId:item.instanceId||item.uid,slot:item.slot}:null,inventoryLength:p.bag.length,equipmentSlotContent:item?.slot&&p.equipment[item.slot]?{name:p.equipment[item.slot].name,instanceId:p.equipment[item.slot].instanceId||p.equipment[item.slot].uid,slot:p.equipment[item.slot].slot}:null,count:item?countInstanceId(p,item.instanceId||item.uid):0});
export function equip(p,id,trace=()=>{}){let item=p.bag.find(x=>(x.instanceId||x.uid)===id);trace('B_found_item',transactionState(p,item));if(!item||countInstanceId(p,id)!==1||!EQUIPMENT_SLOTS.has(item.slot)||!canEquip(p,item)){trace('validation_failed',transactionState(p,item));return false}let old=p.equipment[item.slot],nextBag=[...p.bag],nextEquipment={...p.equipment};trace('C_before_inventory_remove',transactionState({bag:nextBag,equipment:nextEquipment},item));nextBag=nextBag.filter(x=>(x.instanceId||x.uid)!==id);trace('D_after_inventory_remove',transactionState({bag:nextBag,equipment:nextEquipment},item));trace('E_before_equipment_write',transactionState({bag:nextBag,equipment:nextEquipment},item));if(item.slot==='武器'&&(item.two||item.type==='弓'||['雙刀','鋼爪'].includes(item.type))&&nextEquipment.盾牌){nextBag.push(nextEquipment.盾牌);delete nextEquipment.盾牌}if(old)nextBag.push(old);nextEquipment[item.slot]=item;let candidate={...p,bag:nextBag,equipment:nextEquipment};trace('F_after_equipment_write',transactionState(candidate,item));if(countInstanceId(candidate,id)!==1||nextEquipment[item.slot]!==item||old&&countInstanceId(candidate,old.instanceId||old.uid)!==1){trace('transaction_rejected',transactionState(p,item));return false}p.bag=nextBag;p.equipment=nextEquipment;return true}
export function addItem(p,item){let instanceId=itemInstanceId();p.bag.push({...item,uid:instanceId,instanceId,enhance:item.enhance||0,protected:!!item.protected||!!item.boss||!!item.world||!!item.special});return instanceId}
export function unequip(p,slot){let item=p.equipment[slot];if(!item)return false;delete p.equipment[slot];p.bag.push(item);return true}
export function sell(p,id){let i=p.bag.find(x=>x.uid===id);if(!i||i.protected||i.enhance>0)return false;p.gold+=Math.floor((i.price||100)/3);p.bag=p.bag.filter(x=>x.uid!==id);return true}
export function autoSell(p){let list=p.bag.filter(i=>i.kind!=='book'&&!i.protected&&!i.enhance),gold=list.reduce((n,i)=>n+Math.floor((i.price||100)/3),0);p.gold+=gold;p.bag=p.bag.filter(i=>i.kind==='book'||i.protected||i.enhance);return gold}
const battleSignature=i=>JSON.stringify([i.id,i.name,i.enhance||0,i.rarity||'普通',i.slot,i.type||'',i.ac||0,i.small||0,i.large||0,i.hit||0,i.safe||0,i.bossSet||'',i.boss||false,i.special||false,i.summonControl||false,i.statBonuses||{}]);
export function groupEquipment(items){let groups=new Map;for(const item of items.filter(x=>x.kind!=='book')){let key=battleSignature(item),group=groups.get(key);if(group)group.items.push(item);else groups.set(key,{key,item,items:[item]})}return[...groups.values()].map(g=>({...g,count:g.items.length,unitPrice:Math.floor((g.item.price||100)/3),totalPrice:g.items.reduce((n,x)=>n+Math.floor((x.price||100)/3),0)}))}
export const quickSellEligible=i=>i.kind!=='book'&&(i.rarity||'普通')==='普通'&&!(i.enhance||0)&&!i.protected&&!i.boss&&!i.bossSet&&!i.special&&!i.summonControl&&!Object.values(i.statBonuses||{}).some(Boolean);
export function sellInstances(p,ids,{allowProtected=false}={}){let wanted=new Set(ids),items=p.bag.filter(x=>wanted.has(x.instanceId||x.uid));if(items.length!==wanted.size||items.some(x=>!allowProtected&&(x.protected||x.enhance>0)))return{ok:false,count:0,gold:0};let gold=items.reduce((n,x)=>n+Math.floor((x.price||100)/3),0);p.bag=p.bag.filter(x=>!wanted.has(x.instanceId||x.uid));p.gold+=gold;return{ok:true,count:items.length,gold}}
export function quickSellPreview(p){let items=p.bag.filter(quickSellEligible);return{ids:items.map(x=>x.instanceId||x.uid),count:items.length,gold:items.reduce((n,x)=>n+Math.floor((x.price||100)/3),0)}}
