import{simulateOfflineTransform}from'./transformations.js?v=15';import{arrowEffect,selectedArrow,ARROWS}from'./resources.js?v=15';import{acDamageReduction}from'./balance.js?v=15';import{mapFor,equipmentDrop}from'./hunting.js?v=15';import{skillsFor,addBook,skillTier}from'./skills.js?v=15';import{SKILL_TIER_RATE}from'./loot.js?v=15';import{BOOK_SOURCES,BOSS_CATALOG,MINI_MATERIALS}from'./systems.js?v=15';import{addItem}from'./inventory.js?v=15';import{CONSUMABLES}from'./data.js?v=15';import{derived,gainExp}from'./player.js?v=15';import{companionAttack,petWin}from'./companions.js?v=15';import{weaponDamage,hitChance}from'./combat.js?v=15';
const cap=(n,a,b)=>Math.max(a,Math.min(b,n)),rollCount=(tries,rate,rng=Math.random)=>{let fixed=Math.floor(tries*rate),fraction=tries*rate-fixed;return fixed+(rng()<fraction?1:0)};
export function calculateOffline(s,now=Date.now(),rng=Math.random){let p=s.player,sec=Math.min(86400,Math.max(0,Math.floor((now-(s.lastOnlineTimestamp||now))/1000)));if(sec<60||p.inTown)return null;let m=mapFor(p.map),d=derived(p),sample=m.normals[Math.floor(m.normals.length/2)],enemy={...sample,size:'Small',race:/骷髏|殭屍|食屍鬼|死亡|木乃伊/.test(sample.name)?'不死':'一般'},transformSim=simulateOfflineTransform(p,sec,now),base={...p,transformState:{id:null,until:0}},baseD=derived(base),a=arrowEffect(p,enemy),normalDamage=weaponDamage(p,enemy,()=>.5),hit=hitChance(p.equipment.武器?.type==='弓'?d.ranged:d.melee,enemy.ac,enemy.level),active=skillsFor(p).filter(x=>x[2]==='active'&&p.learnedSkills.includes(x[0])),skillDps=active.reduce((n,x)=>n+normalDamage*(x[4]||1)/(x[5]||6),0),petDps=companionAttack(p),speed=baseD.speed*transformSim.multiplier,rawDps=normalDamage*speed*hit+skillDps+petDps,killSec=Math.max(1.2,enemy.hp/Math.max(1,rawDps)),potential=Math.floor(sec/killSec),arrowName=selectedArrow(p),triple=active.find(x=>x[0]==='三重矢'),arrowDemand=p.equipment.武器?.type==='弓'?Math.ceil(sec*speed)+(triple?Math.floor(sec/(triple[5]||4))*3:0):0,budget=p.gold,purchased={},consumed={},cost=0,stopped=false;
 let obtain=(name,demand,auto)=>{let have=p.consumables[name]||0,buyQty=0;if(demand>have&&auto&&CONSUMABLES[name]){buyQty=Math.min(demand-have,Math.floor(budget/CONSUMABLES[name].price));budget-=buyQty*CONSUMABLES[name].price;cost+=buyQty*CONSUMABLES[name].price;purchased[name]=buyQty}let usable=Math.min(demand,have+buyQty);consumed[name]=usable;return demand?usable/demand:1};
 let uptime=1;if(arrowDemand){if(!arrowName||!ARROWS[arrowName])uptime=0;else{let supplyArrow=p.settings.arrowSupplyMode==='fixed'?p.settings.arrowSupplyType:arrowName,canBuy=p.settings.autoSupply&&p.settings.autoBuyArrows&&supplyArrow===arrowName;uptime=Math.min(uptime,obtain(arrowName,arrowDemand,canBuy))}}
 let heal=p.settings.healPotion||'紅色藥水',damageRate=Math.max(.01,(1+m.tier/2)*.035)*(1-acDamageReduction(d.ac)),healDemand=Math.ceil(potential*damageRate),healRatio=obtain(heal,healDemand,p.settings.autoSupply&&p.settings.autoBuyHeal);uptime=Math.min(uptime,healDemand?healRatio:1);
 let mpDemand=Math.ceil(active.reduce((n,x)=>n+x[3]/(x[5]||6),0)*sec),manaDemand=Math.ceil(Math.max(0,mpDemand-p.mp)/45);if(manaDemand){let ratio=obtain('魔力藥水',manaDemand,p.settings.autoSupply&&p.settings.autoBuyMana);uptime=Math.min(uptime,.8+.2*ratio)}if(p.settings.autoBuyBlue){let blueNeed=Math.ceil(sec/300);obtain('藍色藥水',blueNeed,p.settings.autoSupply&&p.settings.autoBuyBlue)}for(let[name,enabled,buyEnabled]of[['綠色藥水',p.settings.autoGreen,p.settings.autoSupplyGreen],['勇敢藥水',p.settings.autoBrave,p.settings.autoSupplyBrave]])if(enabled){let need=Math.ceil(sec/300),ratio=obtain(name,need,p.settings.autoSupply&&buyEnabled);uptime=Math.min(uptime,.7+.3*ratio)}
 let transformNeed=p.settings.autoTransform?Math.ceil(sec/1800):0,transformRatio=transformNeed?obtain('變身卷軸',transformNeed,p.settings.autoSupply&&p.settings.autoSupplyTransform):1;uptime=Math.min(uptime,.85+.15*transformRatio);let actual=Math.floor(potential*uptime);if(uptime<.05){actual=0;stopped=true}else if(uptime<1)stopped=true;let baseExp=m.normals.reduce((n,x)=>n+x.exp,0)/m.normals.length,baseGold=m.normals.reduce((n,x)=>n+x.gold,0)/m.normals.length,exp=Math.floor(actual*baseExp),gross=Math.floor(actual*baseGold*10),gear=[],books=[],materials={};
 let gearTries=Math.min(500,actual);for(let i=0;i<gearTries;i++){let item=equipmentDrop(p,m,rng);if(item)gear.push(item)}
 for(let sk of skillsFor(p)){let source=sk[6]||BOOK_SOURCES[sk[0]],sourceShare=m.normals.filter(x=>x.name===source).length/m.normals.length+(m.mini===source?0.043:0)+(m.boss===source?0.012:0);if(!sourceShare)continue;let drops=rollCount(actual*sourceShare,SKILL_TIER_RATE[skillTier(sk)],rng);for(let i=0;i<drops;i++)books.push(sk)}
 let bosses=m.boss?Math.floor(actual*.012):0,minis=m.mini?Math.floor(actual*.043):0;if(m.boss&&bosses){let key=BOSS_CATALOG.find(x=>x.name===m.boss)?.material;if(key)materials[key]=rollCount(bosses,.45,rng)}if(m.mini&&minis){let key=MINI_MATERIALS[m.mini];if(key)materials[key]=rollCount(minis,.28,rng)}
 let combatSec=Math.floor(sec*(stopped?uptime:.94)),petExp=Math.floor(exp*.1),petShares=p.activePets.length?Object.fromEntries(p.pets.filter(x=>p.activePets.includes(x.uid)&&x.alive).map(x=>[x.name,Math.floor(petExp/p.activePets.length)])):{};return{sec,combatSec,kills:actual,bosses:bosses+minis,deaths:Math.floor(actual*damageRate/3500),returns:Object.keys(purchased).length,exp,gross,cost,net:gross-cost,consumed,purchased,materials,gear,books,petExp,petShares,arrowName,arrowEffect:a,transformScrolls:consumed.變身卷軸||0,stopped}}
export function claimOffline(s,o){let p=s.player;gainExp(p,o.exp);petWin(p,o.petExp);p.gold=Math.max(0,p.gold+o.net);p.statsLog.kills+=o.kills;p.statsLog.bosses+=o.bosses;p.statsLog.deaths+=o.deaths;p.statsLog.goldEarned+=o.gross;p.statsLog.supplyCost+=o.cost;p.killsOnMap+=o.kills;for(let[n,v]of Object.entries(o.purchased||{}))p.consumables[n]=(p.consumables[n]||0)+v;for(let[n,v]of Object.entries(o.consumed||{}))p.consumables[n]=Math.max(0,(p.consumables[n]||0)-v);for(let[n,v]of Object.entries(o.materials||{}))p.bossMaterials[n]=(p.bossMaterials[n]||0)+v;for(let item of o.gear||[])addItem(p,item);for(let sk of o.books||[])addBook(p,sk);s.pendingOffline=null;s.lastOnlineTimestamp=Date.now()}
