import{calculateOffline as previousCalculateOffline,claimOffline}from'./offline.js?v=45';
import{expReward,goldReward}from'./balance-config.js';
import{mapFor}from'./hunting.js?v=58';
import{derived}from'./player.js?v=38';
import{weaponDamage,hitChance}from'./combat.js?v=57';
import{acDamageReduction}from'./balance.js?v=57';
const dragonOffline=(state,now,rng)=>{let p=state.player,m=mapFor(p.map),sec=Math.min(86400,Math.max(0,Math.floor((now-(state.lastOnlineTimestamp||now))/1000)));if(sec<60||p.inTown)return null;let e=m.dragonBoss,d=derived(p),hit=hitChance(p.equipment.武器?.type==='弓'?d.ranged:d.melee,e.ac,e.level),dps=weaponDamage(p,e,()=>.5)*d.speed*hit,incomingHit=hitChance(e.hit,d.ac,p.level),incoming=Math.max(1,e.atk*(1-acDamageReduction(d.ac))-(d.physicalReduction||0))*incomingHit/e.attackInterval,survival=d.maxHp/Math.max(1,incoming),killSec=e.maxHp/Math.max(1,dps),canKill=survival>=killSec,kills=canKill?Math.floor(sec/killSec):0,gear=[],materials={};if(kills){materials[e.material]=kills;for(let i=0;i<kills;i++)if(rng()<.008)gear.push(e.bossEntry.item)}let combatSec=canKill?sec:Math.min(sec,Math.max(1,Math.floor(survival))),exp=Math.floor(kills*e.exp),gross=Math.floor(kills*e.gold);return{sec,combatSec,kills,bosses:kills,deaths:canKill?0:1,returns:0,exp,gross,cost:0,net:gross,consumed:{},purchased:{},materials,gear,books:[],petExp:Math.floor(exp*.1),petShares:{},lootConsumables:{},petEvolutionMaterials:{},skillBookTrace:{kills:0,eligibleKills:0,rolls:0,success:0,books:[],rows:[]},dropTrace:{offlineSeconds:sec,effectiveCombatSeconds:combatSec,kills,monsterIds:[e.name],totalDropRolls:kills,gearRolls:kills,consumableRolls:0,actualGear:gear.length,actualBooks:0,actualMaterials:kills,dragon:true,survivalSeconds:survival,killSeconds:killSec},stopped:!canKill};};
export function calculateOffline(state,now=Date.now(),rng=Math.random){let p=state?.player;if(p&&mapFor(p.map).dragon)return dragonOffline(state,now,rng);let keys=['autoSupply','autoBuyHeal','autoBuyBlue','autoBuyArrows','autoSupplyGreen','autoSupplyBrave','autoSupplyTransform'],saved=p?Object.fromEntries(keys.map(k=>[k,p.settings[k]])):{};if(p)for(const k of keys)p.settings[k]=false;let report;try{report=previousCalculateOffline(state,now,rng)}finally{if(p)for(const k of keys)p.settings[k]=saved[k]}if(!report)return report;report.exp=expReward(report.exp,{offline:true});report.gross=goldReward(report.gross/10,{offline:true});report.cost=0;report.net=report.gross;report.purchased={};report.stopped=false;delete report.consumed?.['魔力藥水'];return report}
export{claimOffline};
