import{speedBuff}from'./balance.js?v=10';import{normalTransform,transformWeaponSpeed,ATTACK_SPEED_CAP}from'./transformations.js?v=10';import{CLASSES,CONSUMABLES,DOLLS}from'./data.js?v=10';import{CLASS_WEAPON_MODIFIERS,TRANSFORMATIONS,BOSS_SETS,setState}from'./systems.js?v=10';import{passive}from'./skills.js?v=10';
export function createPlayer(name,cls){let c=CLASSES[cls],s=c.stats;return{name,cls,level:1,exp:0,hp:c.hp,mp:c.mp,gold:6000,stats:{str:s[0],dex:s[1],con:s[2],int:s[3],wis:s[4],cha:s[5]},equipment:{},bag:[],warehouse:[],consumables:{紅色藥水:60,橙色藥水:10,白色藥水:2,藍色藥水:5,勇氣藥水:0,精靈餅乾:0,魔力藥水:5,回城卷軸:3,瞬間移動卷軸:5,武器強化卷軸:0,防具強化卷軸:0,祝福武器強化卷軸:0,祝福防具強化卷軸:0},map:0,inTown:true,killsOnMap:0,bossMaterials:{},worldMaterials:{},skills:{},transforms:[0],transform:0,dolls:[0],doll:0,lostExp:0,settings:{autoPotion:true,thresholds:{紅色藥水:70,橙色藥水:50,白色藥水:30},autoSupply:true,target:{紅色藥水:300,橙色藥水:80,白色藥水:20,藍色藥水:30},autoBuff:true,autoWorldBoss:false,autoSell:true},statsLog:{kills:0,bosses:0,deaths:0,worldBosses:0,goldEarned:0,supplyCost:0,potions:{},playSeconds:0,sessionStart:Date.now(),sessionGold:0,sessionExp:0,sessionKills:0,returns:0}}}
export function expNeed(l){if(l<10)return 45+l*28+l*l*4;if(l<20)return 700+(l-10)*180+(l-10)**2*24;if(l<30)return 4900+(l-20)*950+(l-20)**2*115;if(l<40)return 25900+(l-30)*4200+(l-30)**2*520;if(l<50)return 119900+(l-40)*18000+(l-40)**2*2500;return Math.floor(549900*Math.pow(1.19,l-50))}function stats(p){let s={...p.stats};Object.values(p.equipment).filter(Boolean).forEach(i=>['str','dex','con','int','wis','cha'].forEach(k=>s[k]+=(i[k]||0)));return s}export function maxHp(p){let s=stats(p);return Math.floor(CLASSES[p.cls].hp+p.level*(5+s.con*.55))}export function maxMp(p){let s=stats(p);return Math.floor(CLASSES[p.cls].mp+p.level*(1+s.wis*.35))}
export function weight(p){let s=stats(p),w=Object.entries(p.consumables).reduce((n,[k,v])=>n+(CONSUMABLES[k]?.weight||1)*v,0)+p.bag.reduce((n,i)=>n+(i.weight||10),0),d=DOLLS[p.doll],max=600+s.str*35+(d?.effect==='weight'?d.value:0);return{current:w,max,ratio:w/max}}
export function derived(p){let s=stats(p),eq=Object.values(p.equipment).filter(Boolean),weapon=p.equipment.武器,doll=DOLLS[p.doll],sets=setState(p.equipment),bonus={hp:0,mp:0,hit:0,damage:0,magic:0,speed:0};for(let set of BOSS_SETS){let c=sets[set.id]||0;for(let n of[2,3,4])if(c>=n)for(let[k,v]of Object.entries(set.effects[n]))bonus[k]=(bonus[k]||0)+v}let full=BOSS_SETS.find(x=>(sets[x.id]||0)>=4),active=normalTransform(p),tr=full?{name:full.name,bossSet:true}:active||{name:'無變身'},mod=CLASS_WEAPON_MODIFIERS[p.cls]?.[weapon?.type]||[1,1],ac=10+eq.reduce((n,i)=>n+(i.ac||0)-(i.enhance||0),0)+(doll?.effect==='ac'?doll.value:0)-(passive(p,'增幅防禦')?3:0),melee=p.level+Math.floor(s.str*1.3)+(weapon?.hit||0)+bonus.hit,ranged=p.level+Math.floor(s.dex*1.35)+(weapon?.hit||0)+bonus.hit,magic=Math.floor(s.int*.75+p.level*.25)+bonus.magic,transformSpeed=full?1+(full.effects[4].speed||0):transformWeaponSpeed(p),baseSpeed=mod[0]*transformSpeed*(1+bonus.speed),speed=Math.min(ATTACK_SPEED_CAP,baseSpeed*speedBuff(p)),physicalReduction=Math.min(20,eq.reduce((n,i)=>n+(i.damageReduction||0),0));return{ac,melee,ranged,magic,speed,baseSpeed,physicalReduction,damageMod:mod[1]*(1+bonus.damage*.03),maxHp:maxHp(p)+bonus.hp,maxMp:maxMp(p)+bonus.mp,weight:weight(p),stats:s,transform:tr.name,sets}}
export function gainExp(p,n){p.exp+=n;p.statsLog.sessionExp+=n;let ups=0;while(p.level<99&&p.exp>=expNeed(p.level)){p.exp-=expNeed(p.level);p.level++;p.stats.str+=p.level%4===0?1:0;p.stats.con+=p.level%6===0?1:0;p.stats.dex+=p.level%5===0?1:0;ups++}return ups}





