export const REBIRTH_CONFIG={levelRequirement:60,hpPerRebirth:.02,mpPerRebirth:.02,physicalPerRebirth:.01,magicPerRebirth:.01,milestones:[3,5,10,15,20]};
export const REBIRTH_SKILL_ADVANCEMENTS={王族:[['激勵士氣強化 I','團隊增益特色'],['精準目標強化 I','MP效率 +10%'],['鋼鐵意志強化 I','防禦特色'],['激勵士氣強化 II','物理傷害 +5%'],['精準目標強化 II','傷害 +10%']],騎士:[['近戰鍛鍊 I','物理傷害 +4%'],['衝擊之暈強化 I','MP效率 +10%'],['增幅防禦強化 I','AC -1'],['近戰鍛鍊 II','物理傷害再 +4%'],['衝擊之暈強化 II','傷害 +10%']],法師:[['召喚強化 I','召喚 HP／攻擊 +8%'],['聖結界強化 I','NEEDS_VERIFICATION：目前技能表無聖結界'],['隕石術強化 I','傷害 +10%'],['召喚強化 II','召喚 HP／攻擊再 +10%'],['究極光裂術強化 I','NEEDS_VERIFICATION：目前技能表無究極光裂術']],黑暗妖精:[['雙刀／鋼爪鍛鍊 I','物理傷害 +4%'],['燃燒鬥志強化 I','爆發特色'],['雙重破壞強化 I','物理傷害再 +5%'],['暗殺強化 I','傷害 +10%'],['暗影之牙強化 I','爆發特色']],龍騎士:[['屠宰者強化 I','傷害 +5%'],['龍牙強化 I','MP效率 +10%'],['弱點曝光強化 I','破防特色'],['屠宰者強化 II','傷害再 +8%'],['龍之怒強化 I','傷害 +10%']],幻術士:[['幻刃強化 I','傷害 +5%'],['專注強化 I','MP效率 +10%'],['心靈破壞強化 I','傷害 +8%'],['鏡像強化 I','生存特色'],['幻滅強化 I','傷害 +10%']]};
export const ELF_REBIRTH_ADVANCEMENTS={風:[['三重矢強化 I','傷害 +5%'],['三重矢節能 I','MP -2'],['三重矢迅捷 I','CD -0.4秒'],['遠距鍛鍊 I','遠距傷害 +6%'],['三重矢追擊 I','20%追加1箭，額外消耗1箭']],水:[['治療強化 I','治療 +8%'],['治療節能 I','治療 MP -2'],['水屬魔法強化 I','治療再 +8%'],['冥想 I','MP恢復 +8%'],['危急治療 I','低HP治療再 +12%']],火:[['近戰鍛鍊 I','近戰傷害 +5%'],['火屬節能 I','火屬技能 MP -2'],['火屬攻擊強化 I','火屬傷害 +8%'],['近戰鍛鍊 II','近戰傷害再 +6%'],['烈焰之魂強化 I','火屬傷害再 +10%']],地:[['大地防護強化 I','AC -1'],['地屬節能 I','地屬技能 MP -2'],['地屬魔法強化 I','防禦特色'],['大地減傷 I','物理減傷 +3%'],['危急防護 I','低HP物理減傷再 +4%']]};
const count=p=>Math.max(0,Math.floor(Number(p?.rebirthCount)||0));
export function rebirthBonuses(p){let n=count(p),milestones=REBIRTH_CONFIG.milestones.filter(x=>n>=x),element=p?.cls==='妖精'?(p.elfElement||'風'):null;return{count:n,hp:1+n*REBIRTH_CONFIG.hpPerRebirth,mp:1+n*REBIRTH_CONFIG.mpPerRebirth,physical:1+n*REBIRTH_CONFIG.physicalPerRebirth,magic:1+n*REBIRTH_CONFIG.magicPerRebirth,milestones,element}}
export function unlockedAdvancements(p){let b=rebirthBonuses(p),rows=p.cls==='妖精'?ELF_REBIRTH_ADVANCEMENTS[b.element]||[]:REBIRTH_SKILL_ADVANCEMENTS[p.cls]||[];return b.milestones.map((m,i)=>({rebirth:m,name:rows[i]?.[0]||'NEEDS_VERIFICATION',effect:rows[i]?.[1]||'NEEDS_VERIFICATION'}))}
export function combatAdvancement(p){let b=rebirthBonuses(p),n=b.count,e=b.element;return{physical:b.physical*((p.cls==='騎士'&&n>=3?1.04:1)*(p.cls==='騎士'&&n>=15?1.04:1)*(p.cls==='黑暗妖精'&&n>=3?1.04:1)*(p.cls==='黑暗妖精'&&n>=10?1.05:1)*(e==='風'&&n>=15?1.06:1)*(e==='火'&&n>=3?1.05:1)*(e==='火'&&n>=15?1.06:1)),magic:b.magic,ac:(p.cls==='騎士'&&n>=10?1:0)+(e==='地'&&n>=3?1:0),reduction:e==='地'&&n>=15?.03:0,manaRegen:e==='水'&&n>=15?1.08:1,summon:n>=15&&p.cls==='法師'?1.18:n>=3&&p.cls==='法師'?1.08:1}}
export function advancedSkill(p,skill){let n=count(p),name=skill[0],element=p.elfElement,mp=skill[3],mult=skill[4]||1,cd=skill[5]||6,arrows=name==='三重矢'?3:0,extraArrowChance=0,heal=1;if(name==='三重矢'&&element==='風'){if(n>=3)mult*=1.05;if(n>=5)mp=Math.max(0,mp-2);if(n>=10)cd=Math.max(1,cd-.4);if(n>=20)extraArrowChance=.2}if(p.cls==='法師'&&name==='隕石術'&&n>=10)mult*=1.1;if(p.cls==='騎士'&&name==='衝擊之暈'){if(n>=5)mp=Math.max(0,mp-2);if(n>=20)mult*=1.1}if(p.cls==='龍騎士'&&name==='屠宰者'){if(n>=3)mult*=1.05;if(n>=15)mult*=1.08}if(p.cls==='幻術士'&&name==='幻刃'&&n>=3)mult*=1.05;if(p.cls==='黑暗妖精'&&name==='暗殺'&&n>=15)mult*=1.1;if(p.cls==='妖精'&&element==='水'&&skill[2]==='recover'){if(n>=3)heal*=1.08;if(n>=5)mp=Math.max(0,mp-2);if(n>=10)heal*=1.08}if(p.cls==='妖精'&&element==='火'&&skill[7]==='火'){if(n>=5)mp=Math.max(0,mp-2);if(n>=10)mult*=1.08;if(n>=20)mult*=1.1}return{mp,mult,cd,arrows,extraArrowChance,heal}}
export function createRebirthPlayer(p){if(!p||p.level<REBIRTH_CONFIG.levelRequirement)return null;let next=structuredClone(p),before={equipment:Object.values(p.equipment||{}).filter(Boolean).map(x=>x.instanceId||x.uid).sort(),bag:(p.bag||[]).map(x=>x.instanceId||x.uid).sort(),skills:[...(p.learnedSkills||[])].sort()};next.level=1;next.exp=0;next.rebirthCount=count(p)+1;next.hp=1;next.mp=0;let after={equipment:Object.values(next.equipment||{}).filter(Boolean).map(x=>x.instanceId||x.uid).sort(),bag:(next.bag||[]).map(x=>x.instanceId||x.uid).sort(),skills:[...(next.learnedSkills||[])].sort()};if(JSON.stringify(before)!==JSON.stringify(after))return null;return next}
