import{FULL_SKILLS}from'./balance.js?v=27';import{SKILL_DEFS,BOOK_SOURCES,HUNTING_MAPS}from'./systems.js?v=27';import{SKILL_TIER_RATE}from'./loot.js?v=27';
export const BOOK_SOURCE_ALTERNATES={精準目標:['妖魔戰士','妖魔弓手'],勇猛意志:['獸人戰士','黑騎士'],增幅防禦:['骷髏兵','骷髏弓手','黑騎士'],魂體轉換:['精靈弓手','風精靈','水精靈'],燃燒鬥志:['黑騎士','妖魔巡守'],影襲:['黑騎士','暗影獸'],血之渴望:['邪惡蜥蜴','巨蟻兵'],弱點曝光:['巨大螞蟻','巨蟻兵'],龍牙:['黑騎士','骷髏近衛兵'],專注:['骷髏法師','妖魔法師'],幻刃:['骷髏弓手','骷髏法師'],骷髏毀壞:['殭屍','不死的木乃伊']};
const progressionMaps=level=>level<15?[0,1,2]:level<25?[2,3,4,5]:level<35?[4,5,6,7,8]:level<45?[7,8,9,10,11]:[10,11,12,13,14,15,16,17];
export function skillSourceDetails(s){let named=[s[6]||BOOK_SOURCES[s[0]],...(BOOK_SOURCE_ALTERNATES[s[0]]||[])].filter(Boolean),maps=progressionMaps(s[1]),rows=[];for(const m of HUNTING_MAPS){for(const n of m.normals)if(named.includes(n.name))rows.push({mapId:m.id,map:m.name,floor:m.floor||null,monster:n.name,boss:null});if(named.includes(m.mini))rows.push({mapId:m.id,map:m.name,floor:m.floor||null,monster:null,boss:m.mini});if(named.includes(m.boss))rows.push({mapId:m.id,map:m.name,floor:m.floor||null,monster:null,boss:m.boss})}for(const id of maps){let m=HUNTING_MAPS.find(x=>x.id===id),n=m?.normals[(s[0].length+id)%Math.max(1,m?.normals.length||1)];if(m&&n&&!rows.some(x=>x.mapId===id&&x.monster===n.name))rows.push({mapId:id,map:m.name,floor:m.floor||null,monster:n.name,boss:null,progression:true})}return rows}
export const skillSources=s=>skillSourceDetails(s).flatMap(x=>[x.monster,x.boss]).filter((x,i,a)=>x&&a.indexOf(x)===i);
export const skillsFor=p=>FULL_SKILLS[p.cls]||[];export const skillTier=s=>s[1]<15?'初階':s[1]<25?'中低階':s[1]<35?'中階':s[1]<45?'高階':s[1]<55?'稀有高階':'頂級';export const bookName=(p,n)=>`${p.cls==='法師'?'魔法書':p.cls==='騎士'?'技術書':'技能書'}：${n}`;
export function learnSkill(p,name){let s=skillsFor(p).find(x=>x[0]===name),book=p.bag.find(x=>x.kind==='book'&&x.skill===name);if(!s||p.level<s[1]||!book||p.learnedSkills.includes(name)||(s[7]&&p.elfElement!==s[7]))return false;book.count--;if(book.count<=0)p.bag=p.bag.filter(x=>x!==book);p.skillBooks[name]=Math.max(0,(p.skillBooks[name]||0)-1);p.learnedSkills.push(name);if(s[2]==='active'&&p.activeSkillSettings.attack.length<2)p.activeSkillSettings.attack.push(name);if(s[2]==='recover'&&!p.activeSkillSettings.heal)p.activeSkillSettings.heal=name;return true}
export function addBook(p,s){let n=s[0],book=p.bag.find(x=>x.kind==='book'&&x.skill===n);if(book)book.count++;else p.bag.push({uid:`book-${n}`,kind:'book',name:bookName(p,n),skill:n,cls:p.cls,level:s[1],tier:skillTier(s),count:1,price:2500+s[1]*500,weight:1});p.skillBooks[n]=(p.skillBooks[n]||0)+1}
export function skillDrop(enemy,p,rng=Math.random,context={}){
 let all=skillsFor(p),first=all.find(s=>s[1]<=20),names=all.filter(s=>p.level+5>=s[1]&&(skillSources(s).includes(enemy.name)||(p.level>=30&&s===first&&!p.learnedSkills.includes(s[0])&&(p.skillBooks[s[0]]||0)<1))),before=p.bag.filter(x=>x.kind==='book').reduce((n,x)=>n+x.count,0),trace={monsterId:enemy.id||enemy.name,mapId:context.mapId??p.map,floor:context.floor||null,playerClass:p.cls,eligibleSourceKills:names.length?1:0,eligibleSkillBooks:[],inventoryBefore:before,inventoryAfter:before};
 for(let s of names){let tier=skillTier(s),pity=p.skillPity[s[0]]||0,boost=['初階','中低階','中階'].includes(tier)?Math.min(3,pity/25):0,progressionFallback=s===first&&!skillSources(s).includes(enemy.name),base=SKILL_TIER_RATE[tier]*(progressionFallback?.45:1),rate=base*(1+boost),roll=rng(),row={name:s[0],sourceMatch:!progressionFallback,progressionFallback,baseDropRate:base,pityMultiplier:1+boost,finalDropRate:rate,roll,success:false,added:false};p.skillPity[s[0]]=pity+1;if(roll<rate){addBook(p,s);p.skillPity[s[0]]=0;row.success=row.added=true;trace.eligibleSkillBooks.push(row);trace.inventoryAfter=p.bag.filter(x=>x.kind==='book').reduce((n,x)=>n+x.count,0);if(p.debug?.dropTrace)p.debug.dropTrace.push(trace);return s}trace.eligibleSkillBooks.push(row)}if(p.debug?.dropTrace)p.debug.dropTrace.push(trace);return null
}
export function selectActiveSkill(p,name){let s=skillsFor(p).find(x=>x[0]===name&&x[2]==='active');if(!s||!p.learnedSkills.includes(name))return false;p.activeSkillSettings.selectedActiveSkill=name;if(!p.activeSkillSettings.attack.includes(name))p.activeSkillSettings.attack.push(name);return true}
export function passive(p,name){return p.learnedSkills?.includes(name)||false}export function activeSkill(p){let name=p.activeSkillSettings.selectedActiveSkill||p.activeSkillSettings.attack?.[0],s=skillsFor(p).find(x=>x[0]===name&&x[2]==='active'&&p.learnedSkills.includes(x[0]));return s&&p.mp>=s[3]?s:null}export function healSkill(p){return skillsFor(p).find(s=>s[0]===p.activeSkillSettings.heal&&p.learnedSkills.includes(s[0])&&p.mp>=s[3])}



