import{CONSUMABLES}from'./data.js?v=53';
export const TRANSFORM_DURATION=1800,ATTACK_SPEED_CAP=2.6;
CONSUMABLES.變身卷軸={price:1000,weight:1,transform:true,duration:TRANSFORM_DURATION};
const T=(id,name,requiredLevel,weaponSpeeds,magicCompatible=true,moveSpeed=1,category='經典')=>({id,name,requiredLevel,allowedWeaponTypes:Object.keys(weaponSpeeds),weaponSpeeds,magicCompatible,moveSpeed,category});
export const TRANSFORMATIONS=[
T('orc','甘地妖魔',1,{匕首:1.02,單手劍:1.02}),T('skeleton','骷髏',10,{匕首:1.07,單手劍:1.06}),T('skeleton-spear','骷髏槍兵',10,{單手劍:1.05,雙手劍:1.08}),T('skeleton-bow','骷髏弓箭手',10,{弓:1.08}),T('skeleton-axe','骷髏斧手',10,{單手劍:1.04,雙手劍:1.03}),T('zombie','殭屍',10,{匕首:.96,單手劍:.96}),T('ghoul','食屍鬼',10,{匕首:1.02,單手劍:1.02}),T('spartoi','史巴托',10,{匕首:1.12,單手劍:1.11}),T('lycan','萊肯',10,{匕首:1.08,單手劍:1.08}),T('troll','食人妖精',10,{雙手劍:1.1,鎖鏈劍:1.04}),
T('orc-scout','妖魔巡守',15,{弓:1.2,匕首:1.03},true,1.05),T('elder','長老',15,{法杖:1.16,匕首:1.02}),T('ogre','歐吉',15,{雙手劍:1.16,鎖鏈劍:1.1},false,.95),T('hellhound','地獄犬',15,{鋼爪:1.15},false,1.12),
T('baphomet','巴風特',45,{法杖:1.22,匕首:1.08},true,1.2,'高階'),T('beleth','巴列斯',45,{法杖:1.2,單手劍:1.08},true,1.12,'高階'),T('black-elder','黑長者',45,{法杖:1.27,匕首:1.08},true,1.08,'高階'),T('caspa','卡士柏',45,{法杖:1.24},true,1.05,'高階'),T('merkyor','馬庫爾',45,{法杖:1.23},true,1.05,'高階'),T('sema','西瑪',45,{法杖:1.22},true,1.05,'高階'),T('balthazar','巴土瑟',45,{法杖:1.21},true,1.05,'高階'),
T('kurtz','克特',51,{單手劍:1.42,匕首:1.3,雙手劍:1.2},true,1.08,'特殊'),T('demon','惡魔',51,{單手劍:1.38,雙手劍:1.28,鋼爪:1.22},true,1.08,'特殊'),T('fire-bow','火焰弓箭手',51,{弓:1.38},true,1.08,'特殊'),T('death-knight','死亡騎士',52,{匕首:1.46,單手劍:1.48,雙手劍:1.34},true,1.1,'52級'),T('dark-elf','黑暗精靈',52,{弓:1.48,匕首:1.26,雙刀:1.32,鋼爪:1.3},true,1.1,'52級'),T('dark-knight','黑暗騎士',55,{單手劍:1.55,雙手劍:1.42,鎖鏈劍:1.34},true,1.12,'55級'),T('dark-mage','黑暗法師',55,{法杖:1.42,匕首:1.22},true,1.1,'55級'),T('dark-scout','黑暗巡守',55,{弓:1.56,匕首:1.2},true,1.12,'55級'),
{...T('rebirth-3','迅影先鋒【3轉】',1,{匕首:1.65,單手劍:1.65,雙手劍:1.58,弓:1.62,法杖:1.5,雙刀:1.64,鋼爪:1.62,鎖鏈劍:1.6},true,1.08,'REBIRTH_EXCLUSIVE'),requiredRebirth:3,combatBonus:{hit:2,melee:.03,ranged:.03,magic:2,mpRegen:.03}},{...T('rebirth-5','赤月戰將【5轉】',1,{匕首:1.78,單手劍:1.78,雙手劍:1.68,弓:1.74,法杖:1.58,雙刀:1.77,鋼爪:1.74,鎖鏈劍:1.72},true,1.1,'REBIRTH_EXCLUSIVE'),requiredRebirth:5,combatBonus:{hit:3,melee:.05,ranged:.05,magic:3,mpRegen:.05}},{...T('rebirth-10','天耀英雄【10轉】',1,{匕首:1.92,單手劍:1.92,雙手劍:1.8,弓:1.88,法杖:1.68,雙刀:1.91,鋼爪:1.88,鎖鏈劍:1.85},true,1.12,'REBIRTH_EXCLUSIVE'),requiredRebirth:10,combatBonus:{hit:5,melee:.08,ranged:.08,magic:5,mpRegen:.08}},{...T('rebirth-15','神域霸主【15轉】',1,{匕首:2.08,單手劍:2.08,雙手劍:1.94,弓:2.03,法杖:1.8,雙刀:2.07,鋼爪:2.03,鎖鏈劍:1.99},true,1.14,'REBIRTH_EXCLUSIVE'),requiredRebirth:15,combatBonus:{hit:7,melee:.11,ranged:.11,magic:7,mpRegen:.11}},{...T('rebirth-20','永恆傳奇【20轉】',1,{匕首:2.25,單手劍:2.25,雙手劍:2.08,弓:2.18,法杖:1.92,雙刀:2.23,鋼爪:2.18,鎖鏈劍:2.14},true,1.16,'REBIRTH_EXCLUSIVE'),requiredRebirth:20,combatBonus:{hit:9,melee:.15,ranged:.15,magic:10,mpRegen:.15}}];
export const transformById=id=>TRANSFORMATIONS.find(x=>x.id===id);
export const compatible=(t,weapon)=>!!t&&(!weapon||t.allowedWeaponTypes.includes(weapon.type));
export const unlocked=p=>TRANSFORMATIONS.filter(t=>p.level>=t.requiredLevel&&(p.rebirthCount||0)>=(t.requiredRebirth||0));
export function recommend(p){let w=p.equipment.武器;return unlocked(p).filter(t=>compatible(t,w)).sort((a,b)=>(b.weaponSpeeds[w?.type]||1)-(a.weaponSpeeds[w?.type]||1))[0]||null}
export function normalTransform(p,now=Date.now()){let t=transformById(p.transformState?.id);return t&&p.transformState.until>now&&p.level>=t.requiredLevel&&(p.rebirthCount||0)>=(t.requiredRebirth||0)&&compatible(t,p.equipment.武器)?t:null}
export const transformWeaponSpeed=(p,now=Date.now())=>{let t=normalTransform(p,now);return t?(t.weaponSpeeds[p.equipment.武器?.type]||1):1};
export function transformAttempt(p,id,now=Date.now()){let t=transformById(id),weapon=p.equipment.武器,before=p.transformState?.id||null,intervalBefore=p.__derivedSpeed?1/p.__derivedSpeed:null,trace={autoTransform:!!p.settings.autoTransform,selectedTransformation:id,playerLevel:p.level,requiredLevel:t?.requiredLevel??null,requiredRebirth:t?.requiredRebirth??0,weaponType:weapon?.type||null,allowedWeaponTypes:t?.allowedWeaponTypes||[],scrollCount:p.consumables.變身卷軸||0,eligibilityResult:false,rejectReason:null,consumeResult:false,currentTransformationBefore:before,currentTransformationAfter:before,expireAt:p.transformState?.until||0,attackIntervalBefore:intervalBefore,attackIntervalAfter:intervalBefore};if(!t)trace.rejectReason='未選擇有效變身';else if(p.level<t.requiredLevel)trace.rejectReason='等級不足';else if((p.rebirthCount||0)<(t.requiredRebirth||0))trace.rejectReason='轉生次數不足';else if(!compatible(t,weapon))trace.rejectReason='武器類型不符';else if((p.consumables.變身卷軸||0)<1)trace.rejectReason='變身卷軸不足';else{trace.eligibilityResult=true;p.consumables.變身卷軸--;p.transformState={id,until:now+TRANSFORM_DURATION*1000};trace.consumeResult=true;trace.currentTransformationAfter=id;trace.expireAt=p.transformState.until;let mult=t.weaponSpeeds[weapon?.type]||1;trace.attackIntervalAfter=intervalBefore?intervalBefore/mult:null}p.debug??={};p.debug.transformTrace=trace;return trace}
export function activateTransform(p,id,now=Date.now()){return transformAttempt(p,id,now).consumeResult}
export function autoTransform(p,now=Date.now()){if(p.transformState?.until>now){p.debug??={};p.debug.transformTrace={autoTransform:!!p.settings.autoTransform,eligibilityResult:true,rejectReason:'目前變身仍有效',currentTransformationBefore:p.transformState.id,currentTransformationAfter:p.transformState.id,expireAt:p.transformState.until};return false}if(!p.settings.autoTransform){p.debug??={};p.debug.transformTrace={autoTransform:false,eligibilityResult:false,rejectReason:'自動變身未開啟'};return false}let t=p.settings.autoTransformMode==='best'?recommend(p):transformById(p.settings.autoTransformId);return transformAttempt(p,t?.id||p.settings.autoTransformId,now).consumeResult}
export function simulateOfflineTransform(p,seconds,now=Date.now()){let active=Math.max(0,Math.min(seconds,((p.transformState?.until||0)-now)/1000)),scrolls=0,t=normalTransform(p,now)||(p.settings.autoTransformMode==='best'?recommend(p):transformById(p.settings.autoTransformId));if(p.settings.autoTransform&&t){let remaining=seconds-active;scrolls=Math.min(p.consumables.變身卷軸||0,Math.ceil(Math.max(0,remaining)/TRANSFORM_DURATION));active=Math.min(seconds,active+scrolls*TRANSFORM_DURATION)}let gain=(t?.weaponSpeeds[p.equipment.武器?.type]||1)-1;return{transform:t,activeSeconds:active,scrolls,multiplier:seconds?1+gain*active/seconds:1}}
