import{CONSUMABLES}from'./data.js?v=13';
export const TRANSFORM_DURATION=1800,ATTACK_SPEED_CAP=2.6;
CONSUMABLES.變身卷軸={price:1000,weight:1,transform:true,duration:TRANSFORM_DURATION};
const T=(id,name,requiredLevel,weaponSpeeds,magicCompatible=true,moveSpeed=1,category='經典')=>({id,name,requiredLevel,allowedWeaponTypes:Object.keys(weaponSpeeds),weaponSpeeds,magicCompatible,moveSpeed,category});
export const TRANSFORMATIONS=[
T('orc','甘地妖魔',1,{匕首:1.02,單手劍:1.02}),T('skeleton','骷髏',10,{匕首:1.07,單手劍:1.06}),T('skeleton-spear','骷髏槍兵',10,{單手劍:1.05,雙手劍:1.08}),T('skeleton-bow','骷髏弓箭手',10,{弓:1.08}),T('skeleton-axe','骷髏斧手',10,{單手劍:1.04,雙手劍:1.03}),T('zombie','殭屍',10,{匕首:.96,單手劍:.96}),T('ghoul','食屍鬼',10,{匕首:1.02,單手劍:1.02}),T('spartoi','史巴托',10,{匕首:1.12,單手劍:1.11}),T('lycan','萊肯',10,{匕首:1.08,單手劍:1.08}),T('troll','食人妖精',10,{雙手劍:1.1,鎖鏈劍:1.04}),
T('orc-scout','妖魔巡守',15,{弓:1.2,匕首:1.03},true,1.05),T('elder','長老',15,{法杖:1.16,匕首:1.02}),T('ogre','歐吉',15,{雙手劍:1.16,鎖鏈劍:1.1},false,.95),T('hellhound','地獄犬',15,{鋼爪:1.15},false,1.12),
T('baphomet','巴風特',45,{法杖:1.22,匕首:1.08},true,1.2,'高階'),T('beleth','巴列斯',45,{法杖:1.2,單手劍:1.08},true,1.12,'高階'),T('black-elder','黑長者',45,{法杖:1.27,匕首:1.08},true,1.08,'高階'),T('caspa','卡士柏',45,{法杖:1.24},true,1.05,'高階'),T('merkyor','馬庫爾',45,{法杖:1.23},true,1.05,'高階'),T('sema','西瑪',45,{法杖:1.22},true,1.05,'高階'),T('balthazar','巴土瑟',45,{法杖:1.21},true,1.05,'高階'),
T('kurtz','克特',51,{單手劍:1.42,匕首:1.3,雙手劍:1.2},true,1.08,'特殊'),T('demon','惡魔',51,{單手劍:1.38,雙手劍:1.28,鋼爪:1.22},true,1.08,'特殊'),T('fire-bow','火焰弓箭手',51,{弓:1.38},true,1.08,'特殊'),T('death-knight','死亡騎士',52,{匕首:1.46,單手劍:1.48,雙手劍:1.34},true,1.1,'52級'),T('dark-elf','黑暗精靈',52,{弓:1.48,匕首:1.26,雙刀:1.32,鋼爪:1.3},true,1.1,'52級'),T('dark-knight','黑暗騎士',55,{單手劍:1.55,雙手劍:1.42,鎖鏈劍:1.34},true,1.12,'55級'),T('dark-mage','黑暗法師',55,{法杖:1.42,匕首:1.22},true,1.1,'55級'),T('dark-scout','黑暗巡守',55,{弓:1.56,匕首:1.2},true,1.12,'55級')];
export const transformById=id=>TRANSFORMATIONS.find(x=>x.id===id);
export const compatible=(t,weapon)=>!!t&&(!weapon||t.allowedWeaponTypes.includes(weapon.type));
export const unlocked=p=>TRANSFORMATIONS.filter(t=>p.level>=t.requiredLevel);
export function recommend(p){let w=p.equipment.武器;return unlocked(p).filter(t=>compatible(t,w)).sort((a,b)=>(b.weaponSpeeds[w?.type]||1)-(a.weaponSpeeds[w?.type]||1))[0]||null}
export function normalTransform(p,now=Date.now()){let t=transformById(p.transformState?.id);return t&&p.transformState.until>now&&p.level>=t.requiredLevel&&compatible(t,p.equipment.武器)?t:null}
export const transformWeaponSpeed=(p,now=Date.now())=>{let t=normalTransform(p,now);return t?(t.weaponSpeeds[p.equipment.武器?.type]||1):1};
export function activateTransform(p,id,now=Date.now()){let t=transformById(id);if(!t||p.level<t.requiredLevel||!compatible(t,p.equipment.武器)||(p.consumables.變身卷軸||0)<1)return false;p.consumables.變身卷軸--;p.transformState={id,until:now+TRANSFORM_DURATION*1000};return true}
export function autoTransform(p,now=Date.now()){if(p.transformState?.until>now||!p.settings.autoTransform||(p.consumables.變身卷軸||0)<1)return false;let t=p.settings.autoTransformMode==='best'?recommend(p):transformById(p.settings.autoTransformId);return t?activateTransform(p,t.id,now):false}
export function simulateOfflineTransform(p,seconds,now=Date.now()){let active=Math.max(0,Math.min(seconds,((p.transformState?.until||0)-now)/1000)),scrolls=0,t=normalTransform(p,now)||(p.settings.autoTransformMode==='best'?recommend(p):transformById(p.settings.autoTransformId));if(p.settings.autoTransform&&t){let remaining=seconds-active;scrolls=Math.min(p.consumables.變身卷軸||0,Math.ceil(Math.max(0,remaining)/TRANSFORM_DURATION));active=Math.min(seconds,active+scrolls*TRANSFORM_DURATION)}let gain=(t?.weaponSpeeds[p.equipment.武器?.type]||1)-1;return{transform:t,activeSeconds:active,scrolls,multiplier:seconds?1+gain*active/seconds:1}}
