import{UI}from'./ui.js?v=38';
import{skillsFor}from'./skills.js?v=53';
import{SUMMON_TYPES}from'./systems.js?v=45';
import{summonStatus}from'./companions.js?v=45';
import{derived}from'./player.js?v=38';
const previousMore=UI.prototype.more;
UI.prototype.more=function(p){let html=previousMore.call(this,p),skills=skillsFor(p).filter(s=>p.learnedSkills.includes(s[0])),attacks=skills.filter(s=>s[2]==='active'),heals=skills.filter(s=>s[2]==='recover'&&s[0]!=='魂體轉換'),resources=skills.filter(s=>s[0]==='魂體轉換'),skillPanel=`<h2>自動技能設定</h2><div class="card"><b>【攻擊】</b>${attacks.map(s=>`<label><input type="checkbox" data-attack-skill="${s[0]}" ${p.activeSkillSettings.attack.includes(s[0])?'checked':''}> ${s[0]}（MP ${s[3]}・CD ${s[5]||6}秒）</label>`).join('')||'<p>尚無可用攻擊技能</p>'}</div><div class="card"><b>【治療】</b>${heals.map(s=>`<label><input type="checkbox" data-heal-skill="${s[0]}" ${([p.activeSkillSettings.heal].flat()).includes(s[0])?'checked':''}> ${s[0]}</label>`).join('')||'<p>尚無可用治療技能</p>'}<label>HP低於 <input id="skill-heal-threshold" type="number" min="1" max="99" value="${p.activeSkillSettings.healThreshold}">%</label></div><div class="card"><b>【資源】</b>${resources.map(s=>`<label><input id="auto-soul" type="checkbox" ${(p.activeSkillSettings.resource?.['魂體轉換']??true)?'checked':''}> 魂體轉換</label><label>MP低於 <input id="soul-mp" type="number" min="1" max="99" value="${p.activeSkillSettings.soulMpBelow??30}">%</label><label>HP高於 <input id="soul-hp" type="number" min="1" max="99" value="${p.activeSkillSettings.soulHpAbove??70}">%</label>`).join('')||'<p>尚無可用資源技能</p>'}</div>`;if(p.cls==='法師'){let d=derived(p),rows=SUMMON_TYPES.map(x=>{let s=summonStatus(p,x.id);return`<div class="card"><b>${x.name}</b><br><small>Lv.${x.level}・CHA ${x.requiredCha}・${x.skill}<br>${s.ok?'可召喚':s.reasons.join('；')}</small><br><button data-summon="${x.id}" ${s.ok?'':'disabled'}>召喚</button></div>`}).join('');skillPanel+=`<h2>經典召喚</h2><p>角色 Lv.${p.level}・最終 CHA ${d.stats.cha}<br>召喚控制戒指：${summonStatus(p,SUMMON_TYPES[0].id)?.hasRing?'已裝備，可指定種類':'未裝備，自動選擇符合條件的最高種類'}</p>${rows}`}
 return html.replace('<h2>設定與存檔</h2>',skillPanel+'<h2>設定與存檔</h2>');
};
const previousBind=UI.prototype.bind;
UI.prototype.bind=function(){previousBind.call(this);let p=this.g.s.player,save=()=>this.g.persist('skill-settings');document.querySelectorAll('[data-attack-skill]').forEach(x=>x.onchange=()=>{let n=x.dataset.attackSkill,a=p.activeSkillSettings.attack;p.activeSkillSettings.attack=x.checked?[...new Set([...a,n])]:a.filter(v=>v!==n);save()});document.querySelectorAll('[data-heal-skill]').forEach(x=>x.onchange=()=>{let selected=[p.activeSkillSettings.heal].flat().filter(Boolean),n=x.dataset.healSkill;p.activeSkillSettings.heal=x.checked?[...new Set([...selected,n])]:selected.filter(v=>v!==n);save()});let set=(id,key)=>{let x=document.querySelector(id);if(x)x.onchange=()=>{p.activeSkillSettings[key]=Math.max(1,Math.min(99,+x.value||1));save()}};set('#skill-heal-threshold','healThreshold');set('#soul-mp','soulMpBelow');set('#soul-hp','soulHpAbove');let soul=document.querySelector('#auto-soul');if(soul)soul.onchange=()=>{p.activeSkillSettings.resource??={};p.activeSkillSettings.resource['魂體轉換']=soul.checked;save()}};
