import{UI}from'./ui.js?v=27';import{derived}from'./player.js?v=27';import{chance}from'./enhance.js?v=27';import{skillsFor,skillSourceDetails,skillTier}from'./skills.js?v=27';import{SUMMON_TYPES,PET_TYPES}from'./systems.js?v=27';import{summonStatus}from'./companions.js?v=27';import{statText,itemSource,BOSS_PET_FORMS,PET_STONES}from'./content-v13.js?v=28';

UI.prototype.bag=function(p){let gear=p.bag.filter(x=>x.kind!=='book'),books=p.bag.filter(x=>x.kind==='book'),stacks=Object.entries(p.consumables).filter(([,n])=>n>0);return`<section class="panel"><h2>裝備 ${gear.length} 件</h2><div class="cards" id="inventory-cards">${gear.map(i=>`<button class="card" data-instance-id="${i.instanceId||i.uid}"><b>+${i.enhance} ${i.name}</b><br><small>${i.slot}${statText(i)?`・${statText(i)}`:''}</small></button>`).join('')||'沒有裝備'}</div><h2>消耗品／箭矢</h2><div class="cards">${stacks.map(([n,c])=>`<button class="card" data-stack="${n}"><b>${n} ×${c}</b></button>`).join('')}</div><h2>技能書</h2>${books.map(b=>`<button class="card" data-book="${b.uid}"><b>${b.name} ×${b.count}</b></button>`).join('')||'尚無技能書'}<h2>寵物進化材料</h2><p>${PET_STONES.normal} ×${p.petMaterials?.[PET_STONES.normal]||0}・${PET_STONES.advanced} ×${p.petMaterials?.[PET_STONES.advanced]||0}</p><h2>Boss材料</h2><div class="cards">${Object.entries(p.bossMaterials).filter(([,n])=>n).map(([n,c])=>`<div class="card"><b>${n} ×${c}</b></div>`).join('')||'尚無材料'}</div></section>`};

UI.prototype.item=function(i){if(i)this.itemByInstanceId(i.instanceId||i.uid)};

UI.prototype.itemByInstanceId=function(id){let p=this.g.s.player,i=p.bag.find(x=>(x.instanceId||x.uid)===id);if(!i)return this.g.ui?.toast?.('物品已變更，背包已重新整理。');let risky=i.enhance>=i.safe,stats=statText(i),src=itemSource(i);this.modal.innerHTML=`<div class="modal"><h2>+${i.enhance} ${i.name}</h2><p>${i.slot==='武器'?`小型/大型 ${i.small}/${i.large}・${i.type}`:`AC ${i.ac??0}`}・安定值 +${i.safe??0}${stats?`<br>${stats}`:''}${src?`<br>來源：${src.map}${src.floor?` ${src.floor}F`:''}<br>${src.boss?`Boss：${src.boss}`:`怪物：${src.monster}`}・${src.rarity}`:''}</p><div class="actions"><button data-item-action="equip">裝備</button><button data-item-action="sell" ${i.protected||i.enhance?'disabled':''}>出售</button><button data-item-action="enhance" class="${risky?'danger':''}">${risky?'【危險強化】':''}目標 +${i.enhance+1}（${Math.round(chance(i)*100)}%）</button><button data-item-action="close">關閉</button></div></div>`;this.modal.onclick=e=>{let action=e.target.closest('[data-item-action]')?.dataset.itemAction;if(!action)return;let live=this.g.s.player.bag.find(x=>(x.instanceId||x.uid)===id);if(action==='close')this.modal.innerHTML='';else if(!live){this.modal.innerHTML='';this.g.ui.toast('物品已變更，請重新開啟背包。')}else if(action==='equip'){this.modal.innerHTML='';this.g.equip(id)}else if(action==='sell'){this.modal.innerHTML='';this.g.sell(id)}else if(action==='enhance')this.g.enhance(id,risky)}};

const priorMore=UI.prototype.more;UI.prototype.more=function(p){let html=priorMore.call(this,p),d=derived(p),sources=skillsFor(p).map(s=>`<div class="card"><b>${s[0]}・${skillTier(s)}</b><br><small>${p.cls}・需求 Lv.${s[1]}・${s[2]}<br>${skillSourceDetails(s).map(x=>`${x.map}${x.floor?` ${x.floor}F`:''}：${x.boss?`Boss ${x.boss}`:x.monster}`).join('<br>')}</small></div>`).join(''),summons=p.cls==='法師'?SUMMON_TYPES.map(x=>{let st=summonStatus(p,x.id);return`<button class="card" data-summon="${x.id}" ${st.ok?'':'disabled'}><b>${x.name}</b><br><small>需要等級 ${x.level}・需要 CHA ${x.requiredCha}<br>目前 CHA ${st.currentCha}・${x.ring?'額外需求：召喚控制戒指<br>':''}狀態：${st.ok?'可召喚':st.reasons.join('、')}</small></button>`}).join(''):'僅法師可使用召喚',pets=p.pets.map(pet=>{let stage=pet.evolution||0,next=stage===0?`${PET_STONES.normal} ×5`:stage===1?`${PET_STONES.advanced} ×3`:null,finals=stage>=2&&!pet.bossForm?BOSS_PET_FORMS.map(f=>`<button data-boss-evolve="${pet.uid}|${f.id}" ${(p.bossMaterials[f.material]||0)<1?'disabled':''}>最終進化：${f.name}（${f.role}）・${f.material} ×1</button>`).join(''):'';return`<div class="card"><b>${pet.name} Lv.${pet.level}</b><br><small>${p.activePets.includes(pet.uid)?'出戰中':'待命'}・一般寵物格，不使用 CHA</small>${next?`<button data-evolve="${pet.uid}">進化：${next}</button>`:''}${finals}</div>`}).join('');html=html.replace('<h2>設定與存檔</h2>',`<h2>技能書來源</h2>${sources}<h2>召喚資訊</h2><p>最終 CHA：${d.stats.cha}</p>${summons}<h2>寵物進化</h2><p>一般進化石由各難度普通怪掉落；最終進化才消耗稀有 Boss 材料。</p>${pets}<h2>召喚控制戒指</h2><div class="card"><b>召喚控制戒指・CHA +2</b><br><small>來源：傲慢之塔中層・Boss 騎士范德・極稀有</small></div><h2>設定與存檔</h2>`);return html};

const priorBind=UI.prototype.bind;UI.prototype.bind=function(){priorBind.call(this);document.querySelectorAll('#inventory-cards [data-instance-id]').forEach(card=>card.onclick=()=>this.itemByInstanceId(card.dataset.instanceId));document.querySelectorAll('[data-boss-evolve]').forEach(boss=>boss.onclick=()=>{let[uid,form]=boss.dataset.bossEvolve.split('|');this.g.evolveBoss(uid,form)})};


const priorOffline=UI.prototype.offline;UI.prototype.offline=function(o){priorOffline.call(this,o);let claim=this.modal.querySelector('#claim'),row=document.createElement('p');row.innerHTML=`寵物材料：${Object.entries(o.petEvolutionMaterials||{}).map(([k,v])=>`${k} ×${v}`).join('・')||'0'}`;claim.parentNode.insertBefore(row,claim)};
