import{UI}from'./ui.js?v=38';
import{groupEquipment,quickSellPreview,sellInstances}from'./inventory.js?v=44';
import{BOSS_SETS}from'./systems.js?v=38';
import{statText,itemSource,PET_STONES}from'./content-v13.js?v=38';
const money=n=>Math.floor(n).toLocaleString('zh-TW');
const danger=i=>i.protected||i.boss||i.bossSet||(i.enhance||0)>0||(i.rarity||'普通')!=='普通'||i.special||i.summonControl||Object.values(i.statBonuses||{}).some(Boolean);
UI.prototype.bag=function(p){let groups=groupEquipment(p.bag),books=p.bag.filter(x=>x.kind==='book'),stacks=Object.entries(p.consumables).filter(([,n])=>n>0),preview=quickSellPreview(p);return`<section class="panel"><div class="row"><h2>裝備 ${p.bag.filter(x=>x.kind!=='book').length} 件・${groups.length} 組</h2><button id="quick-sell-preview" ${preview.count?'':'disabled'}>一鍵出售普通裝備</button></div><div class="cards">${groups.map((g,n)=>`<button class="card" data-group-index="${n}"><b>+${g.item.enhance||0} ${g.item.name} ×${g.count}</b><br><small>${g.item.rarity||'普通'}・${g.item.slot}・單件 ${money(g.unitPrice)}／整組 ${money(g.totalPrice)}</small></button>`).join('')||'沒有裝備'}</div><h2>消耗品／箭矢</h2><div class="cards">${stacks.map(([n,c])=>`<button class="card" data-stack="${n}"><b>${n} ×${c}</b></button>`).join('')}</div><h2>技能書</h2>${books.map(b=>`<button class="card" data-book="${b.uid}"><b>${b.name} ×${b.count}</b></button>`).join('')||'尚無技能書'}<h2>寵物進化材料</h2><p>${PET_STONES.normal} ×${p.petMaterials?.[PET_STONES.normal]||0}・${PET_STONES.advanced} ×${p.petMaterials?.[PET_STONES.advanced]||0}</p></section>`};
UI.prototype.equipmentGroup=function(index){let p=this.g.s.player,g=groupEquipment(p.bag)[index];if(!g)return this.render();let i=g.item,src=itemSource(i),set=BOSS_SETS.find(x=>x.id===i.bossSet),worn=set?Object.values(p.equipment).filter(x=>x?.bossSet===set.id).length:0,ids=g.items.map(x=>x.instanceId||x.uid),details=`${i.slot==='武器'?`小型/大型 ${i.small}/${i.large}・${i.type}`:`AC ${i.ac??0}`}・安定 +${i.safe??0}${statText(i)?`<br>${statText(i)}`:''}${src?`<br>來源：${src.map}${src.floor?` ${src.floor}F`:''}・${src.boss?'Boss '+src.boss:src.monster}・${src.rarity}`:''}${set?`<br>套裝：${set.name}（已穿 ${worn}/${set.pieces.length}）<br>2件：${JSON.stringify(set.effects[2])}<br>3件：${JSON.stringify(set.effects[3])}<br>全套：${JSON.stringify(set.effects[set.pieces.length])}<br>來源Boss：${set.boss}`:''}`;this.modal.innerHTML=`<div class="modal"><h2>+${i.enhance||0} ${i.name} ×${g.count}</h2><p>${details}</p><button data-a="equip">裝備</button><button data-a="one">賣1件</button><button data-a="all">全部賣出</button><button data-a="enhance">強化其中1件</button><button data-a="close">關閉</button></div>`;this.modal.onclick=e=>{let a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;if(a==='close')return this.modal.innerHTML='';if(a==='equip'){this.modal.innerHTML='';return this.g.equip(ids[0])}if(a==='enhance'){this.modal.innerHTML='';return this.g.enhance(ids[0],i.enhance>=i.safe)}let selected=a==='one'?[ids[0]]:ids;if(danger(i)&&!confirm(`此組包含稀有、強化或重要裝備，確定出售 ${selected.length} 件？`))return;let r=sellInstances(p,selected,{allowProtected:danger(i)});this.modal.innerHTML='';this.g.persist('sell-equipment-group');this.g.ui.toast(r.ok?`出售 ${r.count} 件裝備，獲得 ${r.gold} 金幣。`:'出售失敗。')}};
const oldBind=UI.prototype.bind;UI.prototype.bind=function(){oldBind.call(this);document.querySelectorAll('[data-group-index]').forEach(b=>b.onclick=()=>this.equipmentGroup(+b.dataset.groupIndex));let q=document.querySelector('#quick-sell-preview');if(q)q.onclick=()=>{let x=quickSellPreview(this.g.s.player);this.modal.innerHTML=`<div class="modal"><h2>一鍵出售普通裝備</h2><p>將出售：${x.count} 件裝備<br>預計獲得：${money(x.gold)} 金幣</p><button id="confirm-quick-sell">確認出售</button><button id="cancel-quick-sell">取消</button></div>`;this.modal.querySelector('#confirm-quick-sell').onclick=()=>{let r=sellInstances(this.g.s.player,x.ids);this.modal.innerHTML='';this.g.persist('quick-sell-equipment');this.g.ui.toast(r.ok?`出售 ${r.count} 件普通裝備，獲得 ${r.gold} 金幣。`:'沒有可出售的普通裝備。')};this.modal.querySelector('#cancel-quick-sell').onclick=()=>this.modal.innerHTML=''}};
