import{CLASS_AFFIXES,SPECIAL_AFFIXES,SETS,BOSS_LOOT}from'./v2-data.js?v=3';
export const SLOTS=['武器','頭盔','盔甲','手套','鞋子','項鍊','戒指1','戒指2'];export const QUALITY=['普通','優良','稀有','史詩','傳說','神話','永恆'];
const names={武器:['鐵劍','獵刃','戰槍','法杖'],頭盔:['皮帽','戰盔','星冠'],盔甲:['旅衣','鎖甲','魔紋袍'],手套:['護手','影手套'],鞋子:['長靴','疾風鞋'],項鍊:['月牙墜','靈魂鍊'],戒指1:['銀戒','符文戒'],戒指2:['銀戒','符文戒']},pre=['破舊','堅韌','狼牙','暗影','赤焰','星辰','神話','永恆'];
export const DROP_RATES=[.55,.30,.115,.029,.0052,.00075,.00005];
export function power(i){if(!i)return 0;let aff=(i.affixes||[]).reduce((n,a)=>n+a.value*({crit:35,speedPct:12,dropPct:8,rareFind:7,lifesteal:15,skillDamage:11,bossDamage:10}[a.key]||4),0),special=(i.special?250:0)+(i.setId?180:0)+(i.bossId?220:0);return Math.round(((i.atk||0)*5+(i.def||0)*3+(i.hp||0)*.3+(i.mp||0)*.2+(i.crit||0)*40+(i.hit||0)*2+(i.speed||0)*80+aff+special)*(1+(i.quality||0)*.025)*(1+(i.enhance||0)*.035))}
export function rollQuality(luck=0,rng=Math.random){let r=rng()/(1+Math.min(.65,luck));let sum=0;for(let q=6;q>=0;q--){sum+=DROP_RATES[q];if(r<sum)return q}return 0}
function affixCount(q){let ranges=[[0,1],[1,1],[1,2],[2,3],[3,4],[4,5],[5,6]],r=ranges[q];return r[0]+Math.floor(Math.random()*(r[1]-r[0]+1))}
function affixes(q,level,cls){let pool=[['猛攻','atkPct'],['堅壁','defPct'],['活力','hpPct'],['精準','hit'],['致命','crit'],['迅捷','speedPct'],['經驗','expPct'],['聚財','goldPct'],['尋獲','dropPct']],out=[];if(q>=2&&CLASS_AFFIXES[cls]&&Math.random()<.35)pool.push(...CLASS_AFFIXES[cls].map(x=>[`${cls}・${x[0]}`,x[1],cls]));for(let n=affixCount(q);n--;){let a=q>=4&&Math.random()<.06?SPECIAL_AFFIXES[Math.floor(Math.random()*SPECIAL_AFFIXES.length)]:pool[Math.floor(Math.random()*pool.length)];out.push({name:a[0],key:a[1],class:a[2]||null,special:SPECIAL_AFFIXES.some(x=>x[0]===a[0]),value:+((1+q*.8+Math.random()*(2+level/80))).toFixed(1)})}return out}
export function rollItem(level,luck=0,force=-1,opt={}){let q=force>=0?force:rollQuality(luck),slot=opt.slot||SLOTS[Math.floor(Math.random()*SLOTS.length)],itemLevel=Math.max(1,Math.floor(level*(.9+Math.random()*.2))),base=Math.max(2,Math.floor(itemLevel*(.72+Math.random()*.65))),mult=[1,1.25,1.65,2.25,3.1,4.4,6.3][q],armor=['頭盔','盔甲','手套','鞋子'].includes(slot),jewel=slot.startsWith('戒指')||slot==='項鍊',item={id:Date.now().toString(36)+Math.random().toString(36).slice(2),slot,name:`${pre[Math.min(q+Math.floor(Math.random()*2),7)]}${names[slot][Math.floor(Math.random()*names[slot].length)]}`,quality:q,itemLevel,level:itemLevel,enhance:0,locked:q>=5,atk:slot==='武器'?Math.floor(base*mult):Math.max(armor?0:1,Math.floor(base*mult*.12)),def:armor?Math.max(1,Math.floor(base*mult*.65)):0,hp:Math.floor(base*mult*(q>=1?1.8:0)),mp:Math.floor(base*mult*(q>=2?.8:0)),crit:q>=2?+(q*.35+Math.random()).toFixed(1):0,hit:jewel?Math.max(1,Math.floor(q+Math.random()*Math.max(1,q))):0,speed:q>=3?+(q*.01).toFixed(2):0,affixes:affixes(q,itemLevel,opt.class),source:opt.source||'world',acquiredAt:Date.now(),isNew:true};if(opt.boss&&Math.random()<.32){let b=BOSS_LOOT.filter(x=>x.map===opt.map)[Math.floor(Math.random()*4)];Object.assign(item,{bossId:b.id,name:b.name,slot:b.slot,locked:true})}else if(opt.boss&&Math.random()<.38){let set=SETS[(opt.map+(Math.random()*3|0))%SETS.length];item.setId=set.id;item.name=`${set.name}${slot}`;item.locked=true}item.score=power(item);return item}
export function registerItem(p,item){p.drops[item.quality]=(p.drops[item.quality]||0)+1;p.v2stats.totalDrops++;p.v2stats.highestES=Math.max(p.v2stats.highestES,item.score);p.v2stats.rarest=Math.max(p.v2stats.rarest,item.quality);p.collection.items[item.name]=true;if(item.setId){p.collection.sets[item.setId]=true;p.v2stats.setDrops++}if(item.bossId){p.collection.bossLoot[item.bossId]=true;p.v2stats.bossDrops++}}
export function enhanceCost(i){return Math.floor((i.itemLevel+10)*120*Math.pow(i.enhance+1,1.65))}export function enhanceChance(n){return n<5?1:n<10?.9-(n-5)*.08:n<15?.48-(n-10)*.055:.19-(n-15)*.03}
