import{SETS}from'./v2-data.js?v=3';
export const CLASSES={'王族':[125,48,11,9,8,11,9,1,6,8,10],'騎士':[165,32,13,8,5,15,7,.88,5,13,9],'妖精':[105,52,8,15,9,9,10,1.18,8,7,15],'法師':[88,105,5,9,17,8,15,.92,5,5,12],'黑暗妖精':[100,45,13,16,7,9,8,1.22,12,6,14],'龍騎士':[150,38,16,8,6,13,7,1.02,7,10,10],'幻術士':[102,92,7,11,15,9,14,1.05,7,7,13]};
export function newPlayer(name,cls){let c=CLASSES[cls];return{name,class:cls,level:1,exp:0,gold:100,potions:15,hp:c[0],mp:c[1],base:{hp:c[0],mp:c[1],str:c[2],dex:c[3],int:c[4],con:c[5],wis:c[6],speed:c[7],crit:c[8],def:c[9],hit:c[10]},equipment:{},inventory:[],map:0,killsOnMap:0,totalKills:0,bossKills:0,deaths:0,rebirths:0,highestDamage:0,highestCrit:0,playSeconds:0,offlineSeconds:0,totalGold:100,drops:[0,0,0,0,0,0,0],achievements:[],settings:{potion:50,autoSell:[false,false,false],autoDecompose:[false,false,false,false],skillOrder:[],bagSort:'score',bagFilter:'all'},materials:{iron:0,crystal:0,essence:0,greater:0,eternal:0},forge:{level:1,exp:0,total:0},collection:{items:{},bossLoot:{},sets:{},milestones:[]},bossCodex:{},firstKillBonuses:{atk:0,hp:0,exp:0,gold:0,drop:0},tower:{highest:0,current:1,attempts:0,bossKills:0,fastest:null,highestDamage:0},v2stats:{totalDrops:0,setDrops:0,bossDrops:0,decomposed:0,forged:0,rerolled:0,highestES:0,rarest:0}}}
export function expNeed(l){return Math.floor(48*Math.pow(l,1.72)*(1+Math.max(0,l-50)/180))}
export function gearStats(p){let s={atk:0,def:0,hp:0,mp:0,crit:0,hit:0,speed:0,atkPct:0,defPct:0,hpPct:0,mpPct:0,speedPct:0,critDamage:0,dodge:0,lifesteal:0,bossDamage:0,skillDamage:0,dropPct:0,rareFind:0,expPct:0,goldPct:0,penetration:0,reduction:0,bossReduction:0,doubleHit:0,cooldown:0,undying:0},setCounts={};Object.values(p.equipment).filter(Boolean).forEach(i=>{['atk','def','hp','mp','crit','hit','speed'].forEach(k=>s[k]+=i[k]||0);(i.affixes||[]).filter(a=>!a.class||a.class===p.class).forEach(a=>s[a.key]=(s[a.key]||0)+a.value);if(i.setId)setCounts[i.setId]=(setCounts[i.setId]||0)+1});for(let[id,n]of Object.entries(setCounts)){let set=SETS.find(x=>x.id===id);if(!set||set.class&&set.class!==p.class)continue;for(let pieces of[2,4,6])if(n>=pieces)Object.entries(set.effects[pieces]).forEach(([k,v])=>s[k]=(s[k]||0)+v)}s.setCounts=setCounts;return s}
export function stats(p){let g=gearStats(p),r=p.rebirths,b=p.firstKillBonuses||{},dropRaw=g.dropPct+(b.drop||0)+r*2;return{maxHp:Math.floor((p.base.hp+p.level*(8+p.base.con*.42)+g.hp)*(1+r*.1+(b.hp||0)/100+g.hpPct/100)),maxMp:Math.floor((p.base.mp+p.level*(2+p.base.wis*.2)+g.mp)*(1+g.mpPct/100)),atk:Math.floor((p.base.str*2+p.base.int*1.25+p.level*2.2+g.atk)*(1+r*.1+(b.atk||0)/100+g.atkPct/100)),def:Math.floor((p.base.def+p.base.con*.7+p.level*1.15+g.def)*(1+g.defPct/100)),hit:Math.floor(p.base.hit+p.base.dex*.6+p.level*.22+g.hit),crit:Math.min(75,p.base.crit+p.base.dex*.12+g.crit),critDmg:Math.min(3,1.65+g.critDamage/100),speed:Math.min(5,(p.base.speed+g.speed)*(1+g.speedPct/100)),dodge:Math.min(45,g.dodge),lifesteal:Math.min(20,g.lifesteal),bossDamage:Math.min(100,g.bossDamage),skillDamage:Math.min(100,g.skillDamage),dropBonus:Math.min(.75,1-Math.exp(-dropRaw/100)),rareFind:Math.min(50,g.rareFind),expBonus:r*.05+(b.exp||0)/100+g.expPct/100,goldBonus:(b.gold||0)/100+g.goldPct/100,penetration:Math.min(60,g.penetration),reduction:Math.min(65,g.reduction),bossReduction:Math.min(50,g.bossReduction),doubleHit:Math.min(40,g.doubleHit),cooldown:Math.min(40,g.cooldown),undying:Math.min(20,g.undying),setCounts:g.setCounts,power:0}}
export function recalc(p){let s=stats(p);s.power=Math.floor(s.atk*5+s.def*3+s.maxHp*.3+s.maxMp*.15+s.hit*2+s.crit*30+s.speed*100+s.bossDamage*15+s.skillDamage*12+s.dropBonus*800);return s}
export function addExp(p,n){let levels=0,s=stats(p);p.exp+=Math.floor(n*(1+s.expBonus));while(p.level<999&&p.exp>=expNeed(p.level)){p.exp-=expNeed(p.level);p.level++;levels++}return levels}
export function analyzeBuild(p){let s=stats(p),c=[['暴擊流',s.crit*3],['高速連擊流',s.speed*35+s.doubleHit],['技能流',s.skillDamage+s.cooldown],['坦克流',s.maxHp/200+s.def/10],['Boss流',s.bossDamage*2],['尋寶流',s.dropBonus*180+s.rareFind]];return c.sort((a,b)=>b[1]-a[1])[0][0]}
