import assert from'node:assert/strict';import{migrate}from'../js/migration.js';import{CLASSES,MAPS,ITEMS,BOSS_DATA,WORLD_BOSSES,TRANSFORMS,DOLLS,CONSUMABLES,SPECIAL_WEAPONS}from'../js/data.js';import{createPlayer,derived,weight}from'../js/player.js';import{canEquip,equip,addItem,sell}from'../js/inventory.js';import{buy,supply}from'../js/shop.js';import{enemyFor,hitChance,weaponDamage,Combat}from'../js/combat.js';import{enhance}from'../js/enhance.js';import{craft,recipes}from'../js/crafting.js';import{fightWorldBoss}from'../js/world-boss.js';import{calculateOffline,claimOffline}from'../js/offline.js';
assert.equal(Object.keys(CLASSES).length,7);assert.equal(MAPS.length,10);assert.equal(MAPS.flatMap(m=>m.monsters).length,50);assert.equal(BOSS_DATA.length,10);assert.equal(WORLD_BOSSES.length,3);assert.ok(ITEMS.length>=20);assert.equal(TRANSFORMS.length,12);assert.equal(DOLLS.length,9);assert.equal(SPECIAL_WEAPONS.length,7);
for(let c of Object.keys(CLASSES)){let p=createPlayer('測試',c);assert.equal(p.cls,c);assert.ok(derived(p).maxHp>0)}let p=migrate({player:createPlayer('騎士','騎士'),logs:[]}).player;p.gold=1e6;assert.ok(buy(p,'紅色藥水',10));assert.equal(p.consumables.紅色藥水,70);let sword=ITEMS.find(i=>i.id==='長劍'),shield=ITEMS.find(i=>i.id==='圓盾'),great=ITEMS.find(i=>i.id==='巨劍');addItem(p,sword);assert.ok(equip(p,p.bag[0].uid));addItem(p,shield);assert.ok(equip(p,p.bag[0].uid));addItem(p,great);assert.ok(equip(p,p.bag.find(i=>i.id==='巨劍').uid));assert.equal(p.equipment.盾牌,undefined);assert.ok(!canEquip(createPlayer('法','法師'),great));assert.ok(weaponDamage(p,{size:'Large'},()=>.9)>weaponDamage(p,{size:'Small'},()=>.1));assert.ok(hitChance(30,-20,20)>hitChance(10,-20,20));assert.ok(hitChance(20,-20,20)<hitChance(20,5,20));let armor=ITEMS.find(i=>i.id==='皮甲');addItem(p,armor);equip(p,p.bag.find(i=>i.id==='皮甲').uid);assert.ok(derived(p).ac<10);
let beforeW=weight(p).current;buy(p,'紅色藥水',20);assert.equal(weight(p).current,beforeW);let state={player:p,logs:[]},c=new Combat(state,()=>{});p.inTown=false;c.start();assert.ok(c.enemy);p.hp=1;c.autoPotion();assert.ok(p.hp>1);p.consumables.紅色藥水=p.consumables.橙色藥水=p.consumables.白色藥水=0;p.hp=0;c.die();assert.ok(p.inTown&&p.lostExp>=0);
let trash=ITEMS.find(i=>i.id==='皮帽');addItem(p,trash);let id=p.bag.at(-1).uid;assert.ok(sell(p,id));let protectedItem={...sword,name:'王劍',boss:true,protected:true};addItem(p,protectedItem,true);assert.equal(sell(p,p.bag.at(-1).uid),false);
let safe={...sword,uid:'safe',enhance:0};p.bag.push(safe);p.consumables.武器強化卷軸=10;for(let i=0;i<6;i++)assert.ok(enhance(p,'safe',false,()=>0).ok);let doomed={...sword,uid:'doom',enhance:6};p.bag.push(doomed);let er=enhance(p,'doom',false,()=>1);assert.ok(er.destroyed&&!p.bag.some(i=>i.uid==='doom'));let blessed={...sword,uid:'bless',enhance:0};p.bag.push(blessed);p.consumables.祝福武器強化卷軸=1;assert.ok(enhance(p,'bless',true,()=>.9).add>=1);
let r=recipes()[0];p.gold=1e9;p.bossMaterials[Object.keys(r.requirements)[0]]=99;assert.ok(craft(p,r.id));
p.level=99;p.stats.str=500;p.stats.con=500;p.consumables.白色藥水=50000;let wr=fightWorldBoss(p,'dragon',()=>0);assert.ok(wr.win&&p.worldMaterials.黑龍之心>0);let oldHigh=p.statsLog.kills;p.inTown=false;p.gold=1e9;p.settings.autoSupply=true;let offState={player:p,lastOnlineTimestamp:Date.now()-8*3600e3,pendingOffline:null},o=calculateOffline(offState);assert.ok(o&&o.kills>0&&o.sec===28800);claimOffline(offState,o);assert.ok(p.statsLog.kills>oldHigh&&offState.pendingOffline===null);
console.log('天堂文字版 V1 smoke tests passed');
