import assert from'node:assert/strict';import{createPlayer}from'../js/player.js';import{migrate}from'../js/migration.js';import{emptyRoster,wrapLegacy,normalizeRoster,addCharacter,removeCharacter,offlineSeconds,MAX_CHARACTERS}from'../js/multi-character.js';import{calculateOffline,claimOffline}from'../js/offline.js';import{ITEMS}from'../js/data.js';
let n=0,ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.equal(a,b,m);n++},now=2_100_000_000_000;
let old=migrate({saveVersion:9,createdAt:123,lastOnlineTimestamp:now-3600000,logs:[],player:createPlayer('舊勇者','妖精')});old.player.level=37;old.player.gold=987654;old.player.consumables.銀箭=2345;old.player.settings.arrowType='銀箭';old.player.settings.autoTransform=true;old.player.bossMaterials.狼王之牙=8;old.player.pets[0].level=22;old.player.activePets=[old.player.pets[0].uid];old.player.bag.push({...ITEMS[0],uid:'legacy-gear',enhance:7});let migrated=wrapLegacy(old,now);eq(migrated.saveVersion,10);eq(migrated.characters.length,7);eq(migrated.characters[0].state.player.level,37);eq(migrated.characters[0].state.player.gold,987654);eq(migrated.characters[0].state.player.consumables.銀箭,2345);eq(migrated.characters[0].state.player.settings.autoTransform,true);eq(migrated.characters[0].state.player.bag[0].enhance,7);eq(migrated.characters[0].state.player.pets[0].level,22);ok(migrated.multiCharacterMigration);
let again=normalizeRoster(migrated,old,now);eq(again.characters.filter(Boolean).length,1,'migration只執行一次');eq(again.characters[0].state.player.name,'舊勇者');
let roster=emptyRoster();for(let i=0;i<7;i++)ok(addCharacter(roster,`角色${i}`,i<2?'妖精':'騎士',i,now));eq(roster.characters.filter(Boolean).length,MAX_CHARACTERS);eq(addCharacter(roster,'第八隻','法師',0,now),null);eq(addCharacter(emptyRoster(),'','法師',0,now),null);let dup=emptyRoster();ok(addCharacter(dup,'同名','妖精',0,now));eq(addCharacter(dup,'同名','妖精',1,now),null);let twoElf=emptyRoster();ok(addCharacter(twoElf,'妖精甲','妖精',0,now));ok(addCharacter(twoElf,'妖精乙','妖精',1,now));
let a=roster.characters[0].state.player,b=roster.characters[1].state.player,c=roster.characters[2].state.player;a.gold=10000;b.gold=500;a.consumables.銀箭=2000;b.consumables.銀箭=0;a.settings.arrowType='銀箭';b.settings.arrowType=null;a.bag.push({uid:'only-a',name:'A裝',slot:'頭盔',enhance:3});a.skillBooks.魂體轉換=2;a.bossMaterials.狼王之牙=9;a.pets[0].level=30;a.settings.autoTransform=true;b.settings.autoTransform=false;a.settings.autoSupply=false;b.settings.autoSupply=true;eq(b.gold,500);eq(b.consumables.銀箭,0);eq(b.bag.some(x=>x.uid==='only-a'),false);eq(b.skillBooks.魂體轉換||0,0);eq(b.bossMaterials.狼王之牙||0,0);eq(b.pets[0].level,1);eq(b.settings.autoTransform,false);eq(b.settings.autoSupply,true);
roster.characters[0].state.lastOnlineTimestamp=now-1800e3;roster.characters[1].state.lastOnlineTimestamp=now-1200e3;roster.characters[2].state.lastOnlineTimestamp=now-600e3;eq(offlineSeconds(roster.characters[0],now),1800);eq(offlineSeconds(roster.characters[1],now),1200);eq(offlineSeconds(roster.characters[2],now),600);roster.characters[3].state.lastOnlineTimestamp=now-25*3600e3;eq(offlineSeconds(roster.characters[3],now),86400);
for(let i=0;i<3;i++){let s=roster.characters[i].state;s.player.inTown=false;s.player.map=0;s.player.gold=1e7;s.player.settings.autoGreen=false;s.player.settings.autoBrave=false;let report=calculateOffline(s,now,()=>.5);eq(report.sec,[1800,1200,600][i]);ok(report.kills>0);let otherTimes=roster.characters.map(x=>x?.state.lastOnlineTimestamp);claimOffline(s,report);for(let j=0;j<3;j++)if(j!==i)eq(roster.characters[j].state.lastOnlineTimestamp,otherTimes[j])}
let removedName=roster.characters[1].state.player.name,keepGold=roster.characters[0].state.player.gold,id=roster.characters[1].id;ok(removeCharacter(roster,id));eq(roster.characters[1],null);eq(roster.characters[0].state.player.gold,keepGold);ok(addCharacter(roster,'重建角色','法師',1,now));eq(roster.characters[1].state.player.level,1);eq(roster.characters[1].state.player.bag.length,0);ok(roster.characters[1].state.player.name!==removedName);
console.log(`V10 ${n} checks passed`);
