import assert from'node:assert/strict';import{createPlayer,derived}from'../js/player.js';import{migrate}from'../js/migration.js';import{Combat,hitChance}from'../js/combat.js';import{skillsFor}from'../js/skills.js';import{calculateOffline,claimOffline}from'../js/offline.js';import{classWeaponPool}from'../js/loot.js';import{equipmentDrop,mapFor}from'../js/hunting.js';import{addItem,equip}from'../js/inventory.js';import{togglePet,companionHits}from'../js/companions.js';import{PET_CLASS_LIMIT,speedBuff}from'../js/balance.js';
let n=0,ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.equal(a,b,m);n++};const rngFor=seed=>()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};
function runtimeBooks(kills,seed){let p=migrate({player:createPlayer('正式掉落','法師'),logs:[]}).player;p.level=34;p.inTown=false;p.map=1;p.debug={dropTrace:[]};let state={player:p,logs:[]},combat=new Combat(state),rng=rngFor(seed),old=Math.random;Math.random=rng;try{for(let i=0;i<kills;i++){combat.enemy={id:'h1-妖魔法師',name:'妖魔法師',level:6,hp:0,maxHp:30,ac:8,atk:1,hit:1,exp:0,gold:0,size:'Small'};combat.win()}}finally{Math.random=old}return{books:p.bag.filter(x=>x.kind==='book').reduce((a,x)=>a+x.count,0),bag:p.bag,trace:p.debug.dropTrace}}
let runtimeResults={};for(let[k,s]of[[500,11],[1000,22],[5000,33]]){let r=runtimeBooks(k,s);runtimeResults[k]=r.books;ok(r.books>0,`${k}正式擊殺有技能書`);ok(r.bag.some(x=>x.kind==='book'));ok(r.trace.some(x=>x.inventoryAfter>x.inventoryBefore));ok(r.trace.every(x=>x.monsterId&&x.playerClass==='法師'))}
let savePlayer=migrate({player:createPlayer('存檔追蹤','妖精'),logs:[]}).player;savePlayer.settings.autoTransform=true;let json=JSON.stringify(savePlayer),read=JSON.parse(json);eq(savePlayer.settings.autoTransform,true);ok(json.includes('"autoTransform":true'));eq(read.settings.autoTransform,true);
let buff=migrate({player:createPlayer('BUFF','騎士'),logs:[]}).player,now=Date.now(),base=derived(buff).speed;buff.buffs.greenUntil=now+300000;let green=derived(buff).speed;buff.buffs.braveUntil=now+300000;let both=derived(buff).speed;ok(green>base);ok(both>green);eq(speedBuff(buff,now),1.5);let skillCd=skillsFor(buff)[0][5];derived(buff);eq(skillsFor(buff)[0][5],skillCd);
let offlineResults={};for(let hours of[1,6,24]){let p=migrate({player:createPlayer(`離線${hours}`,'法師'),logs:[]}).player;p.level=30;p.map=1;p.inTown=false;p.gold=1e8;p.settings.autoGreen=false;p.settings.autoBrave=false;let end=2_200_000_000_000,state={player:p,lastOnlineTimestamp:end-hours*3600e3,logs:[]},report=calculateOffline(state,end,rngFor(hours));ok(report.kills>0);ok(report.dropTrace.totalDropRolls>0);ok(report.gear.length>0);ok(report.lootConsumables.紅色藥水>0);let before=p.bag.length;claimOffline(state,report);ok(p.bag.length>before);offlineResults[hours]={kills:report.kills,dropRolls:report.dropTrace.totalDropRolls,gear:report.gear.length,books:report.books.length,materials:Object.values(report.materials).reduce((a,b)=>a+b,0)}}
let progression={};for(let cls of['王族','騎士','妖精','法師','黑暗妖精','龍騎士','幻術士']){let p=migrate({player:createPlayer(cls,cls),logs:[]}).player,pool=classWeaponPool(cls),rng=rngFor(cls.length*97),drops=[];p.level=30;for(let mapId of[5,6,7,8,9])for(let i=0;i<300;i++){let item=equipmentDrop(p,mapFor(mapId),rng);if(item?.slot==='武器')drops.push(item)}ok(drops.length>=3,`${cls}中階武器比較機會`);ok(drops.every(x=>!x.classes||x.classes.includes(cls)));progression[cls]=drops.length;let weapon=pool[0];addItem(p,weapon);equip(p,p.bag.find(x=>x.name===weapon.name).uid);if(weapon.type==='弓'){p.settings.arrowType='木箭';p.consumables.木箭=999}let unbuffed=derived(p).speed;p.buffs.greenUntil=Date.now()+300000;p.buffs.braveUntil=Date.now()+300000;ok(derived(p).speed>unbuffed);p.buffs.greenUntil=p.buffs.braveUntil=0;let d=derived(p);ok(d.speed>0);ok(hitChance(weapon.hit+p.level+15,5,p.level)>.8);p.inTown=false;p.settings.autoGreen=false;p.settings.autoBrave=false;let combatState={player:p,logs:[]},combat=new Combat(combatState),hp=p.hp,oldRandom=Math.random;combat.enemy={name:'同級測試怪',level:30,hp:999,maxHp:999,ac:5,atk:5,hit:20,exp:1,gold:1,size:'Small'};Math.random=()=>.1;try{combat.tick(2)}finally{Math.random=oldRandom}ok(combatState.logs.some(x=>/你造成/.test(x.t)),`${cls}正式普通攻擊`);ok(combatState.logs.some(x=>/對你造成/.test(x.t)),`${cls}受到傷害流程`);let report=calculateOffline({player:p,lastOnlineTimestamp:1_000_000},3_601_000,rng);ok(report.kills>0);ok(report.gear.length>0);let pets=Array.from({length:PET_CLASS_LIMIT[cls]},(_,i)=>({uid:`${cls}${i}`,type:'dog',name:`狗${i}`,level:5,exp:0,hp:70,alive:true,evolution:0,evolutionMultiplier:1}));p.pets=pets;p.activePets=[];p.stats.cha=1;pets.forEach(x=>togglePet(p,x.uid));eq(companionHits(p).filter(x=>x.name.startsWith('狗')).length,PET_CLASS_LIMIT[cls])}
console.log(JSON.stringify({suite:'V11 runtime',checks:n,runtimeBooks:runtimeResults,offline:offlineResults,midGear:progression}));
