import assert from'node:assert/strict';
import{createPlayer,derived}from'../js/player.js';
import{migrate}from'../js/migration.js';
import{normalizeCharacterState,applyOfflineRewards,maintainSpeedPotions,buySpeedPotionTargets}from'../js/core-v12.js';
import{Combat}from'../js/combat.js?v=51';import'../js/runtime-v12.js';
import{ITEMS}from'../js/data.js';
import{addItem,equip,unequip,sell,ensureItemInstances}from'../js/inventory.js';
import{autoTransform}from'../js/transformations.js';
import{skillDrop,skillsFor,skillSources,selectActiveSkill,activeSkill}from'../js/skills.js';

let n=0,ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.equal(a,b,m);n++};
const player=(name='V12',cls='王族')=>normalizeCharacterState(migrate({player:createPlayer(name,cls),logs:[]})).player;

// 20 + 5 offline items, stable IDs, sequential operations and JSON reload.
let p=player('離線入庫','王族');for(let i=0;i<20;i++)addItem(p,{...ITEMS[i%ITEMS.length],name:`原裝${i}`});let reward={exp:0,petExp:0,net:0,kills:0,bosses:0,deaths:0,gross:0,cost:0,gear:Array.from({length:5},(_,i)=>({...ITEMS[0],name:`離線裝${i}`,slot:'頭盔',ac:-i,safe:4,price:100+i})),books:[],materials:{},purchased:{},consumed:{},lootConsumables:{}};let applied=applyOfflineRewards({player:p},reward);eq(applied.before,20);eq(applied.after,25);eq(new Set(applied.ids).size,5);ok(applied.ids.every(id=>p.bag.some(x=>x.uid===id&&x.instanceId===id)));for(let i=0;i<3;i++){ok(equip(p,applied.ids[i]),`裝備第${i+1}件`);ok(unequip(p,'頭盔'),`卸下第${i+1}件`)}ok(sell(p,applied.ids[3]));ok(p.bag.some(x=>x.uid===applied.ids[4]));let reloaded=JSON.parse(JSON.stringify(p));ensureItemInstances(reloaded);ok(applied.ids.filter(id=>id!==applied.ids[3]).every(id=>reloaded.bag.some(x=>x.uid===id)));ok(equip(reloaded,applied.ids[0]));let reloadEquipped=JSON.parse(JSON.stringify(reloaded));eq(reloadEquipped.equipment.頭盔.uid,applied.ids[0]);ok(applied.ids.filter(id=>![applied.ids[0],applied.ids[3]].includes(id)).every(id=>reloadEquipped.bag.some(x=>x.uid===id)));

// Online auto-buy, auto-use, renewal and actual speed.
let pot=player('加速閉環','騎士');pot.gold=100000;pot.consumables.綠色藥水=0;pot.consumables.勇敢藥水=0;pot.settings.target.綠色藥水=50;pot.settings.target.勇敢藥水=30;pot.settings.autoGreen=pot.settings.autoBrave=pot.settings.autoSupplyGreen=pot.settings.autoSupplyBrave=true;let gold0=pot.gold,buyResult=buySpeedPotionTargets(pot);eq(buyResult.bought.綠色藥水,50);eq(buyResult.bought.勇敢藥水,30);eq(gold0-pot.gold,50*300+30*900);let base=derived(pot).speed,use=maintainSpeedPotions(pot,1000);eq(use.used.length,2);eq(pot.consumables.綠色藥水,49);eq(pot.consumables.勇敢藥水,29);ok(derived({...pot,buffs:{greenUntil:Date.now()+1e6,braveUntil:Date.now()+1e6}}).speed>base);pot.buffs.greenUntil=pot.buffs.braveUntil=0;maintainSpeedPotions(pot,2000);eq(pot.consumables.綠色藥水,48);eq(pot.consumables.勇敢藥水,28);

// Transform execution and renewal trace.
let tr=player('變身鏈','騎士');tr.level=30;addItem(tr,{id:'sword-test',name:'測試劍',slot:'武器',type:'單手劍',small:8,large:8,hit:1,safe:6,classes:['騎士']});equip(tr,tr.bag[0].uid);tr.consumables.變身卷軸=10;tr.settings.autoTransform=true;tr.settings.autoTransformMode='fixed';tr.settings.autoTransformId='spartoi';let trBase=derived(tr).speed,now=100000;ok(autoTransform(tr,now));eq(tr.consumables.變身卷軸,9);eq(tr.transformState.id,'spartoi');eq(tr.debug.transformTrace.rejectReason,null);ok(tr.debug.transformTrace.consumeResult);ok(tr.transformState.until>now);tr.transformState.until=now-1;ok(autoTransform(tr,now));eq(tr.consumables.變身卷軸,8);ok(derived({...tr,transformState:{id:'spartoi',until:Date.now()+1e6}}).speed>trBase);

// Formal Combat.win path for prince and first-book eligibility for all classes.
let prince=player('王族死亡鏈','王族');prince.level=30;prince.inTown=false;prince.map=4;prince.debug={dropTrace:[]};let cs={player:prince,logs:[]},combat=new Combat(cs),oldRandom=Math.random;Math.random=()=>.00001;try{for(let i=0;i<400;i++){combat.enemy={id:'formal-'+i,name:'妖魔戰士',level:20,hp:0,maxHp:10,ac:0,atk:1,hit:1,exp:0,gold:0,size:'Small'};combat.win()}}finally{Math.random=oldRandom}let rolls=prince.debug.dropTrace.reduce((a,x)=>a+x.eligibleSkillBooks.length,0),success=prince.debug.dropTrace.flatMap(x=>x.eligibleSkillBooks).filter(x=>x.success).length;eq(prince.debug.dropTrace.length,400);ok(rolls>0);ok(success>0);ok(prince.bag.some(x=>x.kind==='book'));let princeReload=JSON.parse(JSON.stringify(prince));ok(princeReload.bag.some(x=>x.kind==='book'));
let firstSources={};for(let cls of['王族','騎士','妖精','法師','黑暗妖精','龍騎士','幻術士']){let q=player(cls,cls);q.level=20;q.debug={dropTrace:[]};let first=skillsFor(q).find(s=>s[1]<=20),source=skillSources(first)[0];skillDrop({id:'route',name:source},q,()=>.99,{mapId:0});let row=q.debug.dropTrace[0];ok(row.eligibleSkillBooks.length>0,`${cls} 前期第一本有正式 roll`);firstSources[cls]=`${row.eligibleSkillBooks[0].name} ← ${source}`}

// Mage selected active skill, combat log, MP fallback and persistence/isolation.
let mage=player('法師A','法師');mage.level=30;mage.learnedSkills=['光箭','火球','冰錐'];mage.activeSkillSettings.attack=['光箭','火球','冰錐'];mage.mp=999;ok(selectActiveSkill(mage,'火球'));eq(activeSkill(mage)[0],'火球');let ms={player:mage,logs:[]},mc=new Combat(ms);mc.enemy={name:'木人',level:1,hp:999,maxHp:999,ac:10,atk:0,hit:0,exp:0,gold:0,size:'Small'};mc.skillTick(mage,derived(mage));ok(ms.logs.some(x=>x.t.includes('火球')));mage.skillCooldowns.冰錐=0;ok(selectActiveSkill(mage,'冰錐'));mc.skillTick(mage,derived(mage));ok(ms.logs.some(x=>x.t.includes('冰錐')));let mageReload=JSON.parse(JSON.stringify(mage));eq(mageReload.activeSkillSettings.selectedActiveSkill,'冰錐');mage.mp=0;eq(activeSkill(mage),null);let mageB=player('法師B','法師');mageB.learnedSkills=['光箭'];mageB.activeSkillSettings.attack=['光箭'];selectActiveSkill(mageB,'光箭');eq(mageB.activeSkillSettings.selectedActiveSkill,'光箭');eq(mage.activeSkillSettings.selectedActiveSkill,'冰錐');

console.log(JSON.stringify({suite:'V12 core runtime',checks:n,offline:{before:applied.before,after:applied.after,ids:applied.ids.length},potions:{cost:buyResult.cost,green:pot.consumables.綠色藥水,brave:pot.consumables.勇敢藥水},transform:tr.debug.transformTrace,prince:{kills:400,eligibleSourceKills:prince.debug.dropTrace.filter(x=>x.eligibleSourceKills).length,rolls,success,inventoryAdds:prince.bag.filter(x=>x.kind==='book').reduce((a,x)=>a+x.count,0),reloadPersisted:princeReload.bag.filter(x=>x.kind==='book').reduce((a,x)=>a+x.count,0)},firstSources,selectedSkill:mageReload.activeSkillSettings.selectedActiveSkill}));
