import assert from'node:assert/strict';import{createPlayer,derived}from'../js/player.js';import{migrate}from'../js/migration.js';import{normalizeCharacterState,applyOfflineRewards}from'../js/core-v12.js';import{Combat}from'../js/combat.js?v=51';import'../js/runtime-v12.js';import'../js/runtime-v13.js';import{HUNTING_MAPS,SUMMON_TYPES}from'../js/systems.js';import{skillsFor,skillSourceDetails}from'../js/skills.js';import{CLASSIC_STAT_GEAR,BOSS_PET_FORMS,PET_STONE_RATE}from'../js/content-v13.js';import{addItem,equip}from'../js/inventory.js';import{summonStatus,evolvePet,evolvePetBoss,togglePet,companionAttack}from'../js/companions.js';import{calculateOffline}from'../js/offline.js';import{PET_CLASS_LIMIT}from'../js/balance.js';
let checks=0,ok=(v,m)=>{assert.ok(v,m);checks++},eq=(a,b,m)=>{assert.equal(a,b,m);checks++},make=(cls,name=cls)=>normalizeCharacterState(migrate({player:createPlayer(name,cls),logs:[]})).player,rngFor=seed=>()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};

let progression={};for(const [ci,cls]of['王族','騎士','妖精','法師','黑暗妖精','龍騎士','幻術士'].entries()){let p=make(cls),state={player:p,logs:[]},combat=new Combat(state),rng=rngFor(100+ci),old=Math.random,totalKills=0;Math.random=rng;p.inTown=false;p.debug={dropTrace:[]};try{for(const [from,to,mapIds]of[[1,20,[0,1,2,3]],[20,30,[4,5,6,7]],[30,40,[8,9,10,11]]])for(let level=from;level<to;level++){p.level=level;let map=HUNTING_MAPS[mapIds[(level-from)%mapIds.length]];p.map=map.id;for(let k=0;k<35;k++){let enemy=map.normals[k%map.normals.length];combat.enemy={...enemy,id:`${map.id}-${enemy.name}-${k}`,hp:0,maxHp:enemy.hp,atk:1,hit:1,size:'Small'};combat.win();totalKills++}}}finally{Math.random=old}let eligible=p.debug.dropTrace.filter(x=>x.eligibleSourceKills).length,rolls=p.debug.dropTrace.reduce((n,x)=>n+x.eligibleSkillBooks.length,0),books=p.bag.filter(x=>x.kind==='book').reduce((n,x)=>n+x.count,0);ok(eligible>totalKills*.2,`${cls}正常路線有來源`);ok(rolls>0);ok(books>0,`${cls} Lv40前可見技能書`);ok(skillSourceDetails(skillsFor(p)[0]).some(x=>x.mapId<=4));ok(skillsFor(p).filter(s=>s[1]>=20&&s[1]<=40).every(s=>skillSourceDetails(s).some(x=>x.mapId>=4)));progression[cls]={kills:totalKills,eligible,rolls,books}}

let mage=make('法師','能力召喚');mage.stats.cha=15;let ring=CLASSIC_STAT_GEAR.find(x=>x.id==='summon-ring'),amulet=CLASSIC_STAT_GEAR.find(x=>x.id==='cha-amulet');addItem(mage,ring);equip(mage,mage.bag[0].uid);eq(derived(mage).stats.cha,18);mage.level=60;mage.learnedSkills=['召喚術','高階召喚術'];let elder=SUMMON_TYPES.find(x=>x.id==='elder'),status17=summonStatus(mage,elder.id);eq(status17.currentCha,18);ok(!status17.ok);ok(status17.reasons.some(x=>x.includes('魅力不足 18/19')));addItem(mage,amulet);equip(mage,mage.bag[0].uid);let status18=summonStatus(mage,elder.id);eq(status18.currentCha,20);ok(status18.ok);ok(ring.source.boss==='騎士范德');

let petOwner=make('王族','寵物進化');let pet=petOwner.pets[0];pet.level=40;petOwner.petMaterials.寵物進化石=5;petOwner.petMaterials.高級寵物進化石=3;ok(evolvePet(petOwner,pet.uid));eq(petOwner.petMaterials.寵物進化石,0);ok(evolvePet(petOwner,pet.uid));eq(petOwner.petMaterials.高級寵物進化石,0);let preBossDps=companionAttack({...petOwner,activePets:[pet.uid]});petOwner.bossMaterials.死亡騎士之魂=1;ok(evolvePetBoss(petOwner,pet.uid,'death-knight'));eq(petOwner.bossMaterials.死亡騎士之魂,0);eq(pet.name,'死亡騎士');ok(companionAttack({...petOwner,activePets:[pet.uid]})>preBossDps);let other=make('妖精','自由Boss寵'),pet2=other.pets[0];pet2.level=40;pet2.evolution=2;other.bossMaterials.黑長者魔力核=1;ok(evolvePetBoss(other,pet2.uid,'black-elder'));eq(pet2.name,'黑長者');eq(other.bossMaterials.黑長者魔力核,0);other.stats.cha=1;ok(togglePet(other,pet2.uid));eq(other.activePets.length,1);eq(PET_CLASS_LIMIT.妖精,2);ok(BOSS_PET_FORMS.every(x=>!['安塔瑞斯','法利昂','林德拜爾','巴拉卡斯'].includes(x.name)));

let offline=make('騎士','離線進化石');offline.level=35;offline.map=9;offline.inTown=false;offline.gold=1e8;offline.settings.autoGreen=offline.settings.autoBrave=false;let now=4_000_000_000_000,report=calculateOffline({player:offline,lastOnlineTimestamp:now-24*3600e3},now,()=>.5);ok(report.petEvolutionMaterials.寵物進化石>0);ok(report.petEvolutionMaterials.高級寵物進化石>0);let before={...offline.petMaterials};applyOfflineRewards({player:offline},report);ok(offline.petMaterials.寵物進化石>before.寵物進化石);ok(PET_STONE_RATE(2).advanced===0&&PET_STONE_RATE(12).advanced>PET_STONE_RATE(5).advanced);

console.log(JSON.stringify({suite:'V13 progression equipment summon pet',checks,progression,finalCha:status18.currentCha,summon:status18.ok,bossPets:BOSS_PET_FORMS.map(x=>`${x.name}:${x.role}`),offlineStones:report.petEvolutionMaterials}));
