import assert from'node:assert/strict';import{CLASSES,ITEMS}from'../js/data.js';import{HUNTING_MAPS,BOSS_CATALOG,PET_EVOLUTIONS,controlCapacity}from'../js/systems.js';import{createPlayer,expNeed,derived,gainExp}from'../js/player.js';import{eligibleItems,rollEnemy}from'../js/hunting.js';import{migrate}from'../js/migration.js';import{recipes,recipeForClass}from'../js/crafting.js';import{evolvePet,petControl,companionAttack,togglePet}from'../js/companions.js';import{calculateOffline,claimOffline}from'../js/offline.js';
assert.equal(HUNTING_MAPS.length,18);assert.ok(HUNTING_MAPS.every(m=>m.id>=0));assert.ok(HUNTING_MAPS.some(m=>!m.mini&&!m.boss));assert.ok(HUNTING_MAPS.some(m=>m.mini&&!m.boss));assert.ok(HUNTING_MAPS.some(m=>!m.mini&&m.boss));assert.ok(HUNTING_MAPS.some(m=>m.tier>=14));assert.equal(BOSS_CATALOG.length,17);assert.equal(new Set(BOSS_CATALOG.map(b=>b.material)).size,17);
assert.deepEqual([1,10,20,30,40,50,60].map(expNeed),[77,700,4900,25900,119900,549900,3131506]);assert.ok(expNeed(20)>expNeed(10));assert.ok(expNeed(50)>expNeed(40)*4);let p=createPlayer('測試','騎士'),s=migrate({player:p});assert.equal(s.saveVersion,9);assert.equal(s.player.pets[0].evolution,0);assert.equal(petControl(s.player.pets[0]),2);
let pool=eligibleItems(p);assert.ok(pool.length);assert.ok(pool.filter(x=>x.slot==='武器').every(x=>CLASSES.騎士.weapon.includes(x.type)));let mage=createPlayer('法','法師');assert.ok(eligibleItems(mage).filter(x=>x.slot==='武器').every(x=>CLASSES.法師.weapon.includes(x.type)));assert.ok(eligibleItems(p).some(x=>x.slot!=='武器'));assert.equal(rollEnemy({...p,map:0},()=>.5).boss,undefined);assert.equal(rollEnemy({...p,map:2},()=>0).boss,true);
let knightRecipes=recipes().filter(r=>recipeForClass(p,r));assert.ok(knightRecipes.every(r=>r.item.slot!=='武器'||CLASSES.騎士.weapon.includes(r.item.type)));assert.ok(!knightRecipes.some(r=>/森林狼王之刃|礦坑巨蠍之刃|暗影女王之刃/.test(r.name)));let pet=s.player.pets[0];pet.level=15;p.bossMaterials.狼王之牙=3;let oldLevel=pet.level,oldAtk=companionAttack({...p,pets:[pet],activePets:[pet.uid],summons:[]});assert.ok(evolvePet(p,pet.uid));assert.equal(pet.level,oldLevel);assert.equal(pet.evolution,1);assert.ok(companionAttack({...p,pets:[pet],activePets:[pet.uid],summons:[]})>oldAtk);assert.equal(petControl(pet),3);assert.ok(controlCapacity(20)>controlCapacity(8));
p.inTown=false;p.map=0;p.gold=1e7;p.settings.autoSupply=true;p.statsLog={...p.statsLog,kills:0};let os={player:p,lastOnlineTimestamp:Date.now()-3600000,pendingOffline:null},o=calculateOffline(os);assert.ok(o&&o.kills>0&&o.exp>0);claimOffline(os,o);assert.ok(p.statsLog.kills>0);let lvl=createPlayer('新手','王族');for(let i=0;i<8;i++)gainExp(lvl,15);assert.ok(lvl.level>=2);console.log('V3 28 checks passed');



