import assert from'node:assert/strict';import{CONSUMABLES,ITEMS}from'../js/data.js';import{createPlayer,derived}from'../js/player.js';import{migrate}from'../js/migration.js';import{speedBuff,PET_CLASS_LIMIT,petExpNeed,acDamageReduction,FULL_SKILLS,ELF_ELEMENT_SKILLS,remainingControl}from'../js/balance.js';import{togglePet,petWin,summon}from'../js/companions.js';import{Combat,hitChance,weaponDamage}from'../js/combat.js';import{addBook,learnSkill,skillsFor}from'../js/skills.js';import{calculateOffline}from'../js/offline.js';import{buy,supply}from'../js/shop.js';
assert.equal(CONSUMABLES.綠色藥水.price,300);assert.equal(CONSUMABLES.勇敢藥水.price,900);assert.equal(CONSUMABLES.綠色藥水.duration,300);assert.equal(CONSUMABLES.勇敢藥水.duration,300);assert.equal(CONSUMABLES.紅色藥水.price,45);
for(let cls of Object.keys(PET_CLASS_LIMIT)){let p=migrate({player:createPlayer('測',cls)}).player;p.buffs.greenUntil=Date.now()+1e5;assert.ok(derived(p).speed>derived({...p,buffs:{greenUntil:0,braveUntil:0}}).speed);p.buffs.braveUntil=Date.now()+1e5;assert.equal(Number(speedBuff(p).toFixed(2)),1.5);assert.ok(PET_CLASS_LIMIT[cls]>=1)}
assert.deepEqual(PET_CLASS_LIMIT,{騎士:1,黑暗妖精:1,龍騎士:1,妖精:2,法師:2,幻術士:2,王族:3});assert.ok(petExpNeed(15)>petExpNeed(1));assert.ok(petExpNeed(31)>petExpNeed(15));let pp=migrate({player:createPlayer('王','王族')}).player;pp.stats.cha=50;pp.pets=[1,2,3].map(i=>({uid:`p${i}`,type:'dog',name:'狗',level:1,exp:0,hp:70,alive:true,evolution:0,evolutionMultiplier:1}));pp.activePets=['p1'];petWin(pp,300);assert.equal(pp.pets[0].level>pp.pets[1].level,true);pp.pets.forEach(x=>{x.level=1;x.exp=0});pp.activePets=['p1','p2'];petWin(pp,30);assert.equal(pp.pets[0].exp,pp.pets[1].exp);assert.equal(pp.pets[0].level,pp.pets[1].level);pp.activePets=['p1','p2','p3'];pp.pets.forEach(x=>x.exp=0);petWin(pp,30);assert.equal(pp.pets[2].level,2);assert.equal(pp.pets[2].exp,1);
for(let [cls,max] of Object.entries(PET_CLASS_LIMIT)){let p=migrate({player:createPlayer('寵',cls)}).player;p.stats.cha=99;p.pets=Array.from({length:4},(_,i)=>({uid:`x${i}`,type:'dog',name:'狗',level:1,exp:0,hp:70,alive:true,evolution:0,evolutionMultiplier:1}));p.activePets=[];for(let pet of p.pets)togglePet(p,pet.uid);assert.equal(p.activePets.length,max)}let low=migrate({player:createPlayer('低魅','王族')}).player;low.pets=Array.from({length:3},(_,i)=>({uid:`l${i}`,type:'bear',name:'熊',level:1,exp:0,hp:100,alive:true,evolution:0,evolutionMultiplier:1}));low.activePets=[];low.pets.forEach(x=>togglePet(low,x.uid));assert.ok(low.activePets.length<3);
assert.ok(Object.values(FULL_SKILLS).every(x=>x.length>=5));assert.ok(FULL_SKILLS.妖精.some(x=>x[0]==='三重矢'&&x[2]==='active'));assert.ok(FULL_SKILLS.騎士.some(x=>x[0]==='衝擊之暈'));assert.ok(FULL_SKILLS.龍騎士.some(x=>x[0]==='屠宰者'));assert.deepEqual(Object.keys(ELF_ELEMENT_SKILLS),['火','水','風','地']);for(let e of Object.keys(ELF_ELEMENT_SKILLS))assert.equal(ELF_ELEMENT_SKILLS[e].length,3);
let elf=migrate({player:createPlayer('弓','妖精')}).player;elf.level=40;elf.elfElement='風';let triple=skillsFor(elf).find(x=>x[0]==='三重矢');addBook(elf,triple);assert.ok(learnSkill(elf,'三重矢'));elf.activeSkillSettings.attack=['三重矢'];elf.mp=100;elf.settings.arrowType='木箭';elf.consumables.木箭=100;elf.equipment.武器={id:'bow',name:'弓',slot:'武器',type:'弓',small:10,large:10,hit:2,safe:6,two:true,enhance:0};let state={player:elf,logs:[]},c=new Combat(state);elf.inTown=false;c.enemy={name:'木樁',hp:1000,maxHp:1000,ac:10,level:1,atk:1,hit:1,exp:1,gold:1};let before=c.enemy.hp,mp=elf.mp;c.skillTick(elf,derived(elf));assert.ok(c.enemy.hp<before);assert.equal(mp-elf.mp,15);assert.match(state.logs[0].t,/三重矢.*\+.*\+/);let cd=elf.skillCooldowns.三重矢;c.skillTick(elf,derived(elf));assert.equal(elf.skillCooldowns.三重矢,cd);
assert.ok(hitChance(25,-40,20)<hitChance(25,10,20));assert.ok(acDamageReduction(-40)>acDamageReduction(10));assert.ok(acDamageReduction(-100)<.5);let armor=ITEMS.find(x=>x.slot==='盔甲'),a=migrate({player:createPlayer('甲','騎士')}).player;a.equipment.盔甲={...armor,enhance:0};let ac0=derived(a).ac;a.equipment.盔甲.enhance=7;assert.ok(derived(a).ac<ac0);assert.equal(derived(a).physicalReduction,0);
let off=migrate({player:createPlayer('離','騎士')}).player;off.inTown=false;off.gold=1e8;off.settings.autoSupply=true;off.buffs.greenUntil=Date.now()+1e6;let os={player:off,lastOnlineTimestamp:Date.now()-3600e3},o=calculateOffline(os);assert.ok(o.gross>o.kills*10);let oldGreen=off.consumables.綠色藥水;off.gold=1e6;assert.ok(buy(off,'綠色藥水',1));assert.equal(off.consumables.綠色藥水,oldGreen+1);assert.equal(migrate({player:createPlayer('舊','法師')}).saveVersion,8);console.log('V5 43 checks passed');


