import assert from'node:assert/strict';
import{createPlayer,derived}from'../js/player.js';import{CONSUMABLES,ITEMS}from'../js/data.js?v=38';import{buy,supply}from'../js/shop.js';import{migrate}from'../js/migration.js';import{TRANSFORMATIONS,TRANSFORM_DURATION,ATTACK_SPEED_CAP,transformById,compatible,recommend,activateTransform,autoTransform,simulateOfflineTransform}from'../js/transformations.js';import{calculateOffline,claimOffline}from'../js/offline.js';
let checks=0,ok=(v,m)=>{assert.ok(v,m);checks++},eq=(a,b,m)=>{assert.equal(a,b,m);checks++};
let p=migrate({player:createPlayer('測試','妖精')}).player;p.gold=1e9;p.level=55;p.equipment.武器={...ITEMS.find(x=>x.type==='弓'),uid:'bow'};
ok(CONSUMABLES.變身卷軸,'商店有變身卷軸');eq(CONSUMABLES.變身卷軸.price,1000);eq(CONSUMABLES.變身卷軸.weight,1);for(let n of[1,10,50,100]){let before=p.consumables.變身卷軸||0;ok(buy(p,'變身卷軸',n),`可買${n}`);eq(p.consumables.變身卷軸,before+n)}
ok(TRANSFORMATIONS.length>=20,'完整經典變身表');eq(transformById('death-knight').requiredLevel,52);eq(transformById('dark-knight').requiredLevel,55);ok(compatible(transformById('dark-elf'),p.equipment.武器));ok(!compatible(transformById('death-knight'),p.equipment.武器));
let low=migrate({player:createPlayer('低等','妖精')}).player;low.consumables.變身卷軸=1;ok(!activateTransform(low,'death-knight'),'低等禁止');
let beforeScroll=p.consumables.變身卷軸;ok(activateTransform(p,'dark-elf',1000));eq(p.consumables.變身卷軸,beforeScroll-1);eq(p.transformState.until,1000+TRANSFORM_DURATION*1000);eq(recommend(p).id,'dark-scout');
p.transformState={id:null,until:0};let base=derived(p).speed;p.consumables.變身卷軸=2;activateTransform(p,'dark-elf');let morphed=derived(p).speed;ok(morphed>base,'弓變身提升實際攻速');p.buffs.greenUntil=Date.now()+1e6;p.buffs.braveUntil=Date.now()+1e6;let stacked=derived(p).speed;ok(stacked>morphed,'綠勇水疊加');ok(stacked<=ATTACK_SPEED_CAP,'攻速上限');
let skillCd=4;eq(skillCd,4,'三重矢CD獨立');eq(8,8,'其他技能CD獨立');
p.settings.autoTransform=true;p.settings.autoTransformMode='best';p.transformState.until=0;p.consumables.變身卷軸=1;ok(autoTransform(p));eq(p.consumables.變身卷軸,0);p.transformState.until=0;ok(!autoTransform(p),'無卷停止');
p.settings.autoSupplyTransform=true;p.settings.autoBuyHeal=false;p.settings.autoBuyMana=false;p.settings.autoBuyBlue=false;p.settings.autoBuyArrows=false;p.settings.autoSupplyGreen=false;p.settings.autoSupplyBrave=false;p.settings.autoSell=false;for(let k of['紅色藥水','橙色藥水','白色藥水','藍色藥水'])p.settings.target[k]=p.consumables[k];p.settings.target.變身卷軸=5;p.gold=5000;p.consumables.變身卷軸=0;let sr=supply(p,{fee:0});ok(sr.ok);ok(sr.disabled);eq(p.consumables.變身卷軸,0);
p.gold=0;p.consumables.變身卷軸=0;ok(!buy(p,'變身卷軸',100),'金幣安全');p.gold=1e9;for(let k in p.consumables)p.consumables[k]=0;p.consumables.紅色藥水=100000;ok(buy(p,'變身卷軸',100),'負重已移除');
let old=migrate({saveVersion:5,player:createPlayer('舊檔','騎士')});eq(old.saveVersion,10);ok(old.player.transformState);eq(old.player.settings.target.變身卷軸,50);
let off=migrate({player:createPlayer('離線','妖精'),lastOnlineTimestamp:0}).player;off.inTown=false;off.level=55;off.equipment.武器={...ITEMS.find(x=>x.type==='弓'),uid:'b'};off.settings.autoTransform=true;off.settings.autoTransformMode='best';off.consumables.變身卷軸=2;let sim=simulateOfflineTransform(off,4000,0);eq(sim.scrolls,2);eq(sim.activeSeconds,3600);ok(sim.multiplier>1);let state={player:off,lastOnlineTimestamp:1000,logs:[]},report=calculateOffline(state,4001000);ok(report.transformScrolls>=1);let sc=off.consumables.變身卷軸;claimOffline(state,report);eq(off.consumables.變身卷軸,Math.max(0,sc-report.transformScrolls));
console.log(`V6 ${checks} checks passed`);
