import assert from'node:assert/strict';import{createPlayer,derived}from'../js/player.js';import{ITEMS}from'../js/data.js?v=38';import{migrate}from'../js/migration.js';import{skillDrop,learnSkill,skillsFor}from'../js/skills.js';import{SKILL_TIER_RATE}from'../js/loot.js';import{ARROWS,arrowEffect,consumeArrow}from'../js/resources.js';import{weaponDamage,Combat}from'../js/combat.js';import{calculateOffline,claimOffline}from'../js/offline.js';
let n=0,ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.equal(a,b,m);n++};
eq(SKILL_TIER_RATE.初階,.038);eq(SKILL_TIER_RATE.中低階,.02);eq(SKILL_TIER_RATE.中階,.008);eq(SKILL_TIER_RATE.高階,.0025);eq(SKILL_TIER_RATE.稀有高階,.0008);eq(SKILL_TIER_RATE.頂級,.0002);
let mage=migrate({player:createPlayer('書測','法師'),logs:[]}).player,mageSkill=skillsFor(mage).find(x=>x[0]==='光箭');mage.level=mageSkill[1];let drop=skillDrop({name:'妖魔法師'},mage,()=>.01);eq(drop[0],'光箭');ok(mage.bag.some(x=>x.kind==='book'&&x.skill==='光箭'));ok(learnSkill(mage,'光箭'));ok(mage.learnedSkills.includes('光箭'));
let pity=migrate({player:createPlayer('保護','法師'),logs:[]}).player,pitySkill=skillsFor(pity).find(x=>x[0]==='光箭');for(let i=0;i<91;i++)skillDrop({name:'妖魔法師'},pity,()=>.08);ok(pity.bag.some(x=>x.skill==='光箭'),'基礎技能防極端臉黑');ok(pity.skillPity.光箭<90);
eq(ARROWS.木箭.damage,1);eq(ARROWS.銀箭.damage,2);eq(ARROWS.米索莉箭.damage,4);eq(ARROWS.銀箭.undead,1.5);let ar=migrate({player:createPlayer('箭測','妖精'),logs:[]}).player;ar.level=30;ar.equipment.武器={...ITEMS.find(x=>x.type==='弓'),uid:'bow'};ar.consumables.木箭=100;ar.consumables.銀箭=100;ar.consumables.米索莉箭=100;let normal={name:'哥布林',race:'一般',size:'Small',ac:5,level:5},undead={name:'骷髏兵',race:'不死',size:'Small',ac:5,level:5};ar.settings.arrowType='木箭';let wood=weaponDamage(ar,normal,()=>.5),woodUndead=weaponDamage(ar,undead,()=>.5);ar.settings.arrowType='銀箭';let silver=weaponDamage(ar,normal,()=>.5),silverUndead=weaponDamage(ar,undead,()=>.5);ar.settings.arrowType='米索莉箭';let mithril=weaponDamage(ar,normal,()=>.5);ok(silver>wood);ok(mithril>silver);ok(silverUndead>woodUndead);eq(arrowEffect(ar,normal).bonus,4);
ar.settings.arrowType='銀箭';let before=ar.consumables.銀箭;ok(consumeArrow(ar,1));eq(ar.consumables.銀箭,before-1);ar.learnedSkills=['三重矢'];ar.activeSkillSettings.attack=['三重矢'];ar.mp=100;let c=new Combat({player:ar,logs:[]});c.enemy={...undead,hp:999,maxHp:999,atk:1,hit:1};before=ar.consumables.銀箭;c.skillTick(ar,derived(ar));eq(ar.consumables.銀箭,before-3);ok(c.enemy.hp<999);let cd=ar.skillCooldowns.三重矢;ok(cd>Date.now());ar.consumables.銀箭=2;ar.settings.autoBuyArrows=false;ar.settings.autoSupply=false;ar.skillCooldowns.三重矢=0;let mp=ar.mp;c.skillTick(ar,derived(ar));eq(ar.consumables.銀箭,2);eq(ar.mp,mp);eq(ar.skillCooldowns.三重矢,0);
for(let seconds of[300,900,3600]){let p=migrate({player:createPlayer(`離線${seconds}`,'妖精'),logs:[]}).player;p.inTown=false;p.level=35;p.map=2;p.gold=1e7;p.equipment.武器={...ITEMS.find(x=>x.type==='弓'),uid:'b'};p.settings.arrowType='銀箭';p.settings.autoBuyArrows=true;p.settings.autoSupply=true;p.settings.autoGreen=false;p.settings.autoBrave=false;p.consumables.銀箭=20;let now=1_800_000_000_000,state={player:p,logs:[],lastOnlineTimestamp:now-seconds*1000},report=calculateOffline(state,now,()=>0);eq(report.sec,seconds);ok(report.kills>0);ok(report.exp>0);ok(report.gross>0);ok(report.consumed.銀箭>0);ok(report.purchased.銀箭>=0);let gold=p.gold,exp=p.exp,arrows=p.consumables.銀箭;claimOffline(state,report);ok(p.exp>exp);ok(p.gold!==gold);eq(p.consumables.銀箭,Math.max(0,arrows+(report.purchased.銀箭||0)-report.consumed.銀箭));ok(state.pendingOffline===null)}
let offMage=migrate({player:createPlayer('離線書','法師'),logs:[]}).player;offMage.inTown=false;offMage.level=20;offMage.map=1;offMage.gold=1e7;offMage.settings.autoGreen=false;offMage.settings.autoBrave=false;let os={player:offMage,logs:[],lastOnlineTimestamp:1_000_000},or=calculateOffline(os,3_601_000,()=>0);ok(or.books.length>0,'離線技能書掉落');let beforeBooks=offMage.bag.length;claimOffline(os,or);ok(offMage.bag.length>beforeBooks);
let noArrow=migrate({player:createPlayer('無箭','妖精'),logs:[]}).player;noArrow.inTown=false;noArrow.level=20;noArrow.equipment.武器={...ITEMS.find(x=>x.type==='弓'),uid:'b'};noArrow.settings.arrowType='銀箭';noArrow.settings.autoBuyArrows=false;noArrow.consumables.銀箭=0;let nr=calculateOffline({player:noArrow,lastOnlineTimestamp:1000},301000,()=>0);eq(nr.kills,0);ok(nr.stopped);console.log(`V8 ${n} checks passed`);
