import{ARENA,createPrototypeState,getFormation,getResults,stepPrototype,tapPrototype}from'./physics.js?v=v3-30s-2';
const SAVE_KEY='qunxiong-world-blackwind-prototype-v3',canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d'),hud={time:document.querySelector('[data-time]'),combo:document.querySelector('[data-combo]'),power:document.querySelector('[data-power]'),skill:document.querySelector('[data-skill]'),hint:document.querySelector('[data-hint]')},result=document.querySelector('.result');
canvas.width=ARENA.width;canvas.height=ARENA.height;let state=createPrototypeState(),last=0,raf=0,audio=null,hudIn=0,fpsIn=0,frames=0;
const colors=[['#69c99a','#123f32'],['#ed665e','#441b20'],['#efd369','#3c5736']];
function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect?.(x,y,w,h,r);if(!ctx.roundRect){ctx.rect(x,y,w,h);}return ctx;}
function portrait(x,y,index,scale=1,alpha=1){const c=colors[index];ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle=c[1];ctx.beginPath();ctx.ellipse(0,4,19,22,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e8bc92';ctx.beginPath();ctx.arc(0,-7,10,0,Math.PI*2);ctx.fill();ctx.fillStyle=c[0];ctx.beginPath();ctx.moveTo(-13,-7);ctx.quadraticCurveTo(0,-29,14,-7);ctx.lineTo(7,-15);ctx.lineTo(0,-7);ctx.lineTo(-7,-16);ctx.closePath();ctx.fill();ctx.fillStyle='#18202c';ctx.fillRect(-5,-8,3,2);ctx.fillRect(3,-8,3,2);if(index===0){ctx.strokeStyle='#2b211a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,16);ctx.stroke();ctx.strokeStyle='#4dffc0';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(12,4);ctx.lineTo(25,-10);ctx.stroke();}if(index===1){ctx.strokeStyle='#ffb05e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-15,6);ctx.lineTo(-26,-7);ctx.stroke();}ctx.restore();}
function scene(){const g=ctx.createLinearGradient(0,0,0,ARENA.height);g.addColorStop(0,'#251927');g.addColorStop(.55,'#101b24');g.addColorStop(1,'#071018');ctx.fillStyle=g;ctx.fillRect(0,0,ARENA.width,ARENA.height);ctx.globalAlpha=.2;ctx.strokeStyle='#b58b58';for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(i*52-20,ARENA.height);ctx.lineTo(i*52+65,50);ctx.stroke();}ctx.globalAlpha=1;ctx.fillStyle='#55b5df18';ctx.fillRect(22,425,316,58);ctx.strokeStyle='#70d5ff66';ctx.setLineDash([7,5]);ctx.strokeRect(24,427,312,54);ctx.setLineDash([]);ctx.fillStyle='#24364d';rounded(48,467,112,18,9).fill();rounded(200,467,112,18,9).fill();ctx.strokeStyle='#85d8ff';ctx.lineWidth=3;ctx.stroke();}
function boss(){const b=state.boss;ctx.save();ctx.translate(b.x+b.recoilX,b.y);if(b.flash)ctx.filter='brightness(2.4)';ctx.fillStyle='#252b3a';ctx.strokeStyle='#d7b65b';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-42,38);ctx.lineTo(-34,-16);ctx.lineTo(-18,-48);ctx.lineTo(0,-58);ctx.lineTo(22,-44);ctx.lineTo(40,-12);ctx.lineTo(43,38);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#ddb58e';ctx.beginPath();ctx.arc(0,-18,17,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ee574e';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(20,-8);ctx.lineTo(55,30);ctx.stroke();ctx.restore();}
function trail(formation){const speed=Math.hypot(state.core.vx,state.core.vy),alpha=Math.min(.55,speed/800);for(let i=formation.length-1;i>=0;i--){const f=formation[i],color=colors[i][0];ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=5-i;ctx.beginPath();ctx.moveTo(f.x-Math.cos(f.angle)*45,f.y-Math.sin(f.angle)*45);ctx.lineTo(f.x,f.y);ctx.stroke();ctx.restore();}}
function effects(){for(const e of state.events){const a=Math.max(0,Math.min(1,e.life/.65));ctx.save();ctx.globalAlpha=a;ctx.textAlign='center';if(['hit','dash-hit','power-hit'].includes(e.type)){const strong=e.type==='power-hit',r=(strong?25:14)+(1-a)*(strong?70:38);ctx.strokeStyle=strong?'#ffe887':e.type==='dash-hit'?'#8deaff':'#fff';ctx.lineWidth=strong?8:4;ctx.beginPath();ctx.arc(e.x,e.y,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle=strong?'#fff18a':'#fff';ctx.strokeStyle='#111827';ctx.lineWidth=4;ctx.font=`bold ${strong?27:19}px sans-serif`;ctx.strokeText(e.text,e.x,e.y-r*.2);ctx.fillText(e.text,e.x,e.y-r*.2);}else if(e.type==='skill-slash'){ctx.strokeStyle='#52ffc0';ctx.lineWidth=e.phase===2?13:8;ctx.beginPath();ctx.arc(e.x,e.y,62+e.phase*10,-2.7+e.phase*.5,.55+e.phase*.6);ctx.stroke();}else{ctx.fillStyle=e.type.includes('power')?'#ffe77b':e.type==='counter'?'#8ff6ff':'#fff';ctx.font=`bold ${e.type==='skill-intro'?24:18}px sans-serif`;ctx.strokeStyle='#10131d';ctx.lineWidth=5;ctx.strokeText(e.text||'',e.x,e.y);ctx.fillText(e.text||'',e.x,e.y);}ctx.restore();}}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();if(state.shake)ctx.translate((Math.random()-.5)*10,(Math.random()-.5)*7);scene();boss();const formation=getFormation(state);trail(formation);formation.forEach((f,i)=>portrait(f.x,f.y,i,1,i?0.92:1));if(state.skill){const s=state.skill;portrait(s.x,s.y,0,1.12);ctx.save();ctx.globalCompositeOperation='lighter';ctx.strokeStyle='#48ffc0';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(s.x-Math.cos(s.elapsed*10)*45,s.y-Math.sin(s.elapsed*10)*45);ctx.lineTo(s.x,s.y);ctx.stroke();ctx.restore();}effects();ctx.restore();if(state.flash){ctx.fillStyle=`rgba(255,255,255,${Math.min(.32,state.flash*2)})`;ctx.fillRect(0,0,canvas.width,canvas.height);}}
function sync(){hud.time.textContent=state.timeLeft.toFixed(1);hud.combo.textContent=`${state.combo} HIT`;hud.power.style.width=`${state.power}%`;hud.skill.style.width=`${state.skillGauge}%`;hud.hint.textContent=state.powerReady?'POWER READY！回到底部点击发动':state.core.y>ARENA.floor-70?'点击：弹射':state.dashCooldown<=0?'空中点击：冲刺':'DASH 充能中';if(state.complete&&!result.classList.contains('show')){const r=getResults(state);result.innerHTML=`<h2>Prototype Complete</h2><dl><dt>最高 Combo</dt><dd>${r.highestCombo}</dd><dt>FLIP</dt><dd>${r.flips}</dd><dt>DASH</dt><dd>${r.dashes}</dd><dt>Dash Hit</dt><dd>${r.dashHits}</dd><dt>Power Flip</dt><dd>${r.powerFlips}</dd><dt>Perfect</dt><dd>${r.perfects}</dd><dt>关羽技能</dt><dd>${r.skills}</dd></dl><button type="button">再玩一次</button>`;result.classList.add('show');try{localStorage.setItem(SAVE_KEY,JSON.stringify({last:r,playedAt:Date.now()}));}catch{}result.querySelector('button').onclick=restart;}}
function cue(type){try{audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=type==='power'?180:type==='dash'?320:240;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.06);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.065);}catch{}}
function tap(e){e?.preventDefault();const action=tapPrototype(state);if(action.type!=='cooldown'&&action.type!=='ignored')cue(action.type.includes('power')?'power':action.type.includes('dash')?'dash':'flip');}
function frame(now){const dt=last?Math.min(.033,(now-last)/1000):.016;last=now;stepPrototype(state,dt);render();hudIn-=dt;if(hudIn<=0||state.complete){sync();hudIn=.1;}frames++;fpsIn+=dt;if(fpsIn>=1){document.body.dataset.fps=String(Math.round(frames/fpsIn));frames=0;fpsIn=0;}raf=requestAnimationFrame(frame);}
function restart(){state=createPrototypeState();result.classList.remove('show');result.innerHTML='';last=0;}
const eventName=window.PointerEvent?'pointerdown':'touchstart';canvas.addEventListener(eventName,tap,{passive:false});document.querySelector('[data-restart]').addEventListener('click',restart);document.addEventListener('visibilitychange',()=>{last=0;});raf=requestAnimationFrame(frame);
