export const ARENA={width:360,height:520,padding:22,floor:482};
export const TEST_DURATION=30;
const POWER_THRESHOLDS=[10,20,35,50];
const MOVES=[{id:'charge',name:'黑風突擊',windup:.9},{id:'blade',name:'霸刀蓄力',windup:1.15},{id:'spin',name:'旋風斬',windup:1.05}];

export function createPrototypeState(){return{running:true,complete:false,timeLeft:TEST_DURATION,core:{x:180,y:ARENA.floor-22,vx:0,vy:0,r:22,bottomTime:.01,dashTime:0,powerAttack:0,invulnerable:0},boss:{x:180,y:112,r:50,maxHp:28500,hp:28500,flash:0,recoilX:0,move:null,moveIn:1.8,attackIn:0,weakSide:0},combo:0,maxCombo:0,comboTime:0,power:0,powerTier:0,dashCooldown:0,breakGauge:0,breakIn:0,skillGauge:0,skill:null,hitStop:0,shake:0,flash:0,history:[],pendingHits:[],events:[],bossContact:false,stats:{flips:0,perfectFlips:0,dashes:0,counters:0,perfectCounters:0,powerFlips:0,skills:0,hits:0,weakHits:0,breaks:0,bossAttacks:0,damage:0}};}
function emit(s,type,data={}){s.events.push({type,life:data.life||.7,...data});if(s.events.length>64)s.events.splice(0,s.events.length-64);}
function comboRank(n){return n>=100?'天下無雙':n>=50?'戰意沸騰':n>=30?'無雙':n>=20?'猛攻':n>=10?'疾風':'';}
export function getComboRank(n){return comboRank(n);}
function updatePower(s){let tier=0;for(let i=0;i<POWER_THRESHOLDS.length;i++)if(s.combo>=POWER_THRESHOLDS[i])tier=i+1;if(tier>s.powerTier)emit(s,'rank',{text:tier===4?'POWER MAX！':`POWER ${['','Ⅰ','Ⅱ','Ⅲ'][tier]}`,x:180,y:330,life:.9});s.powerTier=Math.max(s.powerTier,tier);s.power=Math.min(100,s.combo*2);}
function weakPoint(s){const b=s.boss;return b.weakSide===0?{x:b.x-45,y:b.y-4}:b.weakSide===1?{x:b.x,y:b.y-51}:{x:b.x+45,y:b.y-4};}
export function getWeakPoint(s){return weakPoint(s);}
function registerHit(s,kind='normal',follower=0,x=s.boss.x,y=s.boss.y){const strong=kind.startsWith('power'),dash=kind.includes('dash')||kind.includes('counter'),skill=kind.includes('skill');const wp=weakPoint(s),weak=Math.hypot(x-wp.x,y-wp.y)<46||(skill&&follower===2);s.combo++;s.maxCombo=Math.max(s.maxCombo,s.combo);s.comboTime=2.35;s.stats.hits++;if(weak)s.stats.weakHits++;let damage=100+(dash?80:0)+(skill?170:0)+(strong?160+Number(kind.slice(-1)||1)*80:0)+(follower?45:0);if(weak)damage=Math.round(damage*1.55);if(s.breakIn)damage=Math.round(damage*1.65);s.boss.hp=Math.max(0,s.boss.hp-damage);s.stats.damage+=damage;s.breakGauge=Math.min(100,s.breakGauge+(weak?18:dash?8:4)+(strong?12:0));s.boss.flash=strong?.16:.08;s.boss.recoilX=(x<s.boss.x?1:-1)*(strong?14:7);s.hitStop=strong?.075:weak?.05:.026;s.shake=strong?.28:weak?.14:.05;s.flash=strong?.12:.035;emit(s,weak?'weak-hit':strong?'power-hit':'hit',{x:s.boss.x,y:s.boss.y,text:`${weak?'WEAK ':''}-${damage}`,life:.7});updatePower(s);if(s.breakGauge>=100&&!s.breakIn){s.breakGauge=0;s.breakIn=3.5;s.stats.breaks++;s.boss.move=null;s.boss.attackIn=0;emit(s,'break',{text:'BOSS BREAK！',x:180,y:190,life:1.1});}}
function startBossMove(s){const m=MOVES[s.stats.bossAttacks%MOVES.length];s.boss.move={...m,elapsed:0,counterFrom:m.windup-.55,counterPerfectFrom:m.windup-.24};emit(s,'warning',{text:m.name,x:180,y:225,life:m.windup});}
function updateBoss(s,dt){const b=s.boss;if(s.breakIn){s.breakIn=Math.max(0,s.breakIn-dt);return;}if(!b.move){b.moveIn-=dt;if(b.moveIn<=0)startBossMove(s);return;}const m=b.move;m.elapsed+=dt;if(m.elapsed>=m.windup){s.stats.bossAttacks++;emit(s,'boss-impact',{text:m.name,x:b.x,y:b.y+72,life:.5});if(s.core.invulnerable<=0){s.combo=Math.max(0,s.combo-8);s.comboTime=.8;s.shake=.35;emit(s,'hurt',{text:'隊伍受擊！',x:s.core.x,y:s.core.y-30});}b.move=null;b.moveIn=2.1+(s.stats.bossAttacks%3)*.25;}}
export function getActionHint(s){if(s.boss.move&&s.boss.move.elapsed>=s.boss.move.counterFrom)return s.boss.move.elapsed>=s.boss.move.counterPerfectFrom?'PERFECT COUNTER！':'COUNTER DASH！';if(s.core.y>=ARENA.floor-40)return s.powerTier?`POWER FLIP ${s.powerTier===4?'MAX':'ⅠⅡⅢ'[s.powerTier-1]}`:'FLIP';return s.dashCooldown<=0?'DASH':'DASH 充能中';}
export function tapPrototype(s){if(!s.running||s.complete||s.skill)return{type:'ignored'};const c=s.core,inZone=c.y>=ARENA.floor-40;if(inZone){const perfect=c.bottomTime>0&&c.bottomTime<=.32,tier=s.powerTier;c.vx=(c.x<180?1:-1)*(tier?80:42);c.vy=-(perfect?700:650)-(tier*32);c.bottomTime=0;c.powerAttack=tier;c.dashTime=0;s.dashCooldown=.25;s.stats.flips++;if(perfect){s.stats.perfectFlips++;s.breakGauge=Math.min(100,s.breakGauge+9);emit(s,'perfect',{text:'PERFECT FLIP！',x:180,y:404});}if(tier){s.stats.powerFlips++;emit(s,'power-flip',{text:`POWER FLIP ${tier===4?'MAX':'ⅠⅡⅢ'[tier-1]}`,x:180,y:350,life:1});s.powerTier=0;s.power=0;}else emit(s,'flip',{text:'FLIP！',x:180,y:410});return{type:tier?'power-flip':'flip',perfect,tier};}
 if(s.dashCooldown>0)return{type:'cooldown'};const b=s.boss,dx=b.x-c.x,dy=b.y-c.y,d=Math.max(1,Math.hypot(dx,dy));let counter=0;if(b.move&&b.move.elapsed>=b.move.counterFrom){counter=b.move.elapsed>=b.move.counterPerfectFrom?2:1;b.move=null;b.moveIn=1.7;c.invulnerable=.65;s.stats.counters++;if(counter===2)s.stats.perfectCounters++;s.breakGauge=Math.min(100,s.breakGauge+(counter===2?34:22));s.combo+=counter===2?4:2;s.comboTime=2.35;emit(s,'counter',{text:counter===2?'PERFECT COUNTER！':'COUNTER DASH！',x:c.x,y:c.y-34,life:1});}
 c.vx=dx/d*(counter?760:650);c.vy=dy/d*(counter?760:650);c.dashTime=.23;s.dashCooldown=counter?1.0:.82;s.stats.dashes++;return{type:counter===2?'perfect-counter':counter?'counter-dash':'dash'};}
function beginSkill(s){s.skill={elapsed:0,duration:1.55,x:s.core.x,y:s.core.y,hitMask:0};s.skillGauge=0;s.stats.skills++;s.hitStop=.1;emit(s,'skill-intro',{text:'關羽【青龍偃月】',x:180,y:180,life:.55});}
function updateSkill(s,dt){const k=s.skill;if(!k)return;k.elapsed+=dt;const t=k.elapsed,b=s.boss;if(t<.34){const p=t/.34;k.x=s.core.x+(b.x-82-s.core.x)*p;k.y=s.core.y+(b.y-26-s.core.y)*p;}else if(t<.7){const p=(t-.34)/.36;k.x=88+190*p;k.y=b.y-28+Math.sin(p*Math.PI)*-45;}else if(t<1.08){const p=(t-.7)/.38;k.x=278-196*p;k.y=b.y+28+Math.sin(p*Math.PI)*42;}else{k.x=82+(s.core.x-82)*Math.min(1,(t-1.08)/.47);k.y=b.y+(s.core.y-b.y)*Math.min(1,(t-1.08)/.47);}for(const [i,at] of [.31,.67,1.05].entries())if(t>=at&&!(k.hitMask&(1<<i))){k.hitMask|=1<<i;registerHit(s,i===2?'skill-final':'skill',i,k.x,k.y);emit(s,'skill-slash',{phase:i,x:b.x,y:b.y,life:i===2?.8:.5});}if(t>=k.duration){s.skill=null;emit(s,'skill-end',{text:'武聖歸陣',x:s.core.x,y:s.core.y-30});}}
export function stepPrototype(s,rawDt){if(!s.running||s.complete)return s;const dt=Math.min(.034,Math.max(0,rawDt));s.timeLeft=Math.max(0,s.timeLeft-dt);if(!s.timeLeft||s.boss.hp<=0){s.running=false;s.complete=true;return s;}s.comboTime=Math.max(0,s.comboTime-dt);if(!s.comboTime){s.combo=0;s.power=0;s.powerTier=0;}s.dashCooldown=Math.max(0,s.dashCooldown-dt);s.breakIn=Math.max(0,s.breakIn-dt);s.core.invulnerable=Math.max(0,s.core.invulnerable-dt);s.boss.flash=Math.max(0,s.boss.flash-dt);s.boss.recoilX*=Math.pow(.78,dt*60);s.shake=Math.max(0,s.shake-dt);s.flash=Math.max(0,s.flash-dt);for(const e of s.events)e.life-=dt;s.events=s.events.filter(e=>e.life>0);if(s.hitStop>0){s.hitStop=Math.max(0,s.hitStop-dt);return s;}updateBoss(s,dt);updateSkill(s,dt);for(const q of s.pendingHits)q.delay-=dt;for(const q of s.pendingHits.filter(q=>q.delay<=0))registerHit(s,q.kind,q.follower,q.x,q.y);s.pendingHits=s.pendingHits.filter(q=>q.delay>0);
 const c=s.core;c.dashTime=Math.max(0,c.dashTime-dt);c.vy+=515*dt;c.x+=c.vx*dt;c.y+=c.vy*dt;c.vx*=Math.pow(.997,dt*60);const p=ARENA.padding;if(c.x-c.r<p){c.x=p+c.r;c.vx=Math.abs(c.vx)*.9;}else if(c.x+c.r>ARENA.width-p){c.x=ARENA.width-p-c.r;c.vx=-Math.abs(c.vx)*.9;}if(c.y-c.r<p){c.y=p+c.r;c.vy=Math.abs(c.vy)*.84;}if(c.y+c.r>=ARENA.floor){c.y=ARENA.floor-c.r;c.vy=0;c.vx*=.72;c.bottomTime+=dt;}else c.bottomTime=0;s.history.unshift({x:c.x,y:c.y});if(s.history.length>20)s.history.length=20;
 const dx=c.x-(s.boss.x+s.boss.recoilX),dy=c.y-s.boss.y,overlap=Math.hypot(dx,dy)<c.r+s.boss.r;if(overlap&&!s.bossContact){const tier=c.powerAttack,kind=tier?`power${tier}`:c.dashTime>0?'dash':'normal';registerHit(s,kind,0,c.x,c.y);if(tier)for(let i=1;i<=Math.min(4,tier+1);i++)s.pendingHits.push({delay:i*.055,kind,follower:i%3,x:s.boss.x+(i%2?28:-28),y:s.boss.y});else if(c.dashTime>0)s.pendingHits.push({delay:.085,kind:'dash',follower:1,x:s.boss.x,y:s.boss.y});s.bossContact=true;const d=Math.max(1,Math.hypot(dx,dy)),nx=dx/d,ny=dy/d,dot=c.vx*nx+c.vy*ny;c.x=s.boss.x+nx*(c.r+s.boss.r+1);c.y=s.boss.y+ny*(c.r+s.boss.r+1);c.vx=(c.vx-2*dot*nx)*.88;c.vy=(c.vy-2*dot*ny)*.88;c.powerAttack=0;s.skillGauge=Math.min(100,s.skillGauge+(tier?18:10));s.boss.weakSide=(s.boss.weakSide+1)%3;}if(!overlap)s.bossContact=false;if((s.breakIn>0||s.combo>=28)&&s.skillGauge>=100&&!s.skill)beginSkill(s);return s;}
export function getFormation(s){const c=s.core,h=s.history,a=h[Math.min(5,h.length-1)]||c,b=h[Math.min(11,h.length-1)]||a,angle=Math.atan2(c.vy,c.vx),px=-Math.sin(angle),py=Math.cos(angle),spread=Math.hypot(c.vx,c.vy)>180?18:26;return[{x:c.x,y:c.y,angle},{x:a.x+px*spread,y:a.y+py*spread,angle},{x:b.x-px*spread,y:b.y-py*spread,angle}];}
export function getResults(s){return{highestCombo:s.maxCombo,flips:s.stats.flips,perfectFlips:s.stats.perfectFlips,dashes:s.stats.dashes,counters:s.stats.counters,perfectCounters:s.stats.perfectCounters,powerFlips:s.stats.powerFlips,skills:s.stats.skills,hits:s.stats.hits,weakHits:s.stats.weakHits,breaks:s.stats.breaks,bossAttacks:s.stats.bossAttacks,damage:s.stats.damage};}
