import { FEEL_PRESETS } from './feel-physics.mjs?v=4';
import { CONTACT_PRESETS } from './contact-physics.mjs?v=3';
import { drawCharacter,drawBossCharacter,drawSpriteAfterimages } from './character-renderer.mjs?v=1';
import { spawnImpact,updateSkillVfx,drawSkillTrails,drawSkillVfx } from './skill-vfx-renderer.mjs?v=1';
const KEY='qunxiong-world:prototype-lubu-v033';
const app=document.querySelector('#app');
const defaults={highest:0,selected:1,lubu:{captured:false,quality:'normal',souls:0,breakthrough:0},runs:0};
const structuredCloneSafe=o=>JSON.parse(JSON.stringify(o));
const load=()=>{try{return {...structuredCloneSafe(defaults),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredCloneSafe(defaults)}};
let save=load(),raf=0,game=null;
const persist=()=>localStorage.setItem(KEY,JSON.stringify(save));
const title=d=>d>=30?`鬼神・難度${d}`:({5:'強敵',10:'飛將',15:'傳說',20:'天下無雙'}[d]||`難度 ${d}`);
const modifiers=d=>d<21?[]:[['狂暴','神速','鐵壁','背水','霸者'][d%5],...(d%3===0?['神速']:[])].slice(0,2);
const STAR_COSTS=[3,5,8,12,18],STAR_UNLOCKS=['飛將戰意衰減減緩','無雙亂舞追加戟光','飛將破軍追擊強化','鬼神・天下無雙強化','鬼神無雙・極'];
const POWER_LABELS=['飛將破軍 I','飛將破軍 II','飛將破軍 III','POWER MAX・三軍列陣'];
function home(){cancelAnimationFrame(raf);game=null;const lv=save.lubu.breakthrough,cost=STAR_COSTS[lv];app.innerHTML=`<section class="shell"><div class="panel challenge"><div><div class="eyebrow">傳奇挑戰</div><h1>呂布</h1><p class="quote">「人中呂布，馬中赤兔」</p></div><div class="stats"><span>最高通關：${save.highest}</span><span>魂魄：${save.lubu.souls}</span></div><div class="stars">${'★'.repeat(lv)}${'☆'.repeat(5-lv)}</div>${lv<5?`<p>下一突破：${STAR_UNLOCKS[lv]}・魂魄 ${save.lubu.souls} / ${cost}</p><button class="btn" data-break ${save.lubu.souls<cost?'disabled':''}>突破（100%）</button>`:'<p class="eyebrow">鬼神無雙・極 已解鎖</p>'}<div class="difficulty"><button class="btn" data-minus>−</button><strong>${title(save.selected)}</strong><button class="btn" data-plus>＋</button></div>${modifiers(save.selected).length?`<p>異變：${modifiers(save.selected).join('・')}</p>`:''}<button class="btn primary" data-start>開始挑戰</button>${save.lubu.captured?'<button class="btn primary" data-practice>使用呂布试玩</button>':''}<p>擊敗難度 5 可收服；難度 15 首通保證傳說。</p></div></section>`;app.querySelector('[data-minus]').onclick=()=>{save.selected=Math.max(1,save.selected-1);home()};app.querySelector('[data-plus]').onclick=()=>{save.selected=Math.min(save.highest+1,save.selected+1);home()};app.querySelector('[data-start]').onclick=()=>start(false);app.querySelector('[data-practice]')?.addEventListener('click',()=>start(true));app.querySelector('[data-break]')?.addEventListener('click',()=>{if(save.lubu.souls>=cost){save.lubu.souls-=cost;save.lubu.breakthrough++;persist();home()}})}
function start(practice=false){const d=save.selected,scale=1+Math.pow(d-1,.72)*.2;game={d,practice,hp:Math.round((practice?1700:2400)*scale),maxHp:Math.round((practice?1700:2400)*scale),break:0,breakTime:0,combo:0,comboT:0,phase:1,time:0,attack:2.8,telegraph:0,perfect:0,flying:0,skillEnergy:practice?100:0,ultimate:practice?100:0,power:1,powerGauge:20,special:null,ghosts:[],god:0,godCd:0,airDashReady:true,chainWindow:0,chainCount:0,skillQueue:[],skillCooldown:0,skills:[{name:'青龍偃月',gauge:62},{name:'萬軍震破',gauge:46},{name:'仁德天下',gauge:30}],stats:{flips:0,zoneEntries:0,directHits:0,followerHits:0,dashHits:0,emptySwings:0,skills:0,chains:0,fullChains:0,breaks:0,powerMax:0,ultimate:0},entities:[{x:120,y:665,vx:0,vy:0,c:'#7bd4ff',lubu:practice,hitCd:0},{x:190,y:670,vx:0,vy:0,c:'#72e29c',hitCd:0},{x:260,y:665,vx:0,vy:0,c:'#ffb15e',hitCd:0}],boss:{x:180,y:310,vx:0,vy:0,dir:1,recoil:0,dashing:false},effects:[],over:false,debug:new URLSearchParams(location.search).get('debug')==='1'};app.innerHTML=`<section class="shell"><div class="battle"><canvas></canvas><div class="hud"><div class="hud-row"><b>${practice?'修羅木樁':'呂布'}・${title(d)}</b><span class="phase">${practice?'玩家呂布實戰':'人中呂布'}</span></div><div class="bar"><i></i></div><div class="hud-row"><small>BREAK</small><b class="combo"></b></div><div class="bar break"><i></i></div><div class="lubu-status">CHAIN 0・Power I</div></div>${practice?'<div class="skills"><button data-skill>無雙亂舞</button><button data-ult>鬼神・天下無雙</button></div>':''}<div class="tip">點擊／觸控 FLIP・升空後再點 AIR DASH</div><div class="flash"></div></div></section>`;const c=app.querySelector('canvas'),dpr=Math.min(3,devicePixelRatio||1);c.width=360*dpr;c.height=720*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);c.addEventListener('pointerdown',flip);app.querySelector('[data-skill]')?.addEventListener('click',e=>{e.stopPropagation();activateSpecial('skill')});app.querySelector('[data-ult]')?.addEventListener('click',e=>{e.stopPropagation();activateSpecial('ultimate')});game.canvas=c;game.ctx=ctx;game.last=performance.now();raf=requestAnimationFrame(loop)}
function activateSpecial(type){const g=game;if(!g?.practice||g.special||(type==='skill'&&g.skillEnergy<100)||(type==='ultimate'&&g.ultimate<100))return;g[type==='skill'?'skillEnergy':'ultimate']=0;g.special={type,time:0,hit:0};g.entities[0].skillPose=type==='ultimate'?1.8:1.1;spawnImpact(g,'impact',180,360,type==='ultimate');fx(type==='skill'?'無雙亂舞！':'鬼神・天下無雙！',180,360,'#ff725b')}
function flip(){if(!game||game.over)return;const g=game,cfg=feel(g),leader=g.entities[0];if(leader.y<535){if(g.airDashReady&&!g.special){const dx=g.boss.x-leader.x,dy=g.boss.y-leader.y,len=Math.max(1,Math.hypot(dx,dy));leader.vx=dx/len*cfg.dashSpeed;leader.vy=dy/len*cfg.dashSpeed;g.airDashReady=false;g.dashActive=.48;fx('AIR DASH',leader.x,leader.y-25,'#ffcf91')}return}const perfect=leader.y>625,good=leader.y>555,launch=perfect?cfg.perfectLaunch:cfg.normalLaunch;leader.vy=-launch;leader.vx=(leader.x<180?1:-1)*(good?cfg.flipSide:cfg.flipSide*.72);g.airDashReady=true;g.currentFlipHit=false;g.currentFlipZone=false;g.flipClosed=false;g.stats.flips++;g.powerGauge=Math.min(100,g.powerGauge+(perfect?18:good?12:8));fx(perfect?'PERFECT FLIP':good?'GOOD FLIP':'FLIP',180,575,perfect?'#fff09a':'#ffc174');g.power=Math.min(4,1+Math.floor(g.powerGauge/25));if(g.power===4)triggerPowerMax();if(g.telegraph>0){const perfectCounter=g.telegraph<.24;g.perfect=perfectCounter?1:.5;g.break=Math.min(100,g.break+(perfectCounter?44:24));g.boss.vy=perfectCounter?-420:-260;g.boss.vx*=-.55;g.boss.dashing=false;fx(perfectCounter?'PERFECT COUNTER':'COUNTER',180,310,'#fff19a');g.combo+=perfectCounter?4:2;g.attack=3.6}}
function fx(text,x,y,c='#fff'){game.effects.push({text,x,y,c,life:1});if(!game.vfx)game.vfx=[];if(text.includes('青龍')){game.entities[0].skillPose=.45;spawnImpact(game,'slash',x,y,true)}else if(text.includes('萬軍')){game.entities[1].skillPose=.45;spawnImpact(game,'shock',x,y,true)}else if(text.includes('仁德')){game.entities[2].skillPose=.55;spawnImpact(game,'aura',180,470,true)}else if(text.includes('FULL CHAIN')){game.entities.forEach(e=>e.skillPose=.55);spawnImpact(game,'bond',x,y,true)}else if(text.includes('WEAK')||text.startsWith('-'))spawnImpact(game,'impact',x,y,text.includes('WEAK'))}
function loop(now){if(!game)return;let dt=Math.min(.034,(now-game.last)/1000);game.last=now;tickFeelBefore(dt);tickPlayerLubu(dt);tickCombatChain(dt);updateSkillVfx(game,dt);if(game.over)return;step(dt);if(game.over)return;tickFeelAfter(dt);draw();drawPlayerLubuVfx();publishFeelStats();raf=requestAnimationFrame(loop)}
function publishFeelStats(){const g=game,total=g.heat.reduce((a,b)=>a+b,0)||1,leader=g.entities[0];g.maxCombo=Math.max(g.maxCombo||0,g.combo);const stats={fps:g.time?Math.round((g.frames/3)/g.time):0,peakY:Math.round(g.peakY),maxCombo:g.maxCombo,heatmap:g.heat.map(v=>Math.round(v/total*1000)/10),power:g.power,bossY:Math.round(g.boss.y),leaderY:Math.round(leader.y),leaderVY:Math.round(leader.vy),hpPercent:Math.round(g.hp/g.maxHp*100),...g.stats};window.__lubuFeel=stats;app.dataset.feel=JSON.stringify(stats)}
function feel(g){if(!g.cfg){g.cfg={...FEEL_PRESETS.highBounce,...CONTACT_PRESETS.burst,maxSpeed:980,airDrag:.998,ceilingRetention:.9};g.dashActive=0;g.leaderTrail=[];g.lastCombo=g.combo;g.heat=[0,0,0];g.frames=0;g.peakY=700}return g.cfg}
function tickFeelBefore(dt){const g=game,cfg=feel(g),leader=g.entities[0];g.dashActive=Math.max(0,g.dashActive-dt);g.boss.recoil=Math.max(0,g.boss.recoil-dt);if(!g.boss.dashing){const target=cfg.bossY+Math.sin(g.time*1.1)*cfg.bossRange;g.boss.vy+=(target-g.boss.y)*8*dt;g.boss.vy*=Math.pow(.75,dt*60)}for(const e of g.entities){e.hitCd=Math.max(0,e.hitCd-dt);e.vy+=(630-cfg.gravity)*-dt;e.vx*=Math.pow(cfg.airDrag,dt*60);e.vy*=Math.pow(cfg.airDrag,dt*60)}g.leaderTrail.unshift({x:leader.x,y:leader.y,vx:leader.vx,vy:leader.vy});if(g.leaderTrail.length>16)g.leaderTrail.length=16;for(let i=1;i<3;i++){const sample=g.leaderTrail[Math.min(g.leaderTrail.length-1,i===1?5:9)];if(sample){const e=g.entities[i],pull=.18;e.vx+=(sample.vx-e.vx)*pull;e.vy+=(sample.vy-e.vy)*pull;e.x+=(sample.x-e.x)*.048;e.y+=(sample.y-e.y)*.048}const e=g.entities[i];if(g.followerTimers?.[i-1]>0){g.followerTimers[i-1]-=dt;if(g.followerTimers[i-1]<=0){const origin=g.leaderTrail[i===1?5:9]||leader,dx=g.boss.x-origin.x,dy=g.boss.y-origin.y,len=Math.max(1,Math.hypot(dx,dy));e.x=origin.x;e.y=origin.y;e.vx=dx/len*(800-i*35);e.vy=dy/len*(800-i*35);e.hitCd=0;e.chase=.48;fx(`FOLLOW ${i}`,e.x,e.y-20,'#8fe9ff')}}if(e.chase>0){e.chase-=dt;const dx=g.boss.x-e.x,dy=g.boss.y-e.y,len=Math.max(1,Math.hypot(dx,dy)),speed=Math.max(620,Math.hypot(e.vx,e.vy));e.vx=e.vx*.84+dx/len*speed*.16;e.vy=e.vy*.84+dy/len*speed*.16}}}
function tickFeelAfter(dt){const g=game,cfg=feel(g);for(const e of g.entities){const speed=Math.hypot(e.vx,e.vy);if(speed>cfg.maxSpeed){e.vx*=cfg.maxSpeed/speed;e.vy*=cfg.maxSpeed/speed}if(e.y<65)e.vy=Math.max(180,e.vy*cfg.ceilingRetention);const zone=e.y<280?0:e.y<505?1:2;g.heat[zone]++;g.frames++;g.peakY=Math.min(g.peakY,e.y)}g.lastCombo=g.combo}
function triggerPowerMax(){const g=game;if(g.powerBurst>0)return;g.powerBurst=1.05;g.powerGauge=0;g.power=1;g.stats.powerMax++;fx('POWER MAX・三軍追擊',180,410,'#fff09a');g.entities.forEach((e,index)=>{const dx=g.boss.x-e.x,dy=g.boss.y-e.y,len=Math.max(1,Math.hypot(dx,dy));e.vx=dx/len*(850-index*45);e.vy=dy/len*(850-index*45)})}
function tickCombatChain(dt){const g=game;g.chainWindow=Math.max(0,g.chainWindow-dt);g.skillCooldown=Math.max(0,g.skillCooldown-dt);g.powerBurst=Math.max(0,(g.powerBurst||0)-dt);if(!g.chainWindow)g.chainCount=0;if(g.skillCooldown<=0){const ready=g.skills.findIndex(skill=>skill.gauge>=100);if(ready>=0){const skill=g.skills[ready];skill.gauge=0;g.skillCooldown=.24;g.chainWindow=1.6;g.chainCount++;g.stats.skills++;g.stats.chains=Math.max(g.stats.chains,g.chainCount);const damage=Math.round(g.maxHp*(ready===1?.045:.035));g.hp=Math.max(0,g.hp-damage);g.combo+=ready===1?3:2;g.comboT=2.4;g.break=Math.min(100,g.break+(ready===1?18:10));g.powerGauge=Math.min(100,g.powerGauge+16);fx(`CHAIN ${g.chainCount}・${skill.name}`,g.boss.x,g.boss.y-48,['#78e6b0','#ffb36c','#ffe08a'][ready]);if(g.chainCount>=3){g.stats.fullChains++;g.stats.ultimate++;g.hp=Math.max(0,g.hp-Math.round(g.maxHp*.11));g.break=Math.min(100,g.break+30);g.powerGauge=Math.min(100,g.powerGauge+34);fx('FULL CHAIN・三英追擊',180,350,'#fff3a2');g.chainCount=0}if(g.powerGauge>=100)triggerPowerMax();if(!g.hp)victory()}}}
function tickPlayerLubu(dt){const g=game;if(!g?.practice)return;g.god=Math.max(0,g.god-dt);g.godCd=Math.max(0,g.godCd-dt);g.skillEnergy=Math.min(100,g.skillEnergy+dt*14);g.ultimate=Math.min(100,g.ultimate+dt*8);if(g.comboT<0)g.flying=Math.max(0,g.flying-dt*(save.lubu.breakthrough?0.28:0.55));else g.flying=Math.min(5,g.flying+dt*.7);const s=g.special;if(!s)return;const marks=s.type==='skill'?[.12,.36,.61,.92]:[.12,.32,.53,.74,.95,1.22,1.52],paths=[[75,290,620,-260],[285,260,-650,-220],[180,350,0,-720],[180,175,520,120],[65,240,690,-180],[295,210,-720,-90],[180,390,0,-760],[80,170,740,160],[280,300,-700,-230],[180,95,0,820]];s.time+=dt;while(s.hit<marks.length&&s.time>=marks[s.hit]){const p=paths[(s.hit+(s.type==='ultimate'?3:0))%paths.length],e=g.entities[0],heavy=s.hit===marks.length-1;e.x=p[0];e.y=p[1];e.vx=p[2];e.vy=p[3];const damage=Math.round((heavy?210:92)*(1+g.flying*.06)*(s.type==='ultimate'?1.45:1));g.hp=Math.max(0,g.hp-damage);g.combo++;g.comboT=2.5;g.break=Math.min(100,g.break+(heavy?18:7));g.ghosts.push({x:e.x,y:e.y,life:.5});fx(heavy?`方天畫戟・-${damage}`:`-${damage}`,g.boss.x,g.boss.y-25,heavy?'#fff09a':'#ff7b6c');s.hit++;if(!g.hp){victory();return}}if(s.time>(s.type==='skill'?1.18:1.82)){g.special=null;g.entities[0].x=180;g.entities[0].y=560;if(s.type==='ultimate'&&save.lubu.breakthrough>=5&&g.godCd<=0){g.god=3.6;g.godCd=12}}}
function drawPlayerLubuVfx(){const g=game,ls=document.querySelector('.lubu-status');if(ls)ls.textContent=`${g.practice?`飛將 x${Math.floor(g.flying)}・`:''}CHAIN ${g.chainCount}・${POWER_LABELS[g.power-1]}・${g.skills.map(skill=>Math.floor(skill.gauge)).join('/')}`;if(!g?.practice)return;for(const ghost of g.ghosts)ghost.life-=.025;g.ghosts=g.ghosts.filter(x=>x.life>0)}
function step(dt){
 const g=game,cfg=feel(g);g.time+=dt;g.comboT-=dt;if(g.comboT<0)g.combo=0;g.breakTime-=dt;
 if(g.breakTime<=0&&g.break>=100){g.break=0;g.breakTime=3.5;g.stats.breaks++;g.boss.dashing=false;g.boss.vy=0;g.boss.y=cfg.bossY;g.skills.forEach(skill=>skill.gauge=Math.min(100,skill.gauge+24));fx('BREAK・追擊優先！',180,240,'#fff27c')}
 const ratio=g.hp/g.maxHp;g.phase=ratio>.65?1:ratio>.3?2:3;g.attack-=dt;g.telegraph=Math.max(0,g.telegraph-dt);
 if(g.attack<.75&&!g.telegraph&&g.breakTime<=0&&!g.boss.dashing){g.telegraph=.75-(g.d>10?.16:0);fx(g.phase===3?'天下無雙・三段突進':'飛將突進 ↓',180,190,'#ff7560')}
 if(g.attack<=0&&g.breakTime<=0){g.boss.dir*=-1;g.boss.vx=g.boss.dir*((g.phase===3?250:185)+g.d*2);g.boss.vy=245+(g.phase-1)*35;g.boss.dashing=true;g.attack=Math.max(1.7,4-g.d*.05);g.telegraph=0}
 g.boss.x+=g.boss.vx*dt;g.boss.y+=g.boss.vy*dt;g.boss.vx*=Math.pow(.965,dt*60);if(g.boss.dashing)g.boss.vy*=Math.pow(.985,dt*60);
 if(g.boss.x<82||g.boss.x>278){g.boss.vx*=-1;g.boss.x=Math.max(82,Math.min(278,g.boss.x))}if(g.boss.y>400){g.boss.dashing=false;g.boss.vy=-320}if(g.boss.y<205){g.boss.y=205;g.boss.vy=Math.abs(g.boss.vy)}
 for(let index=0;index<g.entities.length;index++){
  const e=g.entities[index];e.vy+=630*dt;e.x+=e.vx*dt;e.y+=e.vy*dt;
  if(e.x<22||e.x>338){e.vx=-e.vx*cfg.wallRetention;e.x=Math.max(22,Math.min(338,e.x));fx('WALL RETURN',e.x,e.y,'#ffb36c')}
  if(e.y<55){e.vy=Math.abs(e.vy)*cfg.ceilingRetention;e.y=55}
  if(e.y>680){if(index===0&&g.stats.flips&&!g.currentFlipHit&&!g.flipClosed){g.stats.emptySwings++;g.flipClosed=true}e.y=680;e.vy=0;e.vx*=.82;if(index===0)g.airDashReady=true}
  if(e.y>=130&&e.y<=380&&index===0&&!g.currentFlipZone){g.currentFlipZone=true;g.stats.zoneEntries++}
  const dx=e.x-g.boss.x,dy=e.y-g.boss.y;if(e.hitCd<=0&&dx*dx+dy*dy<cfg.bossRadius*cfg.bossRadius)handleContact(e,index,dx,dy)
 }
 g.effects.forEach(effect=>effect.life-=dt);g.effects=g.effects.filter(effect=>effect.life>0)
}
function handleContact(e,index,dx,dy){
 const g=game,cfg=feel(g),speed=Math.hypot(e.vx,e.vy),frontal=g.boss.dashing&&e.vy<0&&g.boss.vy>0,weak=g.telegraph>0||frontal||g.breakTime>0;
 const damage=Math.round((index?15:24)+speed*(index?.045:.065))*(g.breakTime>0?2:1)*(weak?1.35:1);g.hp=Math.max(0,g.hp-damage);g.combo+=index?1:2;g.comboT=2.3;g.break=Math.min(100,g.break+(index?7:weak?20:11));g.powerGauge=Math.min(100,g.powerGauge+(index?9:16));g.skills[index].gauge=Math.min(100,g.skills[index].gauge+(index?30:38));e.hitCd=.22;
 const nx=dx/(Math.hypot(dx,dy)||1),ny=dy/(Math.hypot(dx,dy)||1),ret=g.dashActive>0?.97:cfg.bossRetention;e.vx=nx*Math.max(360,speed*ret);e.vy=ny*Math.max(360,speed*ret);g.boss.vx-=nx*(frontal?180:75);g.boss.vy-=ny*(frontal?160:55);g.boss.recoil=.13;
 if(index===0){if(!g.currentFlipHit){g.currentFlipHit=true;g.stats.directHits++;g.followerTimers=[.08,.16]}if(g.dashActive>0)g.stats.dashHits++}else g.stats.followerHits++;
 if(frontal){g.boss.dashing=false;if(g.perfect){g.break=Math.min(100,g.break+28);g.entities.slice(1).forEach((follower,i)=>{follower.vx=(g.boss.x-follower.x)*(3.3+i*.25);follower.vy=(g.boss.y-follower.y)*(3.3+i*.25)});fx('PERFECT COUNTER・全軍追擊',180,g.boss.y-55,'#fff3a2')}else fx('CLASH!',180,g.boss.y-45,'#ffcf87')}
 fx(`${weak?'WEAK ':''}-${Math.round(damage)}`,g.boss.x,g.boss.y-35,weak?'#fff38a':'#fff');if(g.powerGauge>=100)triggerPowerMax();if(!g.hp)victory()
}
function drawDebug(ctx,g){ctx.save();ctx.fillStyle='rgba(80,200,255,.08)';ctx.fillRect(0,130,360,250);ctx.fillStyle='rgba(255,150,70,.08)';ctx.fillRect(0,562,360,158);ctx.strokeStyle='rgba(130,225,255,.55)';ctx.setLineDash([6,6]);ctx.strokeRect(g.boss.x-72,g.boss.y-72,144,144);ctx.setLineDash([]);ctx.fillStyle='#d9f7ff';ctx.font='11px monospace';ctx.textAlign='left';ctx.fillText(`v ${Math.round(g.entities[0].vx)},${Math.round(g.entities[0].vy)} contact ${g.stats.directHits}/${g.stats.flips}`,8,400);ctx.restore()}
function draw(){
 const g=game,ctx=g.ctx;ctx.clearRect(0,0,360,720);const im=assets.arena;if(im.complete)ctx.drawImage(im,0,0,360,720);else{ctx.fillStyle='#160d10';ctx.fillRect(0,0,360,720)}ctx.fillStyle='rgba(0,0,0,.18)';ctx.fillRect(0,0,360,720);
 if(g.debug)drawDebug(ctx,g);
 if(g.telegraph){ctx.strokeStyle='#ff473b';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(g.boss.x,g.boss.y);ctx.lineTo(g.boss.x+(g.boss.dir||1)*150,g.boss.y+120);ctx.stroke()}
 ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=g.phase===3?.75:g.phase===2?.45:.25;ctx.shadowBlur=g.phase===3?34:20;ctx.shadowColor='#ff382f';ctx.fillStyle=g.phase===3?'#ff342c':'#b52532';ctx.beginPath();ctx.arc(g.boss.x,g.boss.y,58+Math.sin(g.time*5)*6,0,Math.PI*2);ctx.fill();ctx.restore();
 drawBossCharacter(ctx,g.boss,assets,{phase:g.phase,hit:g.boss.recoil>0,broken:g.breakTime>0});
 const ids=g.practice?['lubu','zhangfei','liubei']:['guanyu','zhangfei','liubei'];g.entities.forEach((e,i)=>e.character=ids[i]);
 drawSpriteAfterimages(ctx,g.entities[0],assets,g.leaderTrail||[]);
 for(let i=1;i<g.entities.length;i++){const e=g.entities[i];const ghost=(g.leaderTrail||[]).slice(i===1?5:9);drawSpriteAfterimages(ctx,e,assets,ghost)}
 for(const e of g.entities)drawCharacter(ctx,e,assets,{state:e.skillPose>0?'skill':undefined});
 drawSkillTrails(ctx,g);drawSkillVfx(ctx,g);
 ctx.strokeStyle='#ff7b48';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(18,650);ctx.lineTo(155,680);ctx.moveTo(342,650);ctx.lineTo(205,680);ctx.stroke();
 ctx.font='900 18px system-ui';ctx.textAlign='center';if(!g.debug)for(const f of g.effects){ctx.globalAlpha=f.life;ctx.fillStyle=f.c;ctx.fillText(f.text,f.x,f.y-(1-f.life)*35)}ctx.globalAlpha=1;
 document.querySelector('.bar i').style.width=`${g.hp/g.maxHp*100}%`;document.querySelector('.break i').style.width=`${g.break}%`;document.querySelector('.phase').textContent=['人中呂布','飛將・呂布','天下無雙'][g.phase-1];document.querySelector('.combo').textContent=g.combo?`${g.combo} HIT`:''
}
function victory(){game.over=true;cancelAnimationFrame(raf);const d=game.d,first=d>save.highest;save.highest=Math.max(save.highest,d);save.selected=Math.min(save.highest+1,d+1);let capture='';if(d>=5){const q=d>=15&&first?'legendary':d>=12?'epic':d>=8?'rare':'normal',s={normal:1,rare:2,epic:4,legendary:8}[q];if(!save.lubu.captured){save.lubu={...save.lubu,captured:true,quality:q};capture=`收服 ${q==='legendary'?'傳說・':''}呂布！`}else{save.lubu.souls+=s;capture=`重複收服轉化：呂布魂魄 +${s}`}}save.runs++;persist();app.innerHTML=`<section class="shell"><div class="panel result"><div class="eyebrow">VICTORY</div><img class="hero" src="assets/lubu.png"><h1>${title(d)} 通關</h1><p>${capture||'難度 5 起可收服呂布'}</p><span class="badge">EXP・金錢・神兵符已模擬結算</span><button class="btn primary" data-next>挑戰下一難度</button><button class="btn" data-retry>再次挑戰</button><button class="btn" data-home>返回傳奇挑戰</button></div></section>`;app.querySelector('[data-next]').onclick=start;app.querySelector('[data-retry]').onclick=()=>{save.selected=d;start()};app.querySelector('[data-home]').onclick=home}
var assets={lubu:new Image(),arena:new Image(),guanyu:new Image(),zhangfei:new Image(),liubei:new Image(),lubuPixel:new Image()};assets.lubu.src='assets/lubu.png';assets.arena.src='assets/arena.png';assets.guanyu.src='assets/guanyu-pixel.png';assets.zhangfei.src='assets/zhangfei-pixel.png';assets.liubei.src='assets/liubei-pixel.png';assets.lubuPixel.src='assets/lubu-pixel.png';home();
new MutationObserver(()=>{const result=app.querySelector('.result');if(!result||!save.lubu.captured||result.querySelector('[data-practice]'))return;const b=document.createElement('button');b.className='btn primary';b.dataset.practice='';b.textContent='使用呂布试玩';b.onclick=()=>start(true);result.querySelector('[data-next]')?.before(b)}).observe(app,{childList:true,subtree:true});
