const KEY='qunxiong-world:prototype-lubu-v033';
const app=document.querySelector('#app');
const defaults={highest:0,selected:1,lubu:{captured:false,quality:'normal',souls:0,breakthrough:0},runs:0};
const structuredCloneSafe=o=>JSON.parse(JSON.stringify(o));
const load=()=>{try{return {...structuredCloneSafe(defaults),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredCloneSafe(defaults)}};
let save=load(),raf=0,game=null;
const persist=()=>localStorage.setItem(KEY,JSON.stringify(save));
const title=d=>d>=30?`鬼神・難度${d}`:({5:'強敵',10:'飛將',15:'傳說',20:'天下無雙'}[d]||`難度 ${d}`);
const modifiers=d=>d<21?[]:[['狂暴','神速','鐵壁','背水','霸者'][d%5],...(d%3===0?['神速']:[])].slice(0,2);
const STAR_COSTS=[3,5,8,12,18],STAR_UNLOCKS=['飛將戰意衰減減緩','無雙亂舞追加戟光','飛將破軍追擊強化','鬼神・天下無雙強化','鬼神無雙・極'];
function home(){cancelAnimationFrame(raf);game=null;const lv=save.lubu.breakthrough,cost=STAR_COSTS[lv];app.innerHTML=`<section class="shell"><div class="panel challenge"><div><div class="eyebrow">傳奇挑戰</div><h1>呂布</h1><p class="quote">「人中呂布，馬中赤兔」</p></div><div class="stats"><span>最高通關：${save.highest}</span><span>魂魄：${save.lubu.souls}</span></div><div class="stars">${'★'.repeat(lv)}${'☆'.repeat(5-lv)}</div>${lv<5?`<p>下一突破：${STAR_UNLOCKS[lv]}・魂魄 ${save.lubu.souls} / ${cost}</p><button class="btn" data-break ${save.lubu.souls<cost?'disabled':''}>突破（100%）</button>`:'<p class="eyebrow">鬼神無雙・極 已解鎖</p>'}<div class="difficulty"><button class="btn" data-minus>−</button><strong>${title(save.selected)}</strong><button class="btn" data-plus>＋</button></div>${modifiers(save.selected).length?`<p>異變：${modifiers(save.selected).join('・')}</p>`:''}<button class="btn primary" data-start>開始挑戰</button>${save.lubu.captured?'<button class="btn primary" data-practice>使用呂布试玩</button>':''}<p>擊敗難度 5 可收服；難度 15 首通保證傳說。</p></div></section>`;app.querySelector('[data-minus]').onclick=()=>{save.selected=Math.max(1,save.selected-1);home()};app.querySelector('[data-plus]').onclick=()=>{save.selected=Math.min(save.highest+1,save.selected+1);home()};app.querySelector('[data-start]').onclick=()=>start(false);app.querySelector('[data-practice]')?.addEventListener('click',()=>start(true));app.querySelector('[data-break]')?.addEventListener('click',()=>{if(save.lubu.souls>=cost){save.lubu.souls-=cost;save.lubu.breakthrough++;persist();home()}})}
function start(practice=false){const d=save.selected,scale=1+Math.pow(d-1,.72)*.2;game={d,practice,hp:Math.round((practice?1700:2400)*scale),maxHp:Math.round((practice?1700:2400)*scale),break:0,breakTime:0,combo:0,comboT:0,phase:1,time:0,attack:2.8,telegraph:0,perfect:0,flying:0,skillEnergy:practice?100:0,ultimate:practice?100:0,power:1,special:null,ghosts:[],god:0,godCd:0,entities:[{x:110,y:600,vx:125,vy:-280,c:'#7bd4ff',lubu:practice},{x:190,y:610,vx:-80,vy:-320,c:'#72e29c'},{x:270,y:590,vx:90,vy:-250,c:'#ffb15e'}],boss:{x:180,y:205,vx:0,dir:1},effects:[],over:false};app.innerHTML=`<section class="shell"><div class="battle"><canvas></canvas><div class="hud"><div class="hud-row"><b>${practice?'修羅木樁':'呂布'}・${title(d)}</b><span class="phase">${practice?'玩家呂布實戰':'人中呂布'}</span></div><div class="bar"><i></i></div><div class="hud-row"><small>BREAK</small><b class="combo"></b></div><div class="bar break"><i></i></div><div class="lubu-status">${practice?'飛將 x0・Power I':''}</div></div>${practice?'<div class="skills"><button data-skill>無雙亂舞</button><button data-ult>鬼神・天下無雙</button></div>':''}<div class="tip">點擊／觸控 FLIP・預警瞬間反制</div><div class="flash"></div></div></section>`;const c=app.querySelector('canvas'),dpr=Math.min(3,devicePixelRatio||1);c.width=360*dpr;c.height=720*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);c.addEventListener('pointerdown',flip);app.querySelector('[data-skill]')?.addEventListener('click',e=>{e.stopPropagation();activateSpecial('skill')});app.querySelector('[data-ult]')?.addEventListener('click',e=>{e.stopPropagation();activateSpecial('ultimate')});game.canvas=c;game.ctx=ctx;game.last=performance.now();raf=requestAnimationFrame(loop)}
function activateSpecial(type){const g=game;if(!g?.practice||g.special||(type==='skill'&&g.skillEnergy<100)||(type==='ultimate'&&g.ultimate<100))return;g[type==='skill'?'skillEnergy':'ultimate']=0;g.special={type,time:0,hit:0};fx(type==='skill'?'無雙亂舞！':'鬼神・天下無雙！',180,360,'#ff725b')}
function flip(){if(!game||game.over)return;for(const e of game.entities)if(e.y>480)e.vy=-520-Math.random()*90,e.vx+=(e.x<180?110:-110);if(game.practice){game.power=Math.min(4,1+Math.floor(game.combo/8));const l=game.entities[0];l.vy=-560-game.power*45;l.vx=(l.x<180?1:-1)*(180+game.power*55);fx(['飛將破軍 I','飛將破軍 II','飛將破軍 III','POWER MAX・三軍列陣'][game.power-1],180,560,'#ffbd78');if(game.power===4&&save.lubu.breakthrough>=5&&game.godCd<=0){game.god=3.6;game.godCd=12;fx('鬼神無雙・極',180,430,'#ff493d')}}if(game.telegraph>0){const perfect=game.telegraph<.24;game.perfect=perfect?1:.5;game.break=Math.min(100,game.break+(perfect?42:22));fx(perfect?'PERFECT COUNTER':'COUNTER',180,310,'#fff19a');game.combo+=3;game.attack=3.6;}}
function fx(text,x,y,c='#fff'){game.effects.push({text,x,y,c,life:1})}
function loop(now){if(!game)return;let dt=Math.min(.034,(now-game.last)/1000);game.last=now;tickPlayerLubu(dt);step(dt);draw();drawPlayerLubuVfx();if(!game.over)raf=requestAnimationFrame(loop)}
function tickPlayerLubu(dt){const g=game;if(!g?.practice)return;g.god=Math.max(0,g.god-dt);g.godCd=Math.max(0,g.godCd-dt);g.skillEnergy=Math.min(100,g.skillEnergy+dt*14);g.ultimate=Math.min(100,g.ultimate+dt*8);if(g.comboT<0)g.flying=Math.max(0,g.flying-dt*(save.lubu.breakthrough?0.28:0.55));else g.flying=Math.min(5,g.flying+dt*.7);const s=g.special;if(!s)return;const marks=s.type==='skill'?[.12,.36,.61,.92]:[.12,.32,.53,.74,.95,1.22,1.52],paths=[[75,290,620,-260],[285,260,-650,-220],[180,350,0,-720],[180,175,520,120],[65,240,690,-180],[295,210,-720,-90],[180,390,0,-760],[80,170,740,160],[280,300,-700,-230],[180,95,0,820]];s.time+=dt;while(s.hit<marks.length&&s.time>=marks[s.hit]){const p=paths[(s.hit+(s.type==='ultimate'?3:0))%paths.length],e=g.entities[0],heavy=s.hit===marks.length-1;e.x=p[0];e.y=p[1];e.vx=p[2];e.vy=p[3];const damage=Math.round((heavy?210:92)*(1+g.flying*.06)*(s.type==='ultimate'?1.45:1));g.hp=Math.max(0,g.hp-damage);g.combo++;g.comboT=2.5;g.break=Math.min(100,g.break+(heavy?18:7));g.ghosts.push({x:e.x,y:e.y,life:.5});fx(heavy?`方天畫戟・-${damage}`:`-${damage}`,g.boss.x,g.boss.y-25,heavy?'#fff09a':'#ff7b6c');s.hit++;if(!g.hp){victory();return}}if(s.time>(s.type==='skill'?1.18:1.82)){g.special=null;g.entities[0].x=180;g.entities[0].y=560;if(s.type==='ultimate'&&save.lubu.breakthrough>=5&&g.godCd<=0){g.god=3.6;g.godCd=12}}}
function drawPlayerLubuVfx(){const g=game;if(!g?.practice||!g.ctx)return;const ctx=g.ctx,e=g.entities[0],im=assets.lubu;for(const ghost of g.ghosts){ghost.life-=.025;ctx.globalAlpha=Math.max(0,ghost.life);ctx.drawImage(im,ghost.x-30,ghost.y-42,60,60)}g.ghosts=g.ghosts.filter(x=>x.life>0);ctx.globalAlpha=1;ctx.shadowBlur=g.god?30:18;ctx.shadowColor='#ff321f';ctx.drawImage(im,e.x-31,e.y-43,62,62);ctx.shadowBlur=0;if(g.special){ctx.strokeStyle=g.special.type==='ultimate'?'#ff3328':'#ff8064';ctx.lineWidth=g.special.type==='ultimate'?12:8;ctx.beginPath();ctx.arc(e.x,e.y,38+g.special.hit*4,-1.1,1.2);ctx.stroke()}const ls=document.querySelector('.lubu-status');if(ls)ls.textContent=`飛將 x${Math.floor(g.flying)}・Power ${g.power===4?'MAX':['I','II','III'][g.power-1]}・技 ${Math.floor(g.skillEnergy)}%・奧義 ${Math.floor(g.ultimate)}%${g.god?'・鬼神狀態':''}`}
function step(dt){const g=game;g.time+=dt;g.comboT-=dt;if(g.comboT<0)g.combo=0;g.breakTime-=dt;if(g.breakTime<=0&&g.break>=100){g.break=0;g.breakTime=3.5;fx('BREAK!',180,240,'#fff27c')}const ratio=g.hp/g.maxHp;g.phase=ratio>.65?1:ratio>.3?2:3;g.attack-=dt;g.telegraph=Math.max(0,g.telegraph-dt);if(g.attack<.75&&!g.telegraph&&g.breakTime<=0){g.telegraph=.75-(g.d>10?.16:0);fx(g.phase===3?'天下無雙・三段突進':'飛將突進',180,150,'#ff7560')}if(g.attack<=0&&g.breakTime<=0){g.boss.vx=(g.boss.dir*=(g.phase>1?-1:1))*((g.phase===3?330:240)+g.d*3);g.attack=Math.max(1.6,4-g.d*.05);g.telegraph=0}g.boss.x+=g.boss.vx*dt;g.boss.vx*=.965;if(g.boss.x<90||g.boss.x>270)g.boss.vx*=-1;
 for(const e of g.entities){e.vy+=630*dt;e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.x<22||e.x>338){e.vx*=-.9;e.x=Math.max(22,Math.min(338,e.x))}if(e.y<55){e.vy=Math.abs(e.vy)}if(e.y>690){e.y=690;e.vy=-360}const dx=e.x-g.boss.x,dy=e.y-g.boss.y;if(dx*dx+dy*dy<52*52){const speed=Math.hypot(e.vx,e.vy),weak=(g.telegraph>0||dy<-5),damage=Math.round((18+speed*.055)*(g.breakTime>0?1.8:1)*(weak?1.45:1));g.hp=Math.max(0,g.hp-damage);g.break=Math.min(100,g.break+(weak?10:5));g.combo++;g.comboT=2;e.vy=-Math.abs(e.vy)-80;e.vx+=(dx<0?-130:130);fx(`${weak?'WEAK ':''}-${damage}`,g.boss.x,g.boss.y-35,weak?'#fff38a':'#fff');if(!g.hp)return victory()}}
 g.effects.forEach(x=>x.life-=dt);g.effects=g.effects.filter(x=>x.life>0)}
function draw(){const g=game,ctx=g.ctx,bg=document.querySelector('#arenaImg');ctx.clearRect(0,0,360,720);const im=assets.arena;if(im.complete)ctx.drawImage(im,0,0,360,720);else{ctx.fillStyle='#160d10';ctx.fillRect(0,0,360,720)}ctx.fillStyle='rgba(0,0,0,.18)';ctx.fillRect(0,0,360,720);if(g.telegraph){ctx.strokeStyle='#ff473b';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(g.boss.x,g.boss.y);ctx.lineTo(g.boss.x+(g.boss.dir||1)*150,g.boss.y+120);ctx.stroke()}const boss=assets.lubu;if(boss.complete)ctx.drawImage(boss,g.boss.x-64,g.boss.y-78,128,128);for(const e of g.entities){ctx.shadowBlur=16;ctx.shadowColor=e.c;ctx.fillStyle=e.c;ctx.beginPath();ctx.arc(e.x,e.y,16,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}ctx.strokeStyle='#ff7b48';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(18,650);ctx.lineTo(155,680);ctx.moveTo(342,650);ctx.lineTo(205,680);ctx.stroke();ctx.font='900 18px system-ui';ctx.textAlign='center';for(const f of g.effects){ctx.globalAlpha=f.life;ctx.fillStyle=f.c;ctx.fillText(f.text,f.x,f.y-(1-f.life)*35)}ctx.globalAlpha=1;document.querySelector('.bar i').style.width=`${g.hp/g.maxHp*100}%`;document.querySelector('.break i').style.width=`${g.break}%`;document.querySelector('.phase').textContent=['人中呂布','飛將・呂布','天下無雙'][g.phase-1];document.querySelector('.combo').textContent=g.combo?`${g.combo} HIT`:''}
function victory(){game.over=true;cancelAnimationFrame(raf);const d=game.d,first=d>save.highest;save.highest=Math.max(save.highest,d);save.selected=Math.min(save.highest+1,d+1);let capture='';if(d>=5){const q=d>=15&&first?'legendary':d>=12?'epic':d>=8?'rare':'normal',s={normal:1,rare:2,epic:4,legendary:8}[q];if(!save.lubu.captured){save.lubu={...save.lubu,captured:true,quality:q};capture=`收服 ${q==='legendary'?'傳說・':''}呂布！`}else{save.lubu.souls+=s;capture=`重複收服轉化：呂布魂魄 +${s}`}}save.runs++;persist();app.innerHTML=`<section class="shell"><div class="panel result"><div class="eyebrow">VICTORY</div><img class="hero" src="assets/lubu.png"><h1>${title(d)} 通關</h1><p>${capture||'難度 5 起可收服呂布'}</p><span class="badge">EXP・金錢・神兵符已模擬結算</span><button class="btn primary" data-next>挑戰下一難度</button><button class="btn" data-retry>再次挑戰</button><button class="btn" data-home>返回傳奇挑戰</button></div></section>`;app.querySelector('[data-next]').onclick=start;app.querySelector('[data-retry]').onclick=()=>{save.selected=d;start()};app.querySelector('[data-home]').onclick=home}
var assets={lubu:new Image(),arena:new Image()};assets.lubu.src='assets/lubu.png';assets.arena.src='assets/arena.png';home();
new MutationObserver(()=>{const result=app.querySelector('.result');if(!result||!save.lubu.captured||result.querySelector('[data-practice]'))return;const b=document.createElement('button');b.className='btn primary';b.dataset.practice='';b.textContent='使用呂布试玩';b.onclick=()=>start(true);result.querySelector('[data-next]')?.before(b)}).observe(app,{childList:true,subtree:true});
