const KEY='qunxiong-world:prototype-lubu-v033';
const app=document.querySelector('#app');
const defaults={highest:0,selected:1,lubu:{captured:false,quality:'normal',souls:0,breakthrough:0},runs:0};
const structuredCloneSafe=o=>JSON.parse(JSON.stringify(o));
const load=()=>{try{return {...structuredCloneSafe(defaults),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredCloneSafe(defaults)}};
let save=load(),raf=0,game=null;
const persist=()=>localStorage.setItem(KEY,JSON.stringify(save));
const title=d=>d>=30?`鬼神・難度${d}`:({5:'強敵',10:'飛將',15:'傳說',20:'天下無雙'}[d]||`難度 ${d}`);
const modifiers=d=>d<21?[]:[['狂暴','神速','鐵壁','背水','霸者'][d%5],...(d%3===0?['神速']:[])].slice(0,2);
function home(){cancelAnimationFrame(raf);game=null;app.innerHTML=`<section class="shell"><div class="panel challenge"><div><div class="eyebrow">傳奇挑戰</div><h1>呂布</h1><p class="quote">「人中呂布，馬中赤兔」</p></div><div class="stats"><span>最高通關：${save.highest}</span><span>魂魄：${save.lubu.souls}・突破 ★${save.lubu.breakthrough}</span></div><div class="difficulty"><button class="btn" data-minus>−</button><strong>${title(save.selected)}</strong><button class="btn" data-plus>＋</button></div>${modifiers(save.selected).length?`<p>異變：${modifiers(save.selected).join('・')}</p>`:''}<button class="btn primary" data-start>開始挑戰</button><p>擊敗難度 5 可收服；難度 15 首通保證傳說。</p></div></section>`;app.querySelector('[data-minus]').onclick=()=>{save.selected=Math.max(1,save.selected-1);home()};app.querySelector('[data-plus]').onclick=()=>{save.selected=Math.min(save.highest+1,save.selected+1);home()};app.querySelector('[data-start]').onclick=start;}
function start(){const d=save.selected,scale=1+Math.pow(d-1,.72)*.2;game={d,hp:Math.round(2400*scale),maxHp:Math.round(2400*scale),break:0,breakTime:0,combo:0,comboT:0,phase:1,time:0,attack:2.8,telegraph:0,perfect:0,entities:[{x:110,y:600,vx:125,vy:-280,c:'#7bd4ff'},{x:190,y:610,vx:-80,vy:-320,c:'#72e29c'},{x:270,y:590,vx:90,vy:-250,c:'#ffb15e'}],boss:{x:180,y:205,vx:0,dir:1},effects:[],over:false};app.innerHTML=`<section class="shell"><div class="battle"><canvas></canvas><div class="hud"><div class="hud-row"><b>呂布・${title(d)}</b><span class="phase">人中呂布</span></div><div class="bar"><i></i></div><div class="hud-row"><small>BREAK</small><b class="combo"></b></div><div class="bar break"><i></i></div></div><div class="tip">點擊／觸控 FLIP・預警瞬間反制</div><div class="flash"></div></div></section>`;const c=app.querySelector('canvas'),box=c.getBoundingClientRect(),dpr=Math.min(3,devicePixelRatio||1);c.width=360*dpr;c.height=720*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);c.addEventListener('pointerdown',flip);game.canvas=c;game.ctx=ctx;game.last=performance.now();raf=requestAnimationFrame(loop)}
function flip(){if(!game||game.over)return;for(const e of game.entities)if(e.y>480)e.vy=-520-Math.random()*90,e.vx+=(e.x<180?110:-110);if(game.telegraph>0){const perfect=game.telegraph<.24;game.perfect=perfect?1:.5;game.break=Math.min(100,game.break+(perfect?42:22));fx(perfect?'PERFECT COUNTER':'COUNTER',180,310,'#fff19a');game.combo+=3;game.attack=3.6;}}
function fx(text,x,y,c='#fff'){game.effects.push({text,x,y,c,life:1})}
function loop(now){if(!game)return;let dt=Math.min(.034,(now-game.last)/1000);game.last=now;step(dt);draw();if(!game.over)raf=requestAnimationFrame(loop)}
function step(dt){const g=game;g.time+=dt;g.comboT-=dt;if(g.comboT<0)g.combo=0;g.breakTime-=dt;if(g.breakTime<=0&&g.break>=100){g.break=0;g.breakTime=3.5;fx('BREAK!',180,240,'#fff27c')}const ratio=g.hp/g.maxHp;g.phase=ratio>.65?1:ratio>.3?2:3;g.attack-=dt;g.telegraph=Math.max(0,g.telegraph-dt);if(g.attack<.75&&!g.telegraph&&g.breakTime<=0){g.telegraph=.75-(g.d>10?.16:0);fx(g.phase===3?'天下無雙・三段突進':'飛將突進',180,150,'#ff7560')}if(g.attack<=0&&g.breakTime<=0){g.boss.vx=(g.boss.dir*=(g.phase>1?-1:1))*((g.phase===3?330:240)+g.d*3);g.attack=Math.max(1.6,4-g.d*.05);g.telegraph=0}g.boss.x+=g.boss.vx*dt;g.boss.vx*=.965;if(g.boss.x<90||g.boss.x>270)g.boss.vx*=-1;
 for(const e of g.entities){e.vy+=630*dt;e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.x<22||e.x>338){e.vx*=-.9;e.x=Math.max(22,Math.min(338,e.x))}if(e.y<55){e.vy=Math.abs(e.vy)}if(e.y>690){e.y=690;e.vy=-360}const dx=e.x-g.boss.x,dy=e.y-g.boss.y;if(dx*dx+dy*dy<52*52){const speed=Math.hypot(e.vx,e.vy),weak=(g.telegraph>0||dy<-5),damage=Math.round((18+speed*.055)*(g.breakTime>0?1.8:1)*(weak?1.45:1));g.hp=Math.max(0,g.hp-damage);g.break=Math.min(100,g.break+(weak?10:5));g.combo++;g.comboT=2;e.vy=-Math.abs(e.vy)-80;e.vx+=(dx<0?-130:130);fx(`${weak?'WEAK ':''}-${damage}`,g.boss.x,g.boss.y-35,weak?'#fff38a':'#fff');if(!g.hp)return victory()}}
 g.effects.forEach(x=>x.life-=dt);g.effects=g.effects.filter(x=>x.life>0)}
function draw(){const g=game,ctx=g.ctx,bg=document.querySelector('#arenaImg');ctx.clearRect(0,0,360,720);const im=assets.arena;if(im.complete)ctx.drawImage(im,0,0,360,720);else{ctx.fillStyle='#160d10';ctx.fillRect(0,0,360,720)}ctx.fillStyle='rgba(0,0,0,.18)';ctx.fillRect(0,0,360,720);if(g.telegraph){ctx.strokeStyle='#ff473b';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(g.boss.x,g.boss.y);ctx.lineTo(g.boss.x+(g.boss.dir||1)*150,g.boss.y+120);ctx.stroke()}const boss=assets.lubu;if(boss.complete)ctx.drawImage(boss,g.boss.x-64,g.boss.y-78,128,128);for(const e of g.entities){ctx.shadowBlur=16;ctx.shadowColor=e.c;ctx.fillStyle=e.c;ctx.beginPath();ctx.arc(e.x,e.y,16,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}ctx.strokeStyle='#ff7b48';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(18,650);ctx.lineTo(155,680);ctx.moveTo(342,650);ctx.lineTo(205,680);ctx.stroke();ctx.font='900 18px system-ui';ctx.textAlign='center';for(const f of g.effects){ctx.globalAlpha=f.life;ctx.fillStyle=f.c;ctx.fillText(f.text,f.x,f.y-(1-f.life)*35)}ctx.globalAlpha=1;document.querySelector('.bar i').style.width=`${g.hp/g.maxHp*100}%`;document.querySelector('.break i').style.width=`${g.break}%`;document.querySelector('.phase').textContent=['人中呂布','飛將・呂布','天下無雙'][g.phase-1];document.querySelector('.combo').textContent=g.combo?`${g.combo} HIT`:''}
function victory(){game.over=true;cancelAnimationFrame(raf);const d=game.d,first=d>save.highest;save.highest=Math.max(save.highest,d);save.selected=Math.min(save.highest+1,d+1);let capture='';if(d>=5){const q=d>=15&&first?'legendary':d>=12?'epic':d>=8?'rare':'normal',s={normal:1,rare:2,epic:4,legendary:8}[q];if(!save.lubu.captured){save.lubu={...save.lubu,captured:true,quality:q};capture=`收服 ${q==='legendary'?'傳說・':''}呂布！`}else{save.lubu.souls+=s;capture=`重複收服轉化：呂布魂魄 +${s}`}}save.runs++;persist();app.innerHTML=`<section class="shell"><div class="panel result"><div class="eyebrow">VICTORY</div><img class="hero" src="assets/lubu.png"><h1>${title(d)} 通關</h1><p>${capture||'難度 5 起可收服呂布'}</p><span class="badge">EXP・金錢・神兵符已模擬結算</span><button class="btn primary" data-next>挑戰下一難度</button><button class="btn" data-retry>再次挑戰</button><button class="btn" data-home>返回傳奇挑戰</button></div></section>`;app.querySelector('[data-next]').onclick=start;app.querySelector('[data-retry]').onclick=()=>{save.selected=d;start()};app.querySelector('[data-home]').onclick=home}
var assets={lubu:new Image(),arena:new Image()};assets.lubu.src='assets/lubu.png';assets.arena.src='assets/arena.png';home();
