import { createChapter3BossMember } from './data.js?v=v032a-art-1';
import { applyLeaderRarity, getBossRarity, getCaptureRate } from './boss-progression.js?v=v032a-art-1';

export const CHAPTER3_AREAS=['desolateVillage','loessSlope','thunderValley','yellowHeavenAltar'];
export const CHAPTER3_BOSSES={
  'storm-warden':{name:'雷谷守將・韓忠',enemyId:'stormWardenBoss',drops:['thunderBow','thunderArmor','thunderBead']},
  'earth-brute':{name:'黃天力帥・鄧茂',enemyId:'earthBruteBoss',drops:['earthBreakerHammer','skyRitualArmor','yellowHeavenSeal']},
  'yellow-demon-general':{name:'黃巾妖將・程遠志',enemyId:'yellowDemonGeneralBoss',drops:['earthBreakerHammer','skyRitualArmor','yellowHeavenSeal']},
  'nether-phoenix':{name:'幽冥鳳凰',enemyId:'netherPhoenixBoss',drops:['phoenixFeatherBlade','phoenixRobe','phoenixEmber']}
};
export const WORLD_ANOMALIES={
  flame:{name:'赤焰天變',description:'火勢助長攻伐，金錢與裝備掉落小幅提高。',gold:1.15,drop:.04},
  thunder:{name:'九幽雷變',description:'雷霆加速戰局，EXP 與技能能量小幅提高。',exp:1.15,skill:1.1},
  turtle:{name:'玄武地變',description:'大地厚重，敵我防禦提高，兵符掉落小幅增加。',defense:1.08,talisman:.05},
  yellow:{name:'黃天祭變',description:'祭壇共鳴，第三章 Boss 與秘境出現率提高。',boss:.05,dungeon:.04}
};
const rankRecord=raw=>({encountered:Boolean(raw?.encountered),defeated:Boolean(raw?.defeated),captured:Boolean(raw?.captured)});
export const isChapter3Area=id=>CHAPTER3_AREAS.includes(id);
export const isChapter3BossKind=id=>Boolean(CHAPTER3_BOSSES[id]);
export function normalizeChapter3(raw={}){return{unlocked:Boolean(raw.unlocked),cleared:Boolean(raw.cleared),phoenixUnlocked:Boolean(raw.phoenixUnlocked),phoenixDefeated:Boolean(raw.phoenixDefeated),areas:Object.fromEntries(CHAPTER3_AREAS.map(id=>[id,Boolean(raw.areas?.[id])])),bossPity:Object.fromEntries(CHAPTER3_AREAS.map(id=>[id,Math.max(0,Number(raw.bossPity?.[id])||0)])),intrusionPity:Math.max(0,Number(raw.intrusionPity)||0)};}
export function normalizeChapter3Codex(raw={}){return Object.fromEntries(Object.keys(CHAPTER3_BOSSES).map(id=>[id,{ranks:Object.fromEntries([1,2,3,4,5].map(rank=>[rank,rankRecord(raw[id]?.ranks?.[rank])])),encounters:Math.max(0,Number(raw[id]?.encounters)||0),defeats:Math.max(0,Number(raw[id]?.defeats)||0),captures:Math.max(0,Number(raw[id]?.captures)||0),drops:Object.fromEntries(CHAPTER3_BOSSES[id].drops.map(drop=>[drop,Boolean(raw[id]?.drops?.[drop])]))}]));}
export function recordChapter3Boss(state,kind,rank,event){const entry=state.chapter3Codex?.[kind];if(!entry)return;entry.ranks[rank]||=rankRecord();entry.ranks[rank].encountered=true;if(event==='encounter')entry.encounters++;if(event==='defeat'){entry.ranks[rank].defeated=true;entry.defeats++;}if(event==='capture'){entry.ranks[rank].captured=true;entry.captures++;}}
export function recordChapter3Drop(state,itemId){for(const [kind,profile]of Object.entries(CHAPTER3_BOSSES))if(profile.drops.includes(itemId))state.chapter3Codex[kind].drops[itemId]=true;}
export function ensureWorldAnomaly(state,date=new Date()){const day=typeof date==='string'?date:date.toLocaleDateString('sv-SE'),ids=Object.keys(WORLD_ANOMALIES),hash=[...day].reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,7),id=ids[hash%ids.length];if(state.worldAnomaly?.date!==day)state.worldAnomaly={date,id};return WORLD_ANOMALIES[state.worldAnomaly.id]||WORLD_ANOMALIES.flame;}
export function normalizeWorldAnomaly(raw={}){const state={date:typeof raw.date==='string'?raw.date:'',id:WORLD_ANOMALIES[raw.id]?raw.id:'flame'};return state;}
export function rollWorldBossIntrusion(state,rng=Math.random){if(!isChapter3Area(state.screen)||state.battle||state.ui?.bossWarning||state.ui?.worldBossIntrusion)return null;state.chapter3.intrusionPity++;const event=ensureWorldAnomaly(state),chance=.018+(state.chapter3.intrusionPity>=35?.05:0)+(event===WORLD_ANOMALIES.yellow?.015:0);if(rng()>=chance)return null;state.chapter3.intrusionPity=0;const unlocked=['crimsonTiger',state.worldBosses?.netherThunder?.unlocked?'netherThunder':null,state.worldBosses?.basaltTurtle?.unlocked?'basaltTurtle':null].filter(Boolean),bossId=unlocked[Math.floor(rng()*unlocked.length)];state.ui.worldBossIntrusion={bossId,sourceScreen:state.screen};state.exploration.auto=false;state.exploration.active=false;state.notice='天地異變撕裂戰場，世界王突然入侵！';return state.ui.worldBossIntrusion;}
function finishRecruit(state,battle,success,profile){const final=battle.bossKind==='yellow-demon-general',phoenix=battle.bossKind==='nether-phoenix';if(final){state.chapter3.cleared=true;state.chapter3.phoenixUnlocked=true;state.progress.chapter3Cleared=true;state.worldBosses.basaltTurtle.unlocked=true;state.ui.chapter3Complete=true;}if(phoenix)state.chapter3.phoenixDefeated=true;state.battle=null;state.ui.bossWarning=false;state.ui.bossRarityRank=null;state.exploration.auto=false;state.exploration.active=false;state.screen=battle.areaId||'yellowHeavenAltar';state.location=state.screen==='desolateVillage'?'荒村':state.screen==='loessSlope'?'黃土坡':state.screen==='thunderValley'?'雷鳴谷':'黃天祭壇';state.notice=`${success?`${profile.name}已加入武將名冊！`:`你放棄或未能招降${profile.name}，全部戰利品保留。`}${final?' 第三章・黃天崛起完成！':''}`;}
export function recruitChapter3Boss(state,rng=Math.random){const battle=state.battle,kind=battle?.bossKind,profile=CHAPTER3_BOSSES[kind];if(!battle?.awaitingRecruit||!profile)return false;const rank=battle.bossRarityRank||1,existing=[...state.party,...state.roster].find(m=>m?.id===kind),rate=kind==='nether-phoenix'?.12:getCaptureRate(rank),success=!existing&&rank===1&&kind!=='nether-phoenix'?true:rng()<rate;recordChapter3Boss(state,kind,rank,success?'capture':'failure');if(success&&!existing){const member=createChapter3BossMember(kind);applyLeaderRarity(member,rank);state.roster.push(member);state.equipment[kind]||={weapon:null,armor:null,accessory:null};}else if(success&&rank>(existing?.rarityRank||1))applyLeaderRarity(existing,rank);finishRecruit(state,battle,success,profile);return success;}
export function spareChapter3Boss(state){const battle=state.battle,profile=CHAPTER3_BOSSES[battle?.bossKind];if(!battle?.awaitingRecruit||!profile)return false;finishRecruit(state,battle,false,profile);return true;}
