import { ITEMS, createYellowBossMember } from './data.js?v=v022-pinball-prototype-1';
import { applyLeaderRarity, getBossRarity, getCaptureRate } from './boss-progression.js?v=v022-pinball-prototype-1';

export const CHAPTER2_BOSSES={
  'yellow-captain':{name:'黃巾校尉',enemyId:'yellowCaptainBoss',role:'坦克',drops:['captainBlade','yellowHeavyArmor','captainToken'],resonance:'鐵壁統領'},
  'yellow-commander':{name:'黃巾渠帥',enemyId:'yellowCommanderBoss',role:'物理輸出',drops:['commanderSpear','breakerArmor','commanderTalisman'],resonance:'破軍統領'},
  'zhang-bao':{name:'張寶',enemyId:'zhangBaoBoss',role:'群攻',drops:['earthLordSword','yellowSkyRobe','earthLordSeal'],resonance:'地公之威'}
};
const rankRecord=raw=>({encountered:Boolean(raw?.encountered),defeated:Boolean(raw?.defeated),captured:Boolean(raw?.captured)});
export function normalizeChapter2(raw={}){return{unlocked:Boolean(raw.unlocked),cleared:Boolean(raw.cleared),areas:{yellowRoad:Boolean(raw.areas?.yellowRoad),yellowCamp:Boolean(raw.areas?.yellowCamp),yellowFortress:Boolean(raw.areas?.yellowFortress)},bossPity:{yellowRoad:Math.max(0,Number(raw.bossPity?.yellowRoad)||0),yellowCamp:Math.max(0,Number(raw.bossPity?.yellowCamp)||0),yellowFortress:Math.max(0,Number(raw.bossPity?.yellowFortress)||0)}};}
export function normalizeChapter2Codex(raw={}){return Object.fromEntries(Object.keys(CHAPTER2_BOSSES).map(id=>[id,{ranks:Object.fromEntries([1,2,3,4,5].map(rank=>[rank,rankRecord(raw[id]?.ranks?.[rank])])),encounters:Math.max(0,Number(raw[id]?.encounters)||0),defeats:Math.max(0,Number(raw[id]?.defeats)||0),captures:Math.max(0,Number(raw[id]?.captures)||0),captureFailures:Math.max(0,Number(raw[id]?.captureFailures)||0),drops:Object.fromEntries(CHAPTER2_BOSSES[id].drops.map(drop=>[drop,Boolean(raw[id]?.drops?.[drop])]))}]));}
export function recordChapter2Boss(state,kind,rank,event){const entry=state.chapter2Codex?.[kind];if(!entry)return;entry.ranks[rank].encountered=true;if(event==='encounter')entry.encounters+=1;if(event==='defeat'){entry.ranks[rank].defeated=true;entry.defeats+=1;}if(event==='capture'){entry.ranks[rank].captured=true;entry.captures+=1;}if(event==='failure')entry.captureFailures+=1;}
export function recordChapter2Drop(state,itemId){for(const [kind,profile]of Object.entries(CHAPTER2_BOSSES))if(profile.drops.includes(itemId))state.chapter2Codex[kind].drops[itemId]=true;}
export function getChapter2Resonance(state,memberOrId){const member=typeof memberOrId==='string'?[...state.party,...state.roster].find(unit=>unit?.id===memberOrId):memberOrId;const result={mightPct:0,defensePct:0,hpPct:0,speedPct:0,skillPct:0,set:null};const profile=CHAPTER2_BOSSES[member?.id];if(!profile)return result;const slots=state.equipment?.[member.id]||{},owned=Object.values(slots).filter(id=>profile.drops.includes(id)).length;if(owned<3)return result;result.set=profile.resonance;if(member.id==='yellow-captain'){result.defensePct=.16;result.hpPct=.12;}if(member.id==='yellow-commander'){result.mightPct=.16;result.speedPct=.08;}if(member.id==='zhang-bao'){result.mightPct=.08;result.skillPct=.20;}return result;}
function finishDungeonIfNeeded(state,battle){if(!battle?.dungeon)return;state.dungeon.active=false;state.dungeon.floor=0;state.dungeon.pendingAdvance=false;state.dungeon.loot=[];state.ui.dungeonProgress=false;}
export function recruitChapter2Boss(state,rng=Math.random){const battle=state.battle,kind=battle?.bossKind,profile=CHAPTER2_BOSSES[kind];if(!battle?.awaitingRecruit||!profile)return false;const rank=battle.bossRarityRank||1,existing=[...state.party,...state.roster].find(member=>member?.id===kind),success=!existing&&rank===1?true:rng()<getCaptureRate(rank);recordChapter2Boss(state,kind,rank,success?'capture':'failure');if(success&&!existing){const member=createYellowBossMember(kind);applyLeaderRarity(member,rank);state.roster.push(member);state.equipment[kind]||={weapon:null,armor:null,accessory:null};}else if(success&&rank>(existing.rarityRank||1))applyLeaderRarity(existing,rank);else if(success)state.gold+=100*rank;const completedZhangBao=kind==='zhang-bao';finishDungeonIfNeeded(state,battle);state.battle=null;state.ui.bossWarning=false;state.ui.bossRarityRank=null;state.exploration.auto=false;state.exploration.active=false;if(completedZhangBao){state.chapter2.cleared=true;state.progress.chapter2Cleared=true;state.worldBosses.netherThunder.unlocked=true;state.ui.chapter2Complete=true;}state.screen=battle.dungeon?(state.dungeon.sourceScreen||'yellowFortress'):battle.areaId;state.location=state.screen==='yellowRoad'?'黃巾荒道':state.screen==='yellowCamp'?'黃巾營地':'黃巾主寨';state.notice=success?`${getBossRarity(rank).stars} ${profile.name}已加入武將名冊！${completedZhangBao?' 第二章・黃巾之亂完成！':''}`:`${profile.name}拒絕招降並離開，全部戰利品保留。${completedZhangBao?' 第二章・黃巾之亂完成！':''}`;return success;}
export function spareChapter2Boss(state){const battle=state.battle;if(!battle?.awaitingRecruit||!battle.bossKind)return false;const kind=battle.bossKind,completed=kind==='zhang-bao';if(completed){state.chapter2.cleared=true;state.progress.chapter2Cleared=true;state.worldBosses.netherThunder.unlocked=true;state.ui.chapter2Complete=true;}finishDungeonIfNeeded(state,battle);state.battle=null;state.ui.bossWarning=false;state.ui.bossRarityRank=null;state.screen=battle.dungeon?(state.dungeon.sourceScreen||'yellowFortress'):battle.areaId;state.location=state.screen==='yellowRoad'?'黃巾荒道':state.screen==='yellowCamp'?'黃巾營地':'黃巾主寨';state.notice=`你放棄招降${CHAPTER2_BOSSES[kind].name}，戰利品全部保留。${completed?' 第二章・黃巾之亂完成！':''}`;return true;}
export function getChapter2CodexCompletion(state){let done=0,total=0;for(const entry of Object.values(state.chapter2Codex||{})){for(const rank of Object.values(entry.ranks)){done+=Number(rank.encountered)+Number(rank.defeated)+Number(rank.captured);total+=3;}done+=Object.values(entry.drops).filter(Boolean).length;total+=Object.keys(entry.drops).length;}return{done,total,pct:total?Math.round(done/total*100):0};}
