// 狩獵核心：獨立管理地圖進度、Boss 收服、夥伴與裝備實例，便於日後擴充。
const maps=[
  {id:'plains',name:'村外平原',level:'Lv.1～4',need:1,threshold:12,normal:['流民','野狼','山賊'],elite:'荒原頭目',boss:'平原盜首',hidden:'狂野豬王',drop:'平原戰刀'},
  {id:'blackwind',name:'黑風森林',level:'Lv.5～10',need:5,threshold:20,normal:['黑風狼','山賊','毒蛇'],elite:'黑風頭目',boss:'黑風寨主',hidden:'魔化虎王',drop:'黑風戰刀'},
  {id:'yellow',name:'黃巾營地',level:'Lv.10～16',need:10,threshold:28,normal:['黃巾兵','黃巾弓手','流民'],elite:'黃巾校尉',boss:'黃巾將領',hidden:'太平妖師',drop:'黃巾鎧甲'},
  {id:'well',name:'古井洞窟',level:'Lv.16～23',need:16,threshold:36,normal:['洞窟蝙蝠','毒蛇','石妖'],elite:'洞窟守衛',boss:'毒龍王',hidden:'井底魔猿',drop:'毒龍護符'},
  {id:'hulao',name:'虎牢關外圍',level:'Lv.23～30',need:23,threshold:45,normal:['西涼鐵騎','猛虎','關外賊兵'],elite:'關外戰將',boss:'虎牢戰將',hidden:'戰神殘影',drop:'虎牢戰戟'}
];
const rarity=['普通','優良','稀有','史詩','傳說','神器'];
const affixes=['攻擊','防禦','生命','速度','爆擊率','爆擊傷害','吸血','經驗','金幣','掉寶','Boss傷害','精英傷害','收服成功率','夥伴傷害','自動回血','火焰傷害','中毒傷害','反擊','閃避','技能傷害'];
const seals={普通:1,精英:2,稀有:3,傳說:5};
const quality=()=>{const r=Math.random();return r<.55?0:r<.8?1:r<.93?2:r<.985?3:r<.997?4:5;};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const log=(s,text,rare=false)=>{s.log.push(`${rare?'✦ ':''}${text}`);s.log=s.log.slice(-120);};
export const huntMaps=maps;
export function migrateHunt(state){
  const old=state.hunting||{};state.version=Math.max(state.version||1,3);
  state.hunting={mapId:maps.some(m=>m.id===old.mapId)?old.mapId:'plains',maps:{},totalKills:old.totalKills||0,bossKills:old.bossKills||0,captures:old.captures||0,rank:old.rank||'青銅獵人',...old};
  maps.forEach(m=>state.hunting.maps[m.id]={kills:0,bossDefeated:false,hiddenDefeated:false,...(old.maps?.[m.id]||{})});
  state.hunting.auto={heal:true,healBelow:45,returnBelow:20,stopBoss:true,autoBoss:false,autoCapture:false,captureItem:'normal',speed:1,logMode:'brief',...old.auto};
  state.captureItems={normal:3,advanced:1,legendary:0,...(state.captureItems||{})};
  state.bossPartners=(state.bossPartners||state.bossSouls||[]).map(x=>({id:x.id,name:x.name,rarity:x.rarity||'普通',level:x.level||1,exp:x.exp||0,stars:x.stars||x.rank||1,hp:x.hp||120,attack:x.attack||12,defense:x.defense||6,speed:x.speed||10,skill:x.skill||'霸王斬',passive:x.passive||'協戰',souls:x.souls||x.seals||0,deployed:!!x.deployed,...x}));
  state.gearInstances=(state.gearInstances||[]).map(x=>x.instanceId?x:{...x,instanceId:`legacy-${Date.now()}-${Math.random().toString(36).slice(2,7)}`});state.instanceEquipment={weapon:null,armor:null,...(state.instanceEquipment||{})};
  return state;
}
export const mapOf=s=>maps.find(m=>m.id===s.hunting.mapId)||maps[0];
export const mapOpen=(s,m)=>{const i=maps.indexOf(m);return i===0||(s.player.level>=m.need&&s.hunting.maps[maps[i-1].id].bossDefeated);};
function foe(s){const m=mapOf(s),p=s.player,progress=s.hunting.maps[m.id];let kind='normal',name=m.normal[Math.floor(Math.random()*m.normal.length)],boss=false,hidden=false;if(progress.kills>=m.threshold){kind='boss';name=m.boss;boss=true;}else if(progress.kills>=50&&Math.random()<.06){kind='boss';name=m.hidden;boss=true;hidden=true;}else if(Math.random()<.1){kind='elite';name=m.elite;}const scale=p.level+(maps.indexOf(m)*4),hp=(kind==='boss'?150:kind==='elite'?70:38)+scale*(kind==='boss'?22:kind==='elite'?11:7);return {id:`enemy-${Date.now()}`,name,kind,boss,hidden,maxHp:hp,hp,attack:6+scale*(kind==='boss'?3:2),defense:2+Math.floor(scale/2),exp:kind==='boss'?120+scale*12:kind==='elite'?30+scale*8:15+scale*5,gold:kind==='boss'?100+scale*12:10+scale*4,rarity:kind==='boss'?(hidden?'傳說':'普通'):(kind==='elite'?'精英':'普通')};}
function gear(s){const q=quality(),slot=Math.random()<.5?'weapon':'armor',level=s.player.level,base=slot==='weapon'?{attack:5+level*3,defense:0}:{attack:0,defense:3+level*2},count=[0,1,2,3,4,4][q],item={instanceId:`gear-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,templateId:`${slot}-${level}`,name:`${mapOf(s).drop}${slot==='weapon'?'':'護甲'}`,slot,quality:rarity[q],level,baseStats:base,affixes:Array.from({length:count},()=>`${affixes[Math.floor(Math.random()*affixes.length)]} +${2+Math.floor(Math.random()*7)}%`),locked:false,obtainedAt:Date.now()};s.gearInstances.push(item);return item;}
function level(s,exp){s.player.exp+=exp;while(s.player.exp>=80+s.player.level*45){s.player.exp-=80+s.player.level*45;s.player.level++;s.player.maxHp+=20;s.player.hp=s.player.maxHp;s.player.attack+=2;s.player.defense++;log(s,`升至 Lv.${s.player.level}！`,true);}}
export function huntStep(s){migrateHunt(s);const a=s.hunting.auto,p=s.player;if(p.hp/p.maxHp*100<=a.returnBelow){s.exploration.running=false;p.hp=Math.ceil(p.maxHp*.7);log(s,'生命過低，已返回安全地點。');return;}if(a.heal&&p.hp/p.maxHp*100<=a.healBelow){const potion=s.inventory.find(x=>x.id==='potion'&&x.quantity>0);if(potion){potion.quantity--;p.hp=Math.min(p.maxHp,p.hp+80);log(s,'自動使用藥草。');}}
  let e=s.exploration.enemy;if(!e){e=foe(s);s.exploration.enemy=e;log(s,`遭遇${e.boss?'Boss ':''}${e.name}！`,e.boss);return;}if(e.boss&&a.stopBoss&&!a.autoBoss&&!a.autoCapture){s.exploration.running=false;log(s,`${e.name}出現，已暫停。`,true);return;}if(e.boss&&e.hp/e.maxHp<=.2){e.catchable=true;if(a.autoCapture)return attemptCapture(s,a.captureItem);if(a.stopBoss&&!a.autoBoss){s.exploration.running=false;log(s,`${e.name}可收服，已暫停。`,true);}return;}
  const partner=s.bossPartners.find(x=>x.deployed),damage=Math.max(1,p.attack+(partner?.attack||0)-e.defense+Math.floor(Math.random()*4));e.hp-=damage;log(s,`對 ${e.name} 造成 ${damage} 傷害。`);if(e.hp<=0){const m=mapOf(s),prog=s.hunting.maps[m.id];p.gold+=e.gold;level(s,e.exp);s.hunting.totalKills++;if(e.boss){prog.kills=0;prog.bossDefeated=true;if(e.hidden)prog.hiddenDefeated=true;s.hunting.bossKills++;}else prog.kills++;const drop=Math.random()<.65?gear(s):null;log(s,`擊敗 ${e.name}，獲得 ${e.exp} EXP、${e.gold} 金。${drop?` 掉落【${drop.quality}】${drop.name}。`:''}`,drop&&rarity.indexOf(drop.quality)>=2);s.exploration.enemy=null;return;}p.hp=Math.max(0,p.hp-Math.max(1,e.attack-p.defense));if(!p.hp){p.hp=Math.ceil(p.maxHp*.5);s.exploration.enemy=null;s.exploration.running=false;log(s,'戰敗後已返回安全地點。');}}
export function attemptCapture(s,item){const e=s.exploration.enemy;if(!e?.boss||e.hp/e.maxHp>.2)return {ok:false,message:'Boss 尚未進入可收服狀態。'};if(!s.captureItems[item])return {ok:false,message:'收服符不足。'};s.captureItems[item]--;const extra=item==='legendary'?45:item==='advanced'?25:10,low=e.hp/e.maxHp<=.05?25:e.hp/e.maxHp<=.1?15:5,chance=clamp((e.rarity==='傳說'?3:e.rarity==='稀有'?10:e.rarity==='精英'?20:35)+extra+low,1,90);if(Math.random()*100<chance){const old=s.bossPartners.find(x=>x.id===e.name);if(old)old.souls+=seals[e.rarity]||1;else s.bossPartners.push({id:e.name,name:e.name,rarity:e.rarity,level:1,exp:0,stars:1,hp:e.maxHp,attack:Math.ceil(e.attack*.6),defense:Math.ceil(e.defense*.6),speed:10,skill:'Boss 技能',passive:'協戰加成',souls:0,deployed:!s.bossPartners.some(x=>x.deployed)});s.hunting.maps[mapOf(s).id].kills=0;s.hunting.maps[mapOf(s).id].bossDefeated=true;s.hunting.captures++;s.exploration.enemy=null;log(s,`收服成功！收服率 ${chance}%。`,true);return {ok:true,message:'收服成功！'};}const effect=['立即反擊','回復生命','進入狂暴','逃走','戰鬥繼續'][Math.floor(Math.random()*5)];if(effect==='回復生命')e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.1);if(effect==='進入狂暴')e.attack=Math.floor(e.attack*1.3);if(effect==='逃走')s.exploration.enemy=null;log(s,`收服失敗（${chance}%）：Boss ${effect}。`,true);return {ok:false,message:`收服失敗：${effect}`};}
export function equipGear(s,id){const g=s.gearInstances.find(x=>x.instanceId===id);if(!g)return false;const old=s.gearInstances.find(x=>x.instanceId===s.instanceEquipment[g.slot]);if(old){s.player.attack-=old.baseStats.attack||0;s.player.defense-=old.baseStats.defense||0;}s.instanceEquipment[g.slot]=id;s.player.attack+=g.baseStats.attack||0;s.player.defense+=g.baseStats.defense||0;log(s,`已裝備 ${g.name}。`);return true;}
export function toggleGear(s,id){const g=s.gearInstances.find(x=>x.instanceId===id);if(g)g.locked=!g.locked;}
export function sellGear(s,id){const g=s.gearInstances.find(x=>x.instanceId===id);if(!g||g.locked)return false;s.player.gold+=Math.max(1,(g.baseStats.attack+g.baseStats.defense)*2);s.gearInstances=s.gearInstances.filter(x=>x.instanceId!==id);if(s.instanceEquipment[g.slot]===id)s.instanceEquipment[g.slot]=null;return true;}
export function deployPartner(s,id){s.bossPartners.forEach(x=>x.deployed=x.id===id);}
export function starPartner(s,id){const x=s.bossPartners.find(v=>v.id===id),need=[2,5,10,20][(x?.stars||1)-1];if(!x||!need||x.souls<need)return false;x.souls-=need;x.stars++;x.attack+=Math.ceil(x.attack*.12);x.defense+=Math.ceil(x.defense*.1);return true;}
