import {byId} from './data.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(action,text,cls='')=>`<button data-action="${action}" class="${cls}">${text}</button>`;
const nav=()=>`<nav class="game-nav">${btn('screen:home','首頁')}${btn('screen:maps','地圖')}${btn('screen:inventory','背包')}${btn('screen:heroes','武將')}${btn('screen:artifacts','神器')}${btn('screen:dungeons','副本')}${btn('screen:souls','戰魂')}${btn('screen:quests','任務')}${btn('screen:settings','設定')}</nav>`;
const bar=p=>`<div class="topbar"><strong>${esc(p.name)} Lv.${p.level}</strong><span>HP ${p.hp}/${p.maxHp}</span><span>MP ${p.mp}/${p.maxMp}</span><span>金 ${p.gold}</span><span>元寶 ${p.gems}</span></div>`;
function home(s,d){const e=s.exploration.enemy,map=byId(d.maps,s.mapId);return `<section class="screen card">${bar(s.player)}<div class="hero-banner"><div><small>${s.player.rank} · ${s.weather}</small><h2>${map.name}</h2><p>${map.description}</p></div><div class="level-badge">Lv.${s.player.level}</div></div>${e?`<div class="enemy-panel ${e.isBoss?'boss':''}"><small>${e.isBoss?'BOSS':'遭遇敵人'}</small><h3>${e.name}</h3><div class="meter"><i style="width:${e.hp/e.maxHp*100}%"></i></div><span>HP ${e.hp}/${e.maxHp}</span></div>`:'<div class="notice">隊伍正在城中整備，選擇地圖後即可自動探索。</div>'}<div class="explore-actions">${s.exploration.running?btn('stop','停止探索','btn-danger'):btn('start','開始自動探索','btn-main')}</div><div class="battle-log" role="log">${s.log.map(line=>`<div>${esc(line)}</div>`).join('')}</div><div class="summary-grid"><div>探索<b>${s.exploration.count}</b></div><div>擊殺<b>${s.exploration.kills}</b></div><div>首領<b>${s.exploration.bosses}</b></div><div>武將<b>${s.heroes.length}/120</b></div></div></section>`;}
function maps(s,d){return `<section class="screen card">${bar(s.player)}<h2 class="section-title">十二州郡</h2><div class="world-grid">${d.maps.map(m=>`<article class="${s.mapId===m.id?'selected':''}"><small>建議 Lv.${m.level} · ${m.weather}</small><h3>${m.name}</h3><p>${m.description}</p>${btn(`map:${m.id}`,s.mapId===m.id?'目前所在地':'前往')}</article>`).join('')}</div></section>`;}
function inventory(s,d){return `<section class="screen card">${bar(s.player)}<h2 class="section-title">背包與裝備</h2><div class="item-list">${s.inventory.map(entry=>{const item=byId(d.items,entry.id);return item?`<article class="item quality-${item.quality}"><div><h3>${item.name} × ${entry.quantity}</h3><p>${item.type}${item.slot?` · ${item.slot}`:''} · ${item.quality||'普通'}</p></div>${item.type==='裝備'?btn(`equip:${item.id}`,'裝備'):''}</article>`:'';}).join('')||'<p class="empty">背包是空的。</p>'}</div></section>`;}
function heroes(s,d){const owned=s.heroes.map(progress=>({progress,hero:byId(d.heroes,typeof progress==='string'?progress:progress.id)})).filter(x=>x.hero);return `<section class="screen card">${bar(s.player)}<h2 class="section-title">武將養成 ${owned.length}/120</h2><p class="lead">Lv.10 起可突破，每 10 級開放一階；Lv.50 且突破五階後可轉生。轉生會重置等級與突破，並永久提高戰力。</p><div class="hero-grid">${owned.map(({hero:h,progress:p})=>`<article><span>${h.rarity}</span><h3>${h.name}</h3><p>${h.title}<br>Lv.${p.level} · 突破 ${p.breakthrough} 階 · 轉生 ${p.rebirth} 次<br>統 ${h.leadership} · 武 ${h.might} · 智 ${h.intellect} · 敏 ${h.agility}</p><div class="growth-actions">${btn(`hero-train:${h.id}`,'訓練')}${btn(`hero-break:${h.id}`,'突破')}${btn(`hero-rebirth:${h.id}`,'轉生')}</div></article>`).join('')||'<p class="empty">尚未招募武將。</p>'}</div></section>`;}
function artifacts(s,d){return `<section class="screen card">${bar(s.player)}<h2 class="section-title">神器進化與覺醒</h2><p class="lead">副本會掉落神器碎片。神器進化至五階後，可消耗 30 枚碎片覺醒，使能力效果翻倍。</p><div class="artifact-grid">${d.artifacts.map(a=>{const x=s.artifacts[a.id]||{level:0,shards:0,awakened:false},active=s.activeArtifact===a.id;return `<article class="${active?'active':''}"><small>${x.awakened?'已覺醒':`進化 ${x.level}/5`}</small><h3>${a.name}</h3><p>${a.description}<br>碎片 ${x.shards} · 攻 ${a.attack} · 防 ${a.defense} · 速 ${a.speed}</p><div class="growth-actions">${btn(`artifact-evolve:${a.id}`,'進化')}${btn(`artifact-awaken:${a.id}`,'覺醒')}${btn(`artifact-set:${a.id}`,active?'使用中':'裝備')}</div></article>`;}).join('')}</div></section>`;}
function dungeons(s,d){const chapters=[...new Set(d.dungeons.map(x=>x.chapter))];return `<section class="screen card">${bar(s.player)}<h2 class="section-title">戰役副本</h2><p class="lead">每章分為普通、困難、地獄、深淵。高難度提高戰魂收服率與神器碎片獎勵。</p>${chapters.map(chapter=>`<div class="dungeon-chapter"><h3>${chapter}</h3><div class="difficulty-grid">${d.dungeons.filter(x=>x.chapter===chapter).map(x=>`<article class="difficulty-${x.difficulty}"><b>${x.difficulty}</b><small>建議 Lv.${x.level}</small><span>獎勵 ${x.rewardGold} 金／${x.rewardShards} 碎片</span><span>通關 ${s.dungeon.completions[x.id]||0} 次</span>${btn(`dungeon:${x.id}`,'挑戰',s.player.level<x.level?'locked':'')}</article>`).join('')}</div></div>`).join('')}</section>`;}
function souls(s){return `<section class="screen card">${bar(s.player)}<h2 class="section-title">戰魂收服</h2><p class="lead">擊敗 BOSS 後有機會收服戰魂。重複收服會轉為魂印；兩枚魂印可升階。世界頭目收服率較低，但戰力更高。</p><div class="soul-grid">${s.bossSouls.map(x=>`<article class="${s.activeSoul===x.id?'active':''}"><small>${x.rank} 階戰魂</small><h3>${x.name}</h3><p>Lv.${x.level} · 魂印 ${x.seals}<br>協戰攻擊 +${x.attack*x.rank} · 防禦 +${x.defense*x.rank}</p><div class="growth-actions">${btn(`soul-train:${x.id}`,'強化')}${btn(`soul-rank:${x.id}`,'升階')}${btn(`soul-set:${x.id}`,s.activeSoul===x.id?'協戰中':'編入協戰')}</div></article>`).join('')||'<p class="empty">尚未收服戰魂。前往副本討伐 BOSS 吧！</p>'}</div></section>`;}
function quests(s,d){return `<section class="screen card">${bar(s.player)}<h2 class="section-title">任務與成就</h2><div class="summary-grid"><div>主支線<b>${d.quests.length}</b></div><div>每日任務<b>${d.dailyquests.length}</b></div><div>成就<b>${d.achievements.length}</b></div><div>技能<b>${d.skills.length}</b></div></div><div class="item-list">${d.quests.slice(0,12).map(q=>`<article class="item"><div><h3>${q.name}</h3><p>${q.type} · ${q.description}<br>獎勵 ${q.rewardGold} 金／${q.rewardExp} EXP</p></div></article>`).join('')}</div></section>`;}
function settings(s,d){const x=s.exploration;return `<section class="screen card">${bar(s.player)}<h2 class="section-title">自動探索設定</h2><div class="settings-grid"><label><input type="checkbox" data-setting="autoHeal" ${x.autoHeal?'checked':''}> 自動補血</label><label>補血門檻 <input type="number" data-setting="healBelow" value="${x.healBelow}" min="10" max="90">%</label><label>回城門檻 <input type="number" data-setting="returnBelow" value="${x.returnBelow}" min="1" max="80">%</label><label>背包上限 <input type="number" data-setting="bagLimit" value="${x.bagLimit}" min="20" max="999"></label><label><input type="checkbox" data-setting="autoSellWhite" ${x.autoSellWhite?'checked':''}> 自動販售白裝</label><label><input type="checkbox" data-setting="autoDismantle" ${x.autoDismantle?'checked':''}> 自動分解低階裝</label><label>陣型 <select data-formation>${d.formations.map(f=>`<option value="${f.id}" ${s.formation===f.id?'selected':''}>${f.name}</option>`).join('')}</select></label><label>速度 <select data-speed><option value="1">×1</option><option value="2" ${s.settings.speed===2?'selected':''}>×2</option><option value="4" ${s.settings.speed===4?'selected':''}>×4</option></select></label></div><div class="menu">${btn('save','手動存檔','btn-good')}${btn('export','匯出 JSON')}${btn('import','匯入 JSON')}<input id="save-file" type="file" accept="application/json" hidden></div></section>`;}
export function render(s,d){const views={home,maps,inventory,heroes,artifacts,dungeons,souls,quests,settings};return `<div class="app-wrap"><header class="masthead"><h1 class="title">群雄天下</h1><div class="subtitle">三國文字放置 RPG · 2.1</div></header>${nav()}${(views[s.screen]||home)(s,d)}</div>`;}
