// 介面以狩獵循環為主，其他既有系統保留為延伸頁面。
import {mapOf,mapOpen,huntMaps} from './hunting-core.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(a,t,c='')=>`<button data-action="${a}" class="${c}">${t}</button>`;
const bar=p=>`<div class="topbar"><strong>${esc(p.name)} Lv.${p.level}</strong><span>HP ${p.hp}/${p.maxHp}</span><span>攻 ${p.attack}／防 ${p.defense}</span><span>EXP ${p.exp}</span><span>金 ${p.gold}</span></div>`;
const nav=()=>`<nav class="game-nav">${btn('screen:home','狩獵')}${btn('screen:maps','地圖')}${btn('screen:inventory','背包')}${btn('screen:partners','Boss')}${btn('screen:heroes','角色')}${btn('screen:settings','設定')}</nav>`;
function home(s){const m=mapOf(s),e=s.exploration.enemy,progress=s.hunting.maps[m.id],partner=s.bossPartners.find(x=>x.deployed);return `<section class="screen card">${bar(s.player)}<div class="hero-banner"><div><small>${s.hunting.rank}</small><h2>${m.name}</h2><p>Boss 氣息 ${progress.kills}/${m.threshold} ・ 上陣夥伴：${partner?.name||'無'}</p></div><div class="level-badge">Lv.${s.player.level}</div></div>${e?`<div class="enemy-panel ${e.boss?'boss':''}"><small>${e.boss?'BOSS':'遭遇敵人'} ${e.kind==='elite'?'・精英':''}</small><h3>${e.name}</h3><div class="meter"><i style="width:${Math.max(0,e.hp/e.maxHp*100)}%"></i></div><span>HP ${Math.max(0,Math.ceil(e.hp))}/${e.maxHp}</span>${e.catchable?`<div class="growth-actions">${btn('capture:normal',`普通符 ${s.captureItems.normal}`)}${btn('capture:advanced',`高級符 ${s.captureItems.advanced}`)}${btn('capture:legendary',`傳說符 ${s.captureItems.legendary}`)}</div>`:''}</div>`:'<div class="notice">自動打怪、升級、掉寶；氣息滿時 Boss 必定出現。</div>'}<div class="battle-actions">${btn('hunt-once','狩獵一次')}${s.exploration.running?btn('stop','停止自動狩獵','btn-danger'):btn('start','開始自動狩獵','btn-main')}</div><div class="battle-log">${s.log.map(x=>`<div>${esc(x)}</div>`).join('')}</div></section>`;}
function maps(s){return `<section class="screen card">${bar(s.player)}<h2 class="section-title">狩獵地圖</h2><div class="item-list">${huntMaps.map(m=>{const open=mapOpen(s,m),x=s.hunting.maps[m.id];return `<article class="item"><div><h3>${m.name} <span class="equip">${m.level}</span></h3><p>普通怪：${m.normal.join('、')}<br>精英：${m.elite}　Boss：${m.boss}<br>隱藏 Boss：${m.hidden}　專屬掉落：${m.drop}<br>擊殺 ${x.kills}/${m.threshold}　${x.bossDefeated?'Boss 已擊敗':'尚未擊敗'}</p></div>${btn(`hunt-map:${m.id}`,open?'前往':'未解鎖',open?'btn-main':'locked')}</article>`;}).join('')}</div></section>`;}
function inventory(s){const equipped=Object.values(s.instanceEquipment).filter(Boolean);return `<section class="screen card">${bar(s.player)}<h2 class="section-title">裝備背包</h2><div class="notice">目前武器：${s.gearInstances.find(g=>g.instanceId===s.instanceEquipment.weapon)?.name||'未裝備'}<br>目前護甲：${s.gearInstances.find(g=>g.instanceId===s.instanceEquipment.armor)?.name||'未裝備'}</div><div class="item-list">${s.gearInstances.length?s.gearInstances.map(g=>{const on=equipped.includes(g.instanceId);return `<article class="item"><div><h3>${g.name} <span class="equip">${g.quality}${on?'・已裝備':''}${g.locked?'・鎖定':''}</span></h3><p>Lv.${g.level}　攻 +${g.baseStats.attack}／防 +${g.baseStats.defense}<br>${g.affixes.join('、')||'無隨機詞條'}</p></div><div class="item-actions">${btn(`gear-equip:${g.instanceId}`,on?'已裝備':'裝備')}${btn(`gear-lock:${g.instanceId}`,g.locked?'解鎖':'鎖定')}${btn(`gear-sell:${g.instanceId}`,'出售')}</div></article>`;}).join(''):'<p class="empty">尚未獲得裝備。</p>'}</div></section>`;}
function partners(s){return `<section class="screen card">${bar(s.player)}<h2 class="section-title">Boss 夥伴</h2><div class="soul-grid">${s.bossPartners.length?s.bossPartners.map(x=>`<article class="${x.deployed?'active':''}"><small>${x.rarity}・${x.stars} 星</small><h3>${x.name}</h3><p>Lv.${x.level}　攻 ${x.attack}／防 ${x.defense}<br>技能：${x.skill}<br>魂印：${x.souls}</p><div class="growth-actions">${btn(`partner-deploy:${x.id}`,x.deployed?'上陣中':'上陣')}${btn(`partner-star:${x.id}`,'升星')}</div></article>`).join(''):'<p class="empty">尚未收服 Boss。</p>'}</div></section>`;}
function settings(s){const a=s.hunting.auto;return `<section class="screen card">${bar(s.player)}<h2 class="section-title">自動狩獵設定</h2><div class="settings-grid"><label><input type="checkbox" data-auto="heal" ${a.heal?'checked':''}> 自動補血</label><label>補血門檻 <input type="number" data-auto="healBelow" value="${a.healBelow}" min="10" max="90">%</label><label>回城門檻 <input type="number" data-auto="returnBelow" value="${a.returnBelow}" min="1" max="80">%</label><label><input type="checkbox" data-auto="autoCapture" ${a.autoCapture?'checked':''}> 自動嘗試收服</label><label><input type="checkbox" data-auto="autoBoss" ${a.autoBoss?'checked':''}> Boss 自動挑戰</label><label>速度 <select data-auto="speed"><option value="1">標準</option><option value="2" ${a.speed===2?'selected':''}>快速</option><option value="4" ${a.speed===4?'selected':''}>極速</option></select></label></div><div class="menu">${btn('save','儲存進度','btn-good')}${btn('export','匯出存檔')}${btn('import','匯入存檔')}<input id="save-file" type="file" accept="application/json" hidden></div></section>`;}
export function render(s){const view={home,maps,inventory,partners,settings,heroes:partners};return `<div class="app-wrap"><header class="masthead"><h1 class="title">群雄天下</h1><div class="subtitle">自動狩獵・Boss 收服・夥伴培養</div></header>${nav()}${(view[s.screen]||home)(s)}</div>`;}
